# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'planGenerator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(1008, 786)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.ship_name_edit = QtGui.QLineEdit(self.groupBox)
        self.ship_name_edit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ship_name_edit.sizePolicy().hasHeightForWidth())
        self.ship_name_edit.setSizePolicy(sizePolicy)
        self.ship_name_edit.setObjectName(_fromUtf8("ship_name_edit"))
        self.horizontalLayout.addWidget(self.ship_name_edit)
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.voyage_number_edit = QtGui.QLineEdit(self.groupBox)
        self.voyage_number_edit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voyage_number_edit.sizePolicy().hasHeightForWidth())
        self.voyage_number_edit.setSizePolicy(sizePolicy)
        self.voyage_number_edit.setObjectName(_fromUtf8("voyage_number_edit"))
        self.horizontalLayout.addWidget(self.voyage_number_edit)
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.from_edit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_edit.sizePolicy().hasHeightForWidth())
        self.from_edit.setSizePolicy(sizePolicy)
        self.from_edit.setObjectName(_fromUtf8("from_edit"))
        self.horizontalLayout.addWidget(self.from_edit)
        self.label_4 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.to_edit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_edit.sizePolicy().hasHeightForWidth())
        self.to_edit.setSizePolicy(sizePolicy)
        self.to_edit.setObjectName(_fromUtf8("to_edit"))
        self.horizontalLayout.addWidget(self.to_edit)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.add_row_btn = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_row_btn.sizePolicy().hasHeightForWidth())
        self.add_row_btn.setSizePolicy(sizePolicy)
        self.add_row_btn.setObjectName(_fromUtf8("add_row_btn"))
        self.horizontalLayout_3.addWidget(self.add_row_btn)
        self.csv_edit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_edit.sizePolicy().hasHeightForWidth())
        self.csv_edit.setSizePolicy(sizePolicy)
        self.csv_edit.setObjectName(_fromUtf8("csv_edit"))
        self.horizontalLayout_3.addWidget(self.csv_edit)
        self.browse_btn = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_btn.sizePolicy().hasHeightForWidth())
        self.browse_btn.setSizePolicy(sizePolicy)
        self.browse_btn.setObjectName(_fromUtf8("browse_btn"))
        self.horizontalLayout_3.addWidget(self.browse_btn)
        self.export_esv_btn = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_esv_btn.sizePolicy().hasHeightForWidth())
        self.export_esv_btn.setSizePolicy(sizePolicy)
        self.export_esv_btn.setObjectName(_fromUtf8("export_esv_btn"))
        self.horizontalLayout_3.addWidget(self.export_esv_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.calculate_form_table_widget = QtGui.QTableWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate_form_table_widget.sizePolicy().hasHeightForWidth())
        self.calculate_form_table_widget.setSizePolicy(sizePolicy)
        self.calculate_form_table_widget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.calculate_form_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.calculate_form_table_widget.setRowCount(10)
        self.calculate_form_table_widget.setObjectName(_fromUtf8("calculate_form_table_widget"))
        self.calculate_form_table_widget.setColumnCount(9)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.calculate_form_table_widget.setHorizontalHeaderItem(8, item)
        self.calculate_form_table_widget.horizontalHeader().setCascadingSectionResizes(True)
        self.calculate_form_table_widget.horizontalHeader().setDefaultSectionSize(100)
        self.calculate_form_table_widget.horizontalHeader().setMinimumSectionSize(32)
        self.calculate_form_table_widget.horizontalHeader().setStretchLastSection(True)
        self.calculate_form_table_widget.verticalHeader().setVisible(False)
        self.calculate_form_table_widget.verticalHeader().setCascadingSectionResizes(True)
        self.calculate_form_table_widget.verticalHeader().setDefaultSectionSize(40)
        self.calculate_form_table_widget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.calculate_form_table_widget)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.label.setBuddy(self.ship_name_edit)
        self.label_2.setBuddy(self.voyage_number_edit)
        self.label_3.setBuddy(self.from_edit)
        self.label_4.setBuddy(self.to_edit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.ship_name_edit, self.voyage_number_edit)
        Form.setTabOrder(self.voyage_number_edit, self.from_edit)
        Form.setTabOrder(self.from_edit, self.to_edit)
        Form.setTabOrder(self.to_edit, self.add_row_btn)
        Form.setTabOrder(self.add_row_btn, self.csv_edit)
        Form.setTabOrder(self.csv_edit, self.browse_btn)
        Form.setTabOrder(self.browse_btn, self.export_esv_btn)
        Form.setTabOrder(self.export_esv_btn, self.calculate_form_table_widget)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Plan Generator", None))
        self.groupBox.setTitle(_translate("Form", "Voyage Data", None))
        self.label.setText(_translate("Form", "Ship Name", None))
        self.label_2.setText(_translate("Form", "Voyage Number", None))
        self.label_3.setText(_translate("Form", "From", None))
        self.label_4.setText(_translate("Form", "To", None))
        self.groupBox_2.setTitle(_translate("Form", "Calculate", None))
        self.add_row_btn.setText(_translate("Form", "Add Row", None))
        self.browse_btn.setText(_translate("Form", "Browse", None))
        self.export_esv_btn.setText(_translate("Form", "Export To Excel", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(0)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(1)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(2)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(3)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(4)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(5)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(6)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(7)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(8)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.verticalHeaderItem(9)
        item.setText(_translate("Form", "新建行", None))
        item = self.calculate_form_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "WP No.", None))
        item = self.calculate_form_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Latitude", None))
        item = self.calculate_form_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Longtitude", None))
        item = self.calculate_form_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "GC/RL", None))
        item = self.calculate_form_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Course", None))
        item = self.calculate_form_table_widget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Distance", None))
        item = self.calculate_form_table_widget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Total DTG(nm)", None))
        item = self.calculate_form_table_widget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "UKC(m)", None))
        item = self.calculate_form_table_widget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Master\'s Instruction\n"
"Danger&Hazards \n"
"Remarks", None))

