# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'revertRoute.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(898, 773)
        Form.setAutoFillBackground(True)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.voyageDetailGroupBox = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voyageDetailGroupBox.sizePolicy().hasHeightForWidth())
        self.voyageDetailGroupBox.setSizePolicy(sizePolicy)
        self.voyageDetailGroupBox.setObjectName(_fromUtf8("voyageDetailGroupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.voyageDetailGroupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_2 = QtGui.QGroupBox(self.voyageDetailGroupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_19.addWidget(self.label_10)
        self.departure_country_combo = QtGui.QComboBox(self.groupBox_2)
        self.departure_country_combo.setEditable(True)
        self.departure_country_combo.setMaxVisibleItems(15)
        self.departure_country_combo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.departure_country_combo.setObjectName(_fromUtf8("departure_country_combo"))
        self.horizontalLayout_19.addWidget(self.departure_country_combo)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_19.addWidget(self.label_11)
        self.departure_port_combo = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_port_combo.sizePolicy().hasHeightForWidth())
        self.departure_port_combo.setSizePolicy(sizePolicy)
        self.departure_port_combo.setEditable(True)
        self.departure_port_combo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.departure_port_combo.setObjectName(_fromUtf8("departure_port_combo"))
        self.horizontalLayout_19.addWidget(self.departure_port_combo)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_18.addWidget(self.label_6)
        self.depart_date_edit = QtGui.QDateEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depart_date_edit.sizePolicy().hasHeightForWidth())
        self.depart_date_edit.setSizePolicy(sizePolicy)
        self.depart_date_edit.setCalendarPopup(True)
        self.depart_date_edit.setTimeSpec(QtCore.Qt.LocalTime)
        self.depart_date_edit.setObjectName(_fromUtf8("depart_date_edit"))
        self.horizontalLayout_18.addWidget(self.depart_date_edit)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_18.addWidget(self.label_7)
        self.departure_time_edit = QtGui.QTimeEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_time_edit.sizePolicy().hasHeightForWidth())
        self.departure_time_edit.setSizePolicy(sizePolicy)
        self.departure_time_edit.setCalendarPopup(True)
        self.departure_time_edit.setObjectName(_fromUtf8("departure_time_edit"))
        self.horizontalLayout_18.addWidget(self.departure_time_edit)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_18.addWidget(self.label_12)
        self.departure_unlo_edit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_unlo_edit.sizePolicy().hasHeightForWidth())
        self.departure_unlo_edit.setSizePolicy(sizePolicy)
        self.departure_unlo_edit.setObjectName(_fromUtf8("departure_unlo_edit"))
        self.horizontalLayout_18.addWidget(self.departure_unlo_edit)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_18.addWidget(self.label_13)
        self.departure_terminal_edit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_terminal_edit.sizePolicy().hasHeightForWidth())
        self.departure_terminal_edit.setSizePolicy(sizePolicy)
        self.departure_terminal_edit.setObjectName(_fromUtf8("departure_terminal_edit"))
        self.horizontalLayout_18.addWidget(self.departure_terminal_edit)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_7 = QtGui.QGroupBox(self.voyageDetailGroupBox)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_8 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_20.addWidget(self.label_8)
        self.arrival_date_edit = QtGui.QDateEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_date_edit.sizePolicy().hasHeightForWidth())
        self.arrival_date_edit.setSizePolicy(sizePolicy)
        self.arrival_date_edit.setCalendarPopup(True)
        self.arrival_date_edit.setObjectName(_fromUtf8("arrival_date_edit"))
        self.horizontalLayout_20.addWidget(self.arrival_date_edit)
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_20.addWidget(self.label_9)
        self.arrival_time_edit = QtGui.QTimeEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_time_edit.sizePolicy().hasHeightForWidth())
        self.arrival_time_edit.setSizePolicy(sizePolicy)
        self.arrival_time_edit.setCalendarPopup(True)
        self.arrival_time_edit.setObjectName(_fromUtf8("arrival_time_edit"))
        self.horizontalLayout_20.addWidget(self.arrival_time_edit)
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_20.addWidget(self.label_16)
        self.arrival_unlo_edit = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_unlo_edit.sizePolicy().hasHeightForWidth())
        self.arrival_unlo_edit.setSizePolicy(sizePolicy)
        self.arrival_unlo_edit.setObjectName(_fromUtf8("arrival_unlo_edit"))
        self.horizontalLayout_20.addWidget(self.arrival_unlo_edit)
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_20.addWidget(self.label_17)
        self.arrival_terminal_edit = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_terminal_edit.sizePolicy().hasHeightForWidth())
        self.arrival_terminal_edit.setSizePolicy(sizePolicy)
        self.arrival_terminal_edit.setObjectName(_fromUtf8("arrival_terminal_edit"))
        self.horizontalLayout_20.addWidget(self.arrival_terminal_edit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_21.addWidget(self.label_14)
        self.arrival_country_combo = QtGui.QComboBox(self.groupBox_7)
        self.arrival_country_combo.setEditable(True)
        self.arrival_country_combo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.arrival_country_combo.setObjectName(_fromUtf8("arrival_country_combo"))
        self.horizontalLayout_21.addWidget(self.arrival_country_combo)
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_21.addWidget(self.label_15)
        self.arrival_port_combo = QtGui.QComboBox(self.groupBox_7)
        self.arrival_port_combo.setEditable(True)
        self.arrival_port_combo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.arrival_port_combo.setObjectName(_fromUtf8("arrival_port_combo"))
        self.horizontalLayout_21.addWidget(self.arrival_port_combo)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.verticalLayout_6.addWidget(self.groupBox_7)
        self.widget = QtGui.QWidget(self.voyageDetailGroupBox)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_19 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_8.addWidget(self.label_19)
        self.use_dw_route_yes_radio = QtGui.QRadioButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_dw_route_yes_radio.sizePolicy().hasHeightForWidth())
        self.use_dw_route_yes_radio.setSizePolicy(sizePolicy)
        self.use_dw_route_yes_radio.setAutoExclusive(True)
        self.use_dw_route_yes_radio.setObjectName(_fromUtf8("use_dw_route_yes_radio"))
        self.horizontalLayout_8.addWidget(self.use_dw_route_yes_radio)
        self.use_dw_route_no_radio = QtGui.QRadioButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_dw_route_no_radio.sizePolicy().hasHeightForWidth())
        self.use_dw_route_no_radio.setSizePolicy(sizePolicy)
        self.use_dw_route_no_radio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.use_dw_route_no_radio.setAutoExclusive(True)
        self.use_dw_route_no_radio.setObjectName(_fromUtf8("use_dw_route_no_radio"))
        self.horizontalLayout_8.addWidget(self.use_dw_route_no_radio)
        self.verticalLayout_6.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.voyageDetailGroupBox)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_20 = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_9.addWidget(self.label_20)
        self.critial_yes_radio = QtGui.QRadioButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.critial_yes_radio.sizePolicy().hasHeightForWidth())
        self.critial_yes_radio.setSizePolicy(sizePolicy)
        self.critial_yes_radio.setAutoExclusive(True)
        self.critial_yes_radio.setObjectName(_fromUtf8("critial_yes_radio"))
        self.horizontalLayout_9.addWidget(self.critial_yes_radio)
        self.critial_no_radio = QtGui.QRadioButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.critial_no_radio.sizePolicy().hasHeightForWidth())
        self.critial_no_radio.setSizePolicy(sizePolicy)
        self.critial_no_radio.setInputMethodHints(QtCore.Qt.ImhNone)
        self.critial_no_radio.setAutoExclusive(True)
        self.critial_no_radio.setObjectName(_fromUtf8("critial_no_radio"))
        self.horizontalLayout_9.addWidget(self.critial_no_radio)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.groupBox_4 = QtGui.QGroupBox(self.voyageDetailGroupBox)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.critial_point_add_btn = QtGui.QPushButton(self.groupBox_4)
        self.critial_point_add_btn.setObjectName(_fromUtf8("critial_point_add_btn"))
        self.verticalLayout.addWidget(self.critial_point_add_btn)
        self.critial_point_delete_btn = QtGui.QPushButton(self.groupBox_4)
        self.critial_point_delete_btn.setObjectName(_fromUtf8("critial_point_delete_btn"))
        self.verticalLayout.addWidget(self.critial_point_delete_btn)
        self.gridLayout_6.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.scrollArea_3 = QtGui.QScrollArea(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(0, 91))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 731, 313))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.critial_point_table_widget = QtGui.QTableWidget(self.scrollAreaWidgetContents_3)
        self.critial_point_table_widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.critial_point_table_widget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.critial_point_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.critial_point_table_widget.setObjectName(_fromUtf8("critial_point_table_widget"))
        self.critial_point_table_widget.setColumnCount(3)
        self.critial_point_table_widget.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setHorizontalHeaderItem(2, item)
        self.critial_point_table_widget.horizontalHeader().setCascadingSectionResizes(True)
        self.critial_point_table_widget.horizontalHeader().setDefaultSectionSize(200)
        self.critial_point_table_widget.horizontalHeader().setMinimumSectionSize(200)
        self.critial_point_table_widget.horizontalHeader().setStretchLastSection(True)
        self.critial_point_table_widget.verticalHeader().setVisible(False)
        self.critial_point_table_widget.verticalHeader().setCascadingSectionResizes(True)
        self.critial_point_table_widget.verticalHeader().setDefaultSectionSize(30)
        self.critial_point_table_widget.verticalHeader().setMinimumSectionSize(30)
        self.critial_point_table_widget.verticalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.critial_point_table_widget, 0, 1, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_6.addWidget(self.scrollArea_3, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 2)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.gridLayout_12.addWidget(self.voyageDetailGroupBox, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.ship_name_edit = QtGui.QLineEdit(self.tab)
        self.ship_name_edit.setEnabled(False)
        self.ship_name_edit.setObjectName(_fromUtf8("ship_name_edit"))
        self.horizontalLayout.addWidget(self.ship_name_edit)
        self.label_2 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.call_sign_edit = QtGui.QLineEdit(self.tab)
        self.call_sign_edit.setEnabled(False)
        self.call_sign_edit.setObjectName(_fromUtf8("call_sign_edit"))
        self.horizontalLayout.addWidget(self.call_sign_edit)
        self.label_4 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.captain_name_edit = QtGui.QLineEdit(self.tab)
        self.captain_name_edit.setEnabled(False)
        self.captain_name_edit.setObjectName(_fromUtf8("captain_name_edit"))
        self.horizontalLayout.addWidget(self.captain_name_edit)
        self.label_5 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.date_edit = QtGui.QLineEdit(self.tab)
        self.date_edit.setEnabled(False)
        self.date_edit.setObjectName(_fromUtf8("date_edit"))
        self.horizontalLayout.addWidget(self.date_edit)
        self.label_3 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.voyage_number_edit = QtGui.QLineEdit(self.tab)
        self.voyage_number_edit.setEnabled(True)
        self.voyage_number_edit.setObjectName(_fromUtf8("voyage_number_edit"))
        self.horizontalLayout.addWidget(self.voyage_number_edit)
        self.gridLayout_12.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.via_name_edit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_name_edit.sizePolicy().hasHeightForWidth())
        self.via_name_edit.setSizePolicy(sizePolicy)
        self.via_name_edit.setObjectName(_fromUtf8("via_name_edit"))
        self.verticalLayout_5.addWidget(self.via_name_edit)
        self.via_listWidget = QtGui.QListWidget(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_listWidget.sizePolicy().hasHeightForWidth())
        self.via_listWidget.setSizePolicy(sizePolicy)
        self.via_listWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.via_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.via_listWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.via_listWidget.setResizeMode(QtGui.QListView.Fixed)
        self.via_listWidget.setObjectName(_fromUtf8("via_listWidget"))
        self.verticalLayout_5.addWidget(self.via_listWidget)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.via_add_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_add_btn.sizePolicy().hasHeightForWidth())
        self.via_add_btn.setSizePolicy(sizePolicy)
        self.via_add_btn.setObjectName(_fromUtf8("via_add_btn"))
        self.verticalLayout_4.addWidget(self.via_add_btn)
        self.via_remove_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_remove_btn.sizePolicy().hasHeightForWidth())
        self.via_remove_btn.setSizePolicy(sizePolicy)
        self.via_remove_btn.setObjectName(_fromUtf8("via_remove_btn"))
        self.verticalLayout_4.addWidget(self.via_remove_btn)
        self.via_up_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_up_btn.sizePolicy().hasHeightForWidth())
        self.via_up_btn.setSizePolicy(sizePolicy)
        self.via_up_btn.setObjectName(_fromUtf8("via_up_btn"))
        self.verticalLayout_4.addWidget(self.via_up_btn)
        self.via_down_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_down_btn.sizePolicy().hasHeightForWidth())
        self.via_down_btn.setSizePolicy(sizePolicy)
        self.via_down_btn.setObjectName(_fromUtf8("via_down_btn"))
        self.verticalLayout_4.addWidget(self.via_down_btn)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_10.addWidget(self.label_23)
        self.received_route_number = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.received_route_number.sizePolicy().hasHeightForWidth())
        self.received_route_number.setSizePolicy(sizePolicy)
        self.received_route_number.setObjectName(_fromUtf8("received_route_number"))
        self.horizontalLayout_10.addWidget(self.received_route_number)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_22.addWidget(self.label_18)
        self.route_type_combo = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.route_type_combo.sizePolicy().hasHeightForWidth())
        self.route_type_combo.setSizePolicy(sizePolicy)
        self.route_type_combo.setObjectName(_fromUtf8("route_type_combo"))
        self.route_type_combo.addItem(_fromUtf8(""))
        self.route_type_combo.addItem(_fromUtf8(""))
        self.route_type_combo.addItem(_fromUtf8(""))
        self.route_type_combo.addItem(_fromUtf8(""))
        self.route_type_combo.addItem(_fromUtf8(""))
        self.route_type_combo.addItem(_fromUtf8(""))
        self.route_type_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_22.addWidget(self.route_type_combo)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_37 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_11.addWidget(self.label_37)
        self.modify_route_radio_yes = QtGui.QRadioButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modify_route_radio_yes.sizePolicy().hasHeightForWidth())
        self.modify_route_radio_yes.setSizePolicy(sizePolicy)
        self.modify_route_radio_yes.setObjectName(_fromUtf8("modify_route_radio_yes"))
        self.horizontalLayout_11.addWidget(self.modify_route_radio_yes)
        self.modify_route_radio_no = QtGui.QRadioButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modify_route_radio_no.sizePolicy().hasHeightForWidth())
        self.modify_route_radio_no.setSizePolicy(sizePolicy)
        self.modify_route_radio_no.setObjectName(_fromUtf8("modify_route_radio_no"))
        self.horizontalLayout_11.addWidget(self.modify_route_radio_no)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_38 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_23.addWidget(self.label_38)
        self.reason_modify_route_combo = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reason_modify_route_combo.sizePolicy().hasHeightForWidth())
        self.reason_modify_route_combo.setSizePolicy(sizePolicy)
        self.reason_modify_route_combo.setObjectName(_fromUtf8("reason_modify_route_combo"))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.reason_modify_route_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_23.addWidget(self.reason_modify_route_combo)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.scrollArea_4 = QtGui.QScrollArea(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 834, 228))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_39 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalLayout_10.addWidget(self.label_39)
        self.paper_chart_table_widget = QtGui.QTableWidget(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paper_chart_table_widget.sizePolicy().hasHeightForWidth())
        self.paper_chart_table_widget.setSizePolicy(sizePolicy)
        self.paper_chart_table_widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.paper_chart_table_widget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.paper_chart_table_widget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.paper_chart_table_widget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.paper_chart_table_widget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.paper_chart_table_widget.setTextElideMode(QtCore.Qt.ElideNone)
        self.paper_chart_table_widget.setObjectName(_fromUtf8("paper_chart_table_widget"))
        self.paper_chart_table_widget.setColumnCount(10)
        self.paper_chart_table_widget.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.paper_chart_table_widget.setHorizontalHeaderItem(9, item)
        self.paper_chart_table_widget.horizontalHeader().setVisible(False)
        self.paper_chart_table_widget.horizontalHeader().setCascadingSectionResizes(True)
        self.paper_chart_table_widget.horizontalHeader().setStretchLastSection(True)
        self.paper_chart_table_widget.verticalHeader().setVisible(False)
        self.paper_chart_table_widget.verticalHeader().setCascadingSectionResizes(True)
        self.paper_chart_table_widget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.paper_chart_table_widget)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.addWidget(self.scrollArea_4)
        self.gridLayout_11.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.voyageDataGroupBox = QtGui.QGroupBox(self.tab_2)
        self.voyageDataGroupBox.setObjectName(_fromUtf8("voyageDataGroupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.voyageDataGroupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_6 = QtGui.QGroupBox(self.voyageDataGroupBox)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_28 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_3.addWidget(self.label_28)
        self.maximum_draft_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximum_draft_edit.sizePolicy().hasHeightForWidth())
        self.maximum_draft_edit.setSizePolicy(sizePolicy)
        self.maximum_draft_edit.setObjectName(_fromUtf8("maximum_draft_edit"))
        self.horizontalLayout_3.addWidget(self.maximum_draft_edit)
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_3.addWidget(self.label_29)
        self.minimum_ukc_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimum_ukc_edit.sizePolicy().hasHeightForWidth())
        self.minimum_ukc_edit.setSizePolicy(sizePolicy)
        self.minimum_ukc_edit.setObjectName(_fromUtf8("minimum_ukc_edit"))
        self.horizontalLayout_3.addWidget(self.minimum_ukc_edit)
        self.label_30 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_3.addWidget(self.label_30)
        self.load_condition_combo = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_condition_combo.sizePolicy().hasHeightForWidth())
        self.load_condition_combo.setSizePolicy(sizePolicy)
        self.load_condition_combo.setObjectName(_fromUtf8("load_condition_combo"))
        self.load_condition_combo.addItem(_fromUtf8(""))
        self.load_condition_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.load_condition_combo)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_31 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_4.addWidget(self.label_31)
        self.displacement_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displacement_edit.sizePolicy().hasHeightForWidth())
        self.displacement_edit.setSizePolicy(sizePolicy)
        self.displacement_edit.setObjectName(_fromUtf8("displacement_edit"))
        self.horizontalLayout_4.addWidget(self.displacement_edit)
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_4.addWidget(self.label_27)
        self.cargo_carried = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cargo_carried.sizePolicy().hasHeightForWidth())
        self.cargo_carried.setSizePolicy(sizePolicy)
        self.cargo_carried.setObjectName(_fromUtf8("cargo_carried"))
        self.horizontalLayout_4.addWidget(self.cargo_carried)
        self.label_34 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_4.addWidget(self.label_34)
        self.average_me_rmp_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_me_rmp_edit.sizePolicy().hasHeightForWidth())
        self.average_me_rmp_edit.setSizePolicy(sizePolicy)
        self.average_me_rmp_edit.setObjectName(_fromUtf8("average_me_rmp_edit"))
        self.horizontalLayout_4.addWidget(self.average_me_rmp_edit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_12.addWidget(self.label_24)
        self.total_distance_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_distance_edit.sizePolicy().hasHeightForWidth())
        self.total_distance_edit.setSizePolicy(sizePolicy)
        self.total_distance_edit.setObjectName(_fromUtf8("total_distance_edit"))
        self.horizontalLayout_12.addWidget(self.total_distance_edit)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.label_33 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_12.addWidget(self.label_33)
        self.distance_me_revolution_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distance_me_revolution_edit.sizePolicy().hasHeightForWidth())
        self.distance_me_revolution_edit.setSizePolicy(sizePolicy)
        self.distance_me_revolution_edit.setObjectName(_fromUtf8("distance_me_revolution_edit"))
        self.horizontalLayout_12.addWidget(self.distance_me_revolution_edit)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_25 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(120, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_13.addWidget(self.label_25)
        self.total_streaming_time_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_streaming_time_edit.sizePolicy().hasHeightForWidth())
        self.total_streaming_time_edit.setSizePolicy(sizePolicy)
        self.total_streaming_time_edit.setEchoMode(QtGui.QLineEdit.Normal)
        self.total_streaming_time_edit.setReadOnly(False)
        self.total_streaming_time_edit.setObjectName(_fromUtf8("total_streaming_time_edit"))
        self.horizontalLayout_13.addWidget(self.total_streaming_time_edit)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_13.addWidget(self.label_26)
        self.log_distance_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_distance_edit.sizePolicy().hasHeightForWidth())
        self.log_distance_edit.setSizePolicy(sizePolicy)
        self.log_distance_edit.setObjectName(_fromUtf8("log_distance_edit"))
        self.horizontalLayout_13.addWidget(self.log_distance_edit)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_40 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_14.addWidget(self.label_40)
        self.average_speed_edit = QtGui.QLineEdit(self.groupBox_6)
        self.average_speed_edit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_speed_edit.sizePolicy().hasHeightForWidth())
        self.average_speed_edit.setSizePolicy(sizePolicy)
        self.average_speed_edit.setObjectName(_fromUtf8("average_speed_edit"))
        self.horizontalLayout_14.addWidget(self.average_speed_edit)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.label_32 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_14.addWidget(self.label_32)
        self.average_slip_edit = QtGui.QLineEdit(self.groupBox_6)
        self.average_slip_edit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_slip_edit.sizePolicy().hasHeightForWidth())
        self.average_slip_edit.setSizePolicy(sizePolicy)
        self.average_slip_edit.setObjectName(_fromUtf8("average_slip_edit"))
        self.horizontalLayout_14.addWidget(self.average_slip_edit)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.bunker_consume_table = QtGui.QTableWidget(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bunker_consume_table.sizePolicy().hasHeightForWidth())
        self.bunker_consume_table.setSizePolicy(sizePolicy)
        self.bunker_consume_table.setMaximumSize(QtCore.QSize(16777215, 192))
        self.bunker_consume_table.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bunker_consume_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.bunker_consume_table.setObjectName(_fromUtf8("bunker_consume_table"))
        self.bunker_consume_table.setColumnCount(4)
        self.bunker_consume_table.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.bunker_consume_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.bunker_consume_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.bunker_consume_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.bunker_consume_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.bunker_consume_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.bunker_consume_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.bunker_consume_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.bunker_consume_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.bunker_consume_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.bunker_consume_table.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.bunker_consume_table.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.bunker_consume_table.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.bunker_consume_table.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.bunker_consume_table.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.bunker_consume_table.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.bunker_consume_table.setItem(2, 3, item)
        self.bunker_consume_table.horizontalHeader().setCascadingSectionResizes(True)
        self.bunker_consume_table.horizontalHeader().setDefaultSectionSize(150)
        self.bunker_consume_table.horizontalHeader().setMinimumSectionSize(100)
        self.bunker_consume_table.horizontalHeader().setStretchLastSection(True)
        self.bunker_consume_table.verticalHeader().setCascadingSectionResizes(True)
        self.bunker_consume_table.verticalHeader().setDefaultSectionSize(50)
        self.bunker_consume_table.verticalHeader().setMinimumSectionSize(30)
        self.bunker_consume_table.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.bunker_consume_table)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_41 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_5.addWidget(self.label_41)
        self.overall_condition_combo = QtGui.QComboBox(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overall_condition_combo.sizePolicy().hasHeightForWidth())
        self.overall_condition_combo.setSizePolicy(sizePolicy)
        self.overall_condition_combo.setObjectName(_fromUtf8("overall_condition_combo"))
        self.overall_condition_combo.addItem(_fromUtf8(""))
        self.overall_condition_combo.addItem(_fromUtf8(""))
        self.overall_condition_combo.addItem(_fromUtf8(""))
        self.overall_condition_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.overall_condition_combo)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_35 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_6.addWidget(self.label_35)
        self.attach_ecdis_route_file_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.attach_ecdis_route_file_edit.setObjectName(_fromUtf8("attach_ecdis_route_file_edit"))
        self.horizontalLayout_6.addWidget(self.attach_ecdis_route_file_edit)
        self.attach_ecdis_browse_btn = QtGui.QPushButton(self.voyageDataGroupBox)
        self.attach_ecdis_browse_btn.setObjectName(_fromUtf8("attach_ecdis_browse_btn"))
        self.horizontalLayout_6.addWidget(self.attach_ecdis_browse_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_36 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_7.addWidget(self.label_36)
        self.attach_wp_plan_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.attach_wp_plan_edit.setObjectName(_fromUtf8("attach_wp_plan_edit"))
        self.horizontalLayout_7.addWidget(self.attach_wp_plan_edit)
        self.attach_wp_plan_browse_btn = QtGui.QPushButton(self.voyageDataGroupBox)
        self.attach_wp_plan_browse_btn.setObjectName(_fromUtf8("attach_wp_plan_browse_btn"))
        self.horizontalLayout_7.addWidget(self.attach_wp_plan_browse_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.label_21 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_7.addWidget(self.label_21)
        self.remark_edit = QtGui.QTextEdit(self.voyageDataGroupBox)
        self.remark_edit.setAcceptRichText(True)
        self.remark_edit.setObjectName(_fromUtf8("remark_edit"))
        self.verticalLayout_7.addWidget(self.remark_edit)
        self.label_21.raise_()
        self.bunker_consume_table.raise_()
        self.groupBox_6.raise_()
        self.remark_edit.raise_()
        self.gridLayout_10.addWidget(self.voyageDataGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.reload_btn = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reload_btn.sizePolicy().hasHeightForWidth())
        self.reload_btn.setSizePolicy(sizePolicy)
        self.reload_btn.setObjectName(_fromUtf8("reload_btn"))
        self.horizontalLayout_2.addWidget(self.reload_btn)
        self.submit_btn = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_btn.sizePolicy().hasHeightForWidth())
        self.submit_btn.setSizePolicy(sizePolicy)
        self.submit_btn.setObjectName(_fromUtf8("submit_btn"))
        self.horizontalLayout_2.addWidget(self.submit_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_10.setBuddy(self.departure_country_combo)
        self.label_11.setBuddy(self.departure_port_combo)
        self.label_6.setBuddy(self.depart_date_edit)
        self.label_7.setBuddy(self.departure_time_edit)
        self.label_12.setBuddy(self.departure_unlo_edit)
        self.label_13.setBuddy(self.departure_terminal_edit)
        self.label_8.setBuddy(self.arrival_date_edit)
        self.label_9.setBuddy(self.arrival_time_edit)
        self.label_16.setBuddy(self.arrival_unlo_edit)
        self.label_17.setBuddy(self.arrival_terminal_edit)
        self.label_14.setBuddy(self.arrival_country_combo)
        self.label_15.setBuddy(self.arrival_port_combo)
        self.label_19.setBuddy(self.use_dw_route_yes_radio)
        self.label_20.setBuddy(self.critial_yes_radio)
        self.label.setBuddy(self.ship_name_edit)
        self.label_2.setBuddy(self.call_sign_edit)
        self.label_4.setBuddy(self.captain_name_edit)
        self.label_5.setBuddy(self.date_edit)
        self.label_3.setBuddy(self.voyage_number_edit)
        self.label_23.setBuddy(self.received_route_number)
        self.label_18.setBuddy(self.route_type_combo)
        self.label_38.setBuddy(self.reason_modify_route_combo)
        self.label_28.setBuddy(self.maximum_draft_edit)
        self.label_29.setBuddy(self.minimum_ukc_edit)
        self.label_30.setBuddy(self.load_condition_combo)
        self.label_31.setBuddy(self.displacement_edit)
        self.label_27.setBuddy(self.cargo_carried)
        self.label_34.setBuddy(self.average_me_rmp_edit)
        self.label_24.setBuddy(self.total_distance_edit)
        self.label_33.setBuddy(self.distance_me_revolution_edit)
        self.label_25.setBuddy(self.total_streaming_time_edit)
        self.label_26.setBuddy(self.log_distance_edit)
        self.label_40.setBuddy(self.average_speed_edit)
        self.label_32.setBuddy(self.average_slip_edit)
        self.label_41.setBuddy(self.overall_condition_combo)
        self.label_35.setBuddy(self.attach_ecdis_route_file_edit)
        self.label_36.setBuddy(self.attach_wp_plan_edit)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.ship_name_edit, self.call_sign_edit)
        Form.setTabOrder(self.call_sign_edit, self.captain_name_edit)
        Form.setTabOrder(self.captain_name_edit, self.date_edit)
        Form.setTabOrder(self.date_edit, self.voyage_number_edit)
        Form.setTabOrder(self.voyage_number_edit, self.depart_date_edit)
        Form.setTabOrder(self.depart_date_edit, self.departure_time_edit)
        Form.setTabOrder(self.departure_time_edit, self.departure_unlo_edit)
        Form.setTabOrder(self.departure_unlo_edit, self.departure_terminal_edit)
        Form.setTabOrder(self.departure_terminal_edit, self.departure_country_combo)
        Form.setTabOrder(self.departure_country_combo, self.arrival_date_edit)
        Form.setTabOrder(self.arrival_date_edit, self.arrival_time_edit)
        Form.setTabOrder(self.arrival_time_edit, self.arrival_unlo_edit)
        Form.setTabOrder(self.arrival_unlo_edit, self.arrival_terminal_edit)
        Form.setTabOrder(self.arrival_terminal_edit, self.arrival_country_combo)
        Form.setTabOrder(self.arrival_country_combo, self.use_dw_route_yes_radio)
        Form.setTabOrder(self.use_dw_route_yes_radio, self.use_dw_route_no_radio)
        Form.setTabOrder(self.use_dw_route_no_radio, self.critial_yes_radio)
        Form.setTabOrder(self.critial_yes_radio, self.critial_no_radio)
        Form.setTabOrder(self.critial_no_radio, self.scrollArea_3)
        Form.setTabOrder(self.scrollArea_3, self.critial_point_add_btn)
        Form.setTabOrder(self.critial_point_add_btn, self.critial_point_delete_btn)
        Form.setTabOrder(self.critial_point_delete_btn, self.via_name_edit)
        Form.setTabOrder(self.via_name_edit, self.via_add_btn)
        Form.setTabOrder(self.via_add_btn, self.via_remove_btn)
        Form.setTabOrder(self.via_remove_btn, self.via_up_btn)
        Form.setTabOrder(self.via_up_btn, self.via_down_btn)
        Form.setTabOrder(self.via_down_btn, self.received_route_number)
        Form.setTabOrder(self.received_route_number, self.modify_route_radio_yes)
        Form.setTabOrder(self.modify_route_radio_yes, self.modify_route_radio_no)
        Form.setTabOrder(self.modify_route_radio_no, self.reason_modify_route_combo)
        Form.setTabOrder(self.reason_modify_route_combo, self.scrollArea_4)
        Form.setTabOrder(self.scrollArea_4, self.maximum_draft_edit)
        Form.setTabOrder(self.maximum_draft_edit, self.minimum_ukc_edit)
        Form.setTabOrder(self.minimum_ukc_edit, self.load_condition_combo)
        Form.setTabOrder(self.load_condition_combo, self.displacement_edit)
        Form.setTabOrder(self.displacement_edit, self.cargo_carried)
        Form.setTabOrder(self.cargo_carried, self.average_me_rmp_edit)
        Form.setTabOrder(self.average_me_rmp_edit, self.total_distance_edit)
        Form.setTabOrder(self.total_distance_edit, self.distance_me_revolution_edit)
        Form.setTabOrder(self.distance_me_revolution_edit, self.total_streaming_time_edit)
        Form.setTabOrder(self.total_streaming_time_edit, self.log_distance_edit)
        Form.setTabOrder(self.log_distance_edit, self.average_speed_edit)
        Form.setTabOrder(self.average_speed_edit, self.average_slip_edit)
        Form.setTabOrder(self.average_slip_edit, self.overall_condition_combo)
        Form.setTabOrder(self.overall_condition_combo, self.attach_ecdis_route_file_edit)
        Form.setTabOrder(self.attach_ecdis_route_file_edit, self.attach_ecdis_browse_btn)
        Form.setTabOrder(self.attach_ecdis_browse_btn, self.attach_wp_plan_edit)
        Form.setTabOrder(self.attach_wp_plan_edit, self.attach_wp_plan_browse_btn)
        Form.setTabOrder(self.attach_wp_plan_browse_btn, self.reload_btn)
        Form.setTabOrder(self.reload_btn, self.submit_btn)
        Form.setTabOrder(self.submit_btn, self.tabWidget)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Revert Route", None))
        self.voyageDetailGroupBox.setTitle(_translate("Form", "Voyage Detail", None))
        self.groupBox_2.setTitle(_translate("Form", "Departure", None))
        self.label_10.setText(_translate("Form", "Departure Country", None))
        self.label_11.setText(_translate("Form", "Departure Port", None))
        self.label_6.setText(_translate("Form", "Departure Date", None))
        self.depart_date_edit.setDisplayFormat(_translate("Form", "yyyy/MM/dd", None))
        self.label_7.setText(_translate("Form", "Departure Time", None))
        self.label_12.setText(_translate("Form", "UNLO Code", None))
        self.label_13.setText(_translate("Form", "Terminal", None))
        self.groupBox_7.setTitle(_translate("Form", "Arrival", None))
        self.label_8.setText(_translate("Form", "Arrival Date  ", None))
        self.arrival_date_edit.setDisplayFormat(_translate("Form", "yyyy/MM/dd", None))
        self.label_9.setText(_translate("Form", "Arrival Time", None))
        self.label_16.setText(_translate("Form", "UNLO Code", None))
        self.label_17.setText(_translate("Form", "Terminal", None))
        self.label_14.setText(_translate("Form", "Arrival Country  ", None))
        self.label_15.setText(_translate("Form", "Arrival Port ", None))
        self.label_19.setText(_translate("Form", "Use DW route when passing channel or TSS if appilicable?", None))
        self.use_dw_route_yes_radio.setText(_translate("Form", "Yes", None))
        self.use_dw_route_no_radio.setText(_translate("Form", "No", None))
        self.label_20.setText(_translate("Form", "Is there any critial point that request to pay special attention to?", None))
        self.critial_yes_radio.setText(_translate("Form", "Yes", None))
        self.critial_no_radio.setText(_translate("Form", "No", None))
        self.groupBox_4.setTitle(_translate("Form", "Critial Point", None))
        self.critial_point_add_btn.setText(_translate("Form", "Add", None))
        self.critial_point_delete_btn.setText(_translate("Form", "Delete", None))
        item = self.critial_point_table_widget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.critial_point_table_widget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.critial_point_table_widget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.critial_point_table_widget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4", None))
        item = self.critial_point_table_widget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5", None))
        item = self.critial_point_table_widget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6", None))
        item = self.critial_point_table_widget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7", None))
        item = self.critial_point_table_widget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8", None))
        item = self.critial_point_table_widget.verticalHeaderItem(8)
        item.setText(_translate("Form", "9", None))
        item = self.critial_point_table_widget.verticalHeaderItem(9)
        item.setText(_translate("Form", "10", None))
        item = self.critial_point_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Latitude", None))
        item = self.critial_point_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Longtitude", None))
        item = self.critial_point_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Included?", None))
        self.label_22.setText(_translate("Form", " If it is necessery to waitting for high tide or reduce speed to passing critial point,  please toggle the checkbox for included item", None))
        self.label.setText(_translate("Form", "Ship Name", None))
        self.label_2.setText(_translate("Form", "Call Sign", None))
        self.label_4.setText(_translate("Form", "Captain Name", None))
        self.label_5.setText(_translate("Form", "Date", None))
        self.label_3.setText(_translate("Form", "Voyage Number", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "General", None))
        self.groupBox_3.setTitle(_translate("Form", "Paper Chart", None))
        self.groupBox_5.setTitle(_translate("Form", "Via", None))
        self.via_add_btn.setText(_translate("Form", "Add", None))
        self.via_remove_btn.setText(_translate("Form", "Remove", None))
        self.via_up_btn.setText(_translate("Form", "Up", None))
        self.via_down_btn.setText(_translate("Form", "Down", None))
        self.label_23.setText(_translate("Form", "Route number received from the cloud", None))
        self.label_18.setText(_translate("Form", "Route Type", None))
        self.route_type_combo.setItemText(0, _translate("Form", "Anti Piracy Route", None))
        self.route_type_combo.setItemText(1, _translate("Form", "Economy Route", None))
        self.route_type_combo.setItemText(2, _translate("Form", "Low Traffic Route", None))
        self.route_type_combo.setItemText(3, _translate("Form", "Deep Water Route", None))
        self.route_type_combo.setItemText(4, _translate("Form", "Costal Navigation Route", None))
        self.route_type_combo.setItemText(5, _translate("Form", "Weather Route", None))
        self.route_type_combo.setItemText(6, _translate("Form", "Recommend Route", None))
        self.label_37.setText(_translate("Form", "Did you modify any part of the route before using it", None))
        self.modify_route_radio_yes.setText(_translate("Form", "Yes", None))
        self.modify_route_radio_no.setText(_translate("Form", "No", None))
        self.label_38.setText(_translate("Form", "Reasons to modify the route", None))
        self.reason_modify_route_combo.setItemText(0, _translate("Form", "To save distance", None))
        self.reason_modify_route_combo.setItemText(1, _translate("Form", "To avoid navigation hazard(e.g wreck, obstructions)", None))
        self.reason_modify_route_combo.setItemText(2, _translate("Form", "To avoid heavy traffic area", None))
        self.reason_modify_route_combo.setItemText(3, _translate("Form", "To avoid heavy weather/rough sea", None))
        self.reason_modify_route_combo.setItemText(4, _translate("Form", "To follow the current", None))
        self.reason_modify_route_combo.setItemText(5, _translate("Form", "To replenish", None))
        self.reason_modify_route_combo.setItemText(6, _translate("Form", "Technical reasons", None))
        self.reason_modify_route_combo.setItemText(7, _translate("Form", "Operational reasons", None))
        self.reason_modify_route_combo.setItemText(8, _translate("Form", "Company/Charterer instruction", None))
        self.reason_modify_route_combo.setItemText(9, _translate("Form", "Others reasons", None))
        self.label_39.setText(_translate("Form", "Paper chart to be used （in secquence） if your ship maintain paper chart onboard", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(0)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(1)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(2)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(3)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(4)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(5)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(6)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(7)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(8)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.verticalHeaderItem(9)
        item.setText(_translate("Form", "新建行", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "新建列", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "新建列", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "新建列", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "新建列", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "新建列", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "新建列", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "新建列", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "新建列", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "新建列", None))
        item = self.paper_chart_table_widget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "新建列", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Paper Chart", None))
        self.voyageDataGroupBox.setTitle(_translate("Form", "Voyage Data", None))
        self.groupBox_6.setTitle(_translate("Form", "Calculate", None))
        self.label_28.setText(_translate("Form", "Maximum Draft", None))
        self.label_29.setText(_translate("Form", "Minimum UKC", None))
        self.label_30.setText(_translate("Form", "Load Condition", None))
        self.load_condition_combo.setItemText(0, _translate("Form", "Ballast", None))
        self.load_condition_combo.setItemText(1, _translate("Form", "Loaded", None))
        self.label_31.setText(_translate("Form", "Displacement ", None))
        self.label_27.setText(_translate("Form", "Cargo Carried (Tone)  ", None))
        self.label_34.setText(_translate("Form", "Average M/E RMP", None))
        self.label_24.setText(_translate("Form", "Total Distance Over Ground", None))
        self.label_33.setText(_translate("Form", "Distance By M/E Revolution", None))
        self.label_25.setText(_translate("Form", "Total Streaming Time", None))
        self.label_26.setText(_translate("Form", "Log Distance", None))
        self.label_40.setText(_translate("Form", "Average Speed", None))
        self.label_32.setText(_translate("Form", "Average Slip", None))
        item = self.bunker_consume_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "Total Bunker Consumption", None))
        item = self.bunker_consume_table.verticalHeaderItem(1)
        item.setText(_translate("Form", "Average Bunker Consumption per NM", None))
        item = self.bunker_consume_table.verticalHeaderItem(2)
        item.setText(_translate("Form", "Voyage Performance Efficiency", None))
        item = self.bunker_consume_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "IFO", None))
        item = self.bunker_consume_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "MDO", None))
        item = self.bunker_consume_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "LSFO", None))
        item = self.bunker_consume_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "LSMDO", None))
        __sortingEnabled = self.bunker_consume_table.isSortingEnabled()
        self.bunker_consume_table.setSortingEnabled(False)
        self.bunker_consume_table.setSortingEnabled(__sortingEnabled)
        self.label_41.setText(_translate("Form", "Overall weather/sea condition throughout the voyage", None))
        self.overall_condition_combo.setItemText(0, _translate("Form", "Good weather throught the voyage", None))
        self.overall_condition_combo.setItemText(1, _translate("Form", "Favorable weather/sea throught the voyage", None))
        self.overall_condition_combo.setItemText(2, _translate("Form", "Adverse weather/sea throught the voyage", None))
        self.overall_condition_combo.setItemText(3, _translate("Form", "Heavy weather/Rough sea throughout the voyage", None))
        self.label_35.setText(_translate("Form", "Attach ECDIS Route File", None))
        self.attach_ecdis_browse_btn.setText(_translate("Form", "Browse", None))
        self.label_36.setText(_translate("Form", "Attach E-marine WP Plan", None))
        self.attach_wp_plan_browse_btn.setText(_translate("Form", "Browse", None))
        self.label_21.setText(_translate("Form", "Remark", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Voyage Data", None))
        self.reload_btn.setText(_translate("Form", "Reload", None))
        self.submit_btn.setText(_translate("Form", "Submit", None))

