#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Generated Mon Feb 29 00:58:11 2016 by generateDS.py version 2.18a.
#
# Command line options:
#   ('-f', '')
#   ('-q', '')
#   ('--use-getter-setter', 'none')
#   ('-o', 'D:\\GitRepo\\emgui\\src\\dao\\quarter.py')
#
# Command line arguments:
#   D:\GitRepo\emgui\src\schema\quarter.xsd
#
# Command line:
#   C:\Python27\Scripts\generateDS.py -f -q --use-getter-setter="none" -o "D:\GitRepo\emgui\src\dao\quarter.py" D:\GitRepo\emgui\src\schema\quarter.xsd
#
# Current working directory (os.getcwd()):
#   Scripts
#

import sys
import re as re_
import base64
import datetime as datetime_
import warnings as warnings_
from lxml import etree as etree_


Validate_simpletypes_ = True


def parsexml_(infile, parser=None, **kwargs):
    if parser is None:
        # Use the lxml ElementTree compatible parser so that, e.g.,
        #   we ignore comments.
        parser = etree_.ETCompatXMLParser()
    doc = etree_.parse(infile, parser=parser, **kwargs)
    return doc

#
# User methods
#
# Calls to the methods in these classes are generated by generateDS.py.
# You can replace these methods by re-implementing the following class
#   in a module named generatedssuper.py.

try:
    from generatedssuper import GeneratedsSuper
except ImportError as exp:

    class GeneratedsSuper(object):
        tzoff_pattern = re_.compile(r'(\+|-)((0\d|1[0-3]):[0-5]\d|14:00)$')
        class _FixedOffsetTZ(datetime_.tzinfo):
            def __init__(self, offset, name):
                self.__offset = datetime_.timedelta(minutes=offset)
                self.__name = name
            def utcoffset(self, dt):
                return self.__offset
            def tzname(self, dt):
                return self.__name
            def dst(self, dt):
                return None
        def gds_format_string(self, input_data, input_name=''):
            return input_data
        def gds_validate_string(self, input_data, node=None, input_name=''):
            if not input_data:
                return ''
            else:
                return input_data
        def gds_format_base64(self, input_data, input_name=''):
            return base64.b64encode(input_data)
        def gds_validate_base64(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_integer(self, input_data, input_name=''):
            return '%d' % input_data
        def gds_validate_integer(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_integer_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_integer_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    int(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of integers')
            return values
        def gds_format_float(self, input_data, input_name=''):
            return ('%.15f' % input_data).rstrip('0')
        def gds_validate_float(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_float_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_float_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of floats')
            return values
        def gds_format_double(self, input_data, input_name=''):
            return '%e' % input_data
        def gds_validate_double(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_double_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_double_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of doubles')
            return values
        def gds_format_boolean(self, input_data, input_name=''):
            return ('%s' % input_data).lower()
        def gds_validate_boolean(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_boolean_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_boolean_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                if value not in ('true', '1', 'false', '0', ):
                    raise_parse_error(
                        node,
                        'Requires sequence of booleans '
                        '("true", "1", "false", "0")')
            return values
        def gds_validate_datetime(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_datetime(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d.%s' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue
        @classmethod
        def gds_parse_datetime(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            time_parts = input_data.split('.')
            if len(time_parts) > 1:
                micro_seconds = int(float('0.' + time_parts[1]) * 1000000)
                input_data = '%s.%s' % (time_parts[0], micro_seconds, )
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt
        def gds_validate_date(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_date(self, input_data, input_name=''):
            _svalue = '%04d-%02d-%02d' % (
                input_data.year,
                input_data.month,
                input_data.day,
            )
            try:
                if input_data.tzinfo is not None:
                    tzoff = input_data.tzinfo.utcoffset(input_data)
                    if tzoff is not None:
                        total_seconds = tzoff.seconds + (86400 * tzoff.days)
                        if total_seconds == 0:
                            _svalue += 'Z'
                        else:
                            if total_seconds < 0:
                                _svalue += '-'
                                total_seconds *= -1
                            else:
                                _svalue += '+'
                            hours = total_seconds // 3600
                            minutes = (total_seconds - (hours * 3600)) // 60
                            _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            except AttributeError:
                pass
            return _svalue
        @classmethod
        def gds_parse_date(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            dt = datetime_.datetime.strptime(input_data, '%Y-%m-%d')
            dt = dt.replace(tzinfo=tz)
            return dt.date()
        def gds_validate_time(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_time(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%02d:%02d:%02d' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%02d:%02d:%02d.%s' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue
        def gds_validate_simple_patterns(self, patterns, target):
            # pat is a list of lists of strings/patterns.  We should:
            # - AND the outer elements
            # - OR the inner elements
            found1 = True
            for patterns1 in patterns:
                found2 = False
                for patterns2 in patterns1:
                    if re_.search(patterns2, target) is not None:
                        found2 = True
                        break
                if not found2:
                    found1 = False
                    break
            return found1
        @classmethod
        def gds_parse_time(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            if len(input_data.split('.')) > 1:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt.time()
        def gds_str_lower(self, instring):
            return instring.lower()
        def get_path_(self, node):
            path_list = []
            self.get_path_list_(node, path_list)
            path_list.reverse()
            path = '/'.join(path_list)
            return path
        Tag_strip_pattern_ = re_.compile(r'\{.*\}')
        def get_path_list_(self, node, path_list):
            if node is None:
                return
            tag = GeneratedsSuper.Tag_strip_pattern_.sub('', node.tag)
            if tag:
                path_list.append(tag)
            self.get_path_list_(node.getparent(), path_list)
        def get_class_obj_(self, node, default_class=None):
            class_obj1 = default_class
            if 'xsi' in node.nsmap:
                classname = node.get('{%s}type' % node.nsmap['xsi'])
                if classname is not None:
                    names = classname.split(':')
                    if len(names) == 2:
                        classname = names[1]
                    class_obj2 = globals().get(classname)
                    if class_obj2 is not None:
                        class_obj1 = class_obj2
            return class_obj1
        def gds_build_any(self, node, type_name=None):
            return None
        @classmethod
        def gds_reverse_node_mapping(cls, mapping):
            return dict(((v, k) for k, v in mapping.iteritems()))


#
# If you have installed IPython you can uncomment and use the following.
# IPython is available from http://ipython.scipy.org/.
#

## from IPython.Shell import IPShellEmbed
## args = ''
## ipshell = IPShellEmbed(args,
##     banner = 'Dropping into IPython',
##     exit_msg = 'Leaving Interpreter, back to program.')

# Then use the following line where and when you want to drop into the
# IPython shell:
#    ipshell('<some message> -- Entering ipshell.\nHit Ctrl-D to exit')

#
# Globals
#

ExternalEncoding = 'ascii'
Tag_pattern_ = re_.compile(r'({.*})?(.*)')
String_cleanup_pat_ = re_.compile(r"[\n\r\s]+")
Namespace_extract_pat_ = re_.compile(r'{(.*)}(.*)')
CDATA_pattern_ = re_.compile(r"<!\[CDATA\[.*?\]\]>", re_.DOTALL)

#
# Support/utility functions.
#


def showIndent(outfile, level, pretty_print=True):
    if pretty_print:
        for idx in range(level):
            outfile.write('    ')


def quote_xml(inStr):
    "Escape markup chars, but do not modify CDATA sections."
    if not inStr:
        return ''
    s1 = (isinstance(inStr, basestring) and inStr or
          '%s' % inStr)
    s2 = ''
    pos = 0
    matchobjects = CDATA_pattern_.finditer(s1)
    for mo in matchobjects:
        s3 = s1[pos:mo.start()]
        s2 += quote_xml_aux(s3)
        s2 += s1[mo.start():mo.end()]
        pos = mo.end()
    s3 = s1[pos:]
    s2 += quote_xml_aux(s3)
    return s2


def quote_xml_aux(inStr):
    s1 = inStr.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    return s1


def quote_attrib(inStr):
    s1 = (isinstance(inStr, basestring) and inStr or
          '%s' % inStr)
    s1 = s1.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    if '"' in s1:
        if "'" in s1:
            s1 = '"%s"' % s1.replace('"', "&quot;")
        else:
            s1 = "'%s'" % s1
    else:
        s1 = '"%s"' % s1
    return s1


def quote_python(inStr):
    s1 = inStr
    if s1.find("'") == -1:
        if s1.find('\n') == -1:
            return "'%s'" % s1
        else:
            return "'''%s'''" % s1
    else:
        if s1.find('"') != -1:
            s1 = s1.replace('"', '\\"')
        if s1.find('\n') == -1:
            return '"%s"' % s1
        else:
            return '"""%s"""' % s1


def get_all_text_(node):
    if node.text is not None:
        text = node.text
    else:
        text = ''
    for child in node:
        if child.tail is not None:
            text += child.tail
    return text


def find_attr_value_(attr_name, node):
    attrs = node.attrib
    attr_parts = attr_name.split(':')
    value = None
    if len(attr_parts) == 1:
        value = attrs.get(attr_name)
    elif len(attr_parts) == 2:
        prefix, name = attr_parts
        namespace = node.nsmap.get(prefix)
        if namespace is not None:
            value = attrs.get('{%s}%s' % (namespace, name, ))
    return value


class GDSParseError(Exception):
    pass


def raise_parse_error(node, msg):
    msg = '%s (element %s/line %d)' % (msg, node.tag, node.sourceline, )
    raise GDSParseError(msg)


class MixedContainer:
    # Constants for category:
    CategoryNone = 0
    CategoryText = 1
    CategorySimple = 2
    CategoryComplex = 3
    # Constants for content_type:
    TypeNone = 0
    TypeText = 1
    TypeString = 2
    TypeInteger = 3
    TypeFloat = 4
    TypeDecimal = 5
    TypeDouble = 6
    TypeBoolean = 7
    TypeBase64 = 8
    def __init__(self, category, content_type, name, value):
        self.category = category
        self.content_type = content_type
        self.name = name
        self.value = value
    def getCategory(self):
        return self.category
    def getContenttype(self, content_type):
        return self.content_type
    def getValue(self):
        return self.value
    def getName(self):
        return self.name
    def export(self, outfile, level, name, namespace, pretty_print=True):
        if self.category == MixedContainer.CategoryText:
            # Prevent exporting empty content as empty lines.
            if self.value.strip():
                outfile.write(self.value)
        elif self.category == MixedContainer.CategorySimple:
            self.exportSimple(outfile, level, name)
        else:    # category == MixedContainer.CategoryComplex
            self.value.export(outfile, level, namespace, name, pretty_print)
    def exportSimple(self, outfile, level, name):
        if self.content_type == MixedContainer.TypeString:
            outfile.write('<%s>%s</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeInteger or \
                self.content_type == MixedContainer.TypeBoolean:
            outfile.write('<%s>%d</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeFloat or \
                self.content_type == MixedContainer.TypeDecimal:
            outfile.write('<%s>%f</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeDouble:
            outfile.write('<%s>%g</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeBase64:
            outfile.write('<%s>%s</%s>' % (
                self.name, base64.b64encode(self.value), self.name))
    def to_etree(self, element):
        if self.category == MixedContainer.CategoryText:
            # Prevent exporting empty content as empty lines.
            if self.value.strip():
                if len(element) > 0:
                    if element[-1].tail is None:
                        element[-1].tail = self.value
                    else:
                        element[-1].tail += self.value
                else:
                    if element.text is None:
                        element.text = self.value
                    else:
                        element.text += self.value
        elif self.category == MixedContainer.CategorySimple:
            subelement = etree_.SubElement(element, '%s' % self.name)
            subelement.text = self.to_etree_simple()
        else:    # category == MixedContainer.CategoryComplex
            self.value.to_etree(element)
    def to_etree_simple(self):
        if self.content_type == MixedContainer.TypeString:
            text = self.value
        elif (self.content_type == MixedContainer.TypeInteger or
                self.content_type == MixedContainer.TypeBoolean):
            text = '%d' % self.value
        elif (self.content_type == MixedContainer.TypeFloat or
                self.content_type == MixedContainer.TypeDecimal):
            text = '%f' % self.value
        elif self.content_type == MixedContainer.TypeDouble:
            text = '%g' % self.value
        elif self.content_type == MixedContainer.TypeBase64:
            text = '%s' % base64.b64encode(self.value)
        return text
    def exportLiteral(self, outfile, level, name):
        if self.category == MixedContainer.CategoryText:
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s", "%s"),\n' % (
                    self.category, self.content_type, self.name, self.value))
        elif self.category == MixedContainer.CategorySimple:
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s", "%s"),\n' % (
                    self.category, self.content_type, self.name, self.value))
        else:    # category == MixedContainer.CategoryComplex
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s",\n' % (
                    self.category, self.content_type, self.name,))
            self.value.exportLiteral(outfile, level + 1)
            showIndent(outfile, level)
            outfile.write(')\n')


class MemberSpec_(object):
    def __init__(self, name='', data_type='', container=0):
        self.name = name
        self.data_type = data_type
        self.container = container
    def set_name(self, name): self.name = name
    def get_name(self): return self.name
    def set_data_type(self, data_type): self.data_type = data_type
    def get_data_type_chain(self): return self.data_type
    def get_data_type(self):
        if isinstance(self.data_type, list):
            if len(self.data_type) > 0:
                return self.data_type[-1]
            else:
                return 'xs:string'
        else:
            return self.data_type
    def set_container(self, container): self.container = container
    def get_container(self): return self.container


def _cast(typ, value):
    if typ is None or value is None:
        return value
    return typ(value)

#
# Data representation classes.
#


class Property(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, ship_name=None, call_sign=None, captain_name=None, date=None, year=None, quarter=None, cargo_info=None, total_fuel_info=None):
        self.original_tagname_ = None
        self.ship_name = ship_name
        self.call_sign = call_sign
        self.captain_name = captain_name
        self.date = date
        self.year = year
        self.quarter = quarter
        self.cargo_info = cargo_info
        self.total_fuel_info = total_fuel_info
    def factory(*args_, **kwargs_):
        if Property.subclass:
            return Property.subclass(*args_, **kwargs_)
        else:
            return Property(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.ship_name is not None or
            self.call_sign is not None or
            self.captain_name is not None or
            self.date is not None or
            self.year is not None or
            self.quarter is not None or
            self.cargo_info is not None or
            self.total_fuel_info is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='Property', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='Property')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='Property', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='Property'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='Property', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.ship_name is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sship_name>%s</%sship_name>%s' % (namespace_, self.gds_format_string(quote_xml(self.ship_name).encode(ExternalEncoding), input_name='ship_name'), namespace_, eol_))
        if self.call_sign is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%scall_sign>%s</%scall_sign>%s' % (namespace_, self.gds_format_string(quote_xml(self.call_sign).encode(ExternalEncoding), input_name='call_sign'), namespace_, eol_))
        if self.captain_name is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%scaptain_name>%s</%scaptain_name>%s' % (namespace_, self.gds_format_string(quote_xml(self.captain_name).encode(ExternalEncoding), input_name='captain_name'), namespace_, eol_))
        if self.date is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdate>%s</%sdate>%s' % (namespace_, self.gds_format_string(quote_xml(self.date).encode(ExternalEncoding), input_name='date'), namespace_, eol_))
        if self.year is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%syear>%s</%syear>%s' % (namespace_, self.gds_format_string(quote_xml(self.year).encode(ExternalEncoding), input_name='year'), namespace_, eol_))
        if self.quarter is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%squarter>%s</%squarter>%s' % (namespace_, self.gds_format_string(quote_xml(self.quarter).encode(ExternalEncoding), input_name='quarter'), namespace_, eol_))
        if self.cargo_info is not None:
            self.cargo_info.export(outfile, level, namespace_, name_='cargo_info', pretty_print=pretty_print)
        if self.total_fuel_info is not None:
            self.total_fuel_info.export(outfile, level, namespace_, name_='total_fuel_info', pretty_print=pretty_print)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'ship_name':
            ship_name_ = child_.text
            ship_name_ = self.gds_validate_string(ship_name_, node, 'ship_name')
            self.ship_name = ship_name_
        elif nodeName_ == 'call_sign':
            call_sign_ = child_.text
            call_sign_ = self.gds_validate_string(call_sign_, node, 'call_sign')
            self.call_sign = call_sign_
        elif nodeName_ == 'captain_name':
            captain_name_ = child_.text
            captain_name_ = self.gds_validate_string(captain_name_, node, 'captain_name')
            self.captain_name = captain_name_
        elif nodeName_ == 'date':
            date_ = child_.text
            date_ = self.gds_validate_string(date_, node, 'date')
            self.date = date_
        elif nodeName_ == 'year':
            year_ = child_.text
            year_ = self.gds_validate_string(year_, node, 'year')
            self.year = year_
        elif nodeName_ == 'quarter':
            quarter_ = child_.text
            quarter_ = self.gds_validate_string(quarter_, node, 'quarter')
            self.quarter = quarter_
        elif nodeName_ == 'cargo_info':
            obj_ = cargo_info.factory()
            obj_.build(child_)
            self.cargo_info = obj_
            obj_.original_tagname_ = 'cargo_info'
        elif nodeName_ == 'total_fuel_info':
            obj_ = total_fuel_info.factory()
            obj_.build(child_)
            self.total_fuel_info = obj_
            obj_.original_tagname_ = 'total_fuel_info'
# end class Property


class cargo_info(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, cargo_item=None):
        self.original_tagname_ = None
        if cargo_item is None:
            self.cargo_item = []
        else:
            self.cargo_item = cargo_item
    def factory(*args_, **kwargs_):
        if cargo_info.subclass:
            return cargo_info.subclass(*args_, **kwargs_)
        else:
            return cargo_info(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.cargo_item
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='cargo_info', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='cargo_info')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='cargo_info', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='cargo_info'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='cargo_info', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        for cargo_item_ in self.cargo_item:
            cargo_item_.export(outfile, level, namespace_, name_='cargo_item', pretty_print=pretty_print)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'cargo_item':
            obj_ = cargo_item.factory()
            obj_.build(child_)
            self.cargo_item.append(obj_)
            obj_.original_tagname_ = 'cargo_item'
# end class cargo_info


class quarterly_report(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, Property=None):
        self.original_tagname_ = None
        self.Property = Property
    def factory(*args_, **kwargs_):
        if quarterly_report.subclass:
            return quarterly_report.subclass(*args_, **kwargs_)
        else:
            return quarterly_report(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.Property is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='quarterly_report', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='quarterly_report')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='quarterly_report', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='quarterly_report'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='quarterly_report', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.Property is not None:
            self.Property.export(outfile, level, namespace_, name_='Property', pretty_print=pretty_print)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'Property':
            obj_ = Property.factory()
            obj_.build(child_)
            self.Property = obj_
            obj_.original_tagname_ = 'Property'
# end class quarterly_report


class total_fuel_info(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, total_fuel_consumption=None, total_fuel_supplied=None, total_fuel_rob=None):
        self.original_tagname_ = None
        self.total_fuel_consumption = total_fuel_consumption
        self.total_fuel_supplied = total_fuel_supplied
        self.total_fuel_rob = total_fuel_rob
    def factory(*args_, **kwargs_):
        if total_fuel_info.subclass:
            return total_fuel_info.subclass(*args_, **kwargs_)
        else:
            return total_fuel_info(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.total_fuel_consumption is not None or
            self.total_fuel_supplied is not None or
            self.total_fuel_rob is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='total_fuel_info', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='total_fuel_info')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='total_fuel_info', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='total_fuel_info'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='total_fuel_info', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.total_fuel_consumption is not None:
            self.total_fuel_consumption.export(outfile, level, namespace_, name_='total_fuel_consumption', pretty_print=pretty_print)
        if self.total_fuel_supplied is not None:
            self.total_fuel_supplied.export(outfile, level, namespace_, name_='total_fuel_supplied', pretty_print=pretty_print)
        if self.total_fuel_rob is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%stotal_fuel_rob>%s</%stotal_fuel_rob>%s' % (namespace_, self.gds_format_string(quote_xml(self.total_fuel_rob).encode(ExternalEncoding), input_name='total_fuel_rob'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'total_fuel_consumption':
            obj_ = total_fuel_consumption.factory()
            obj_.build(child_)
            self.total_fuel_consumption = obj_
            obj_.original_tagname_ = 'total_fuel_consumption'
        elif nodeName_ == 'total_fuel_supplied':
            obj_ = total_fuel_supplied.factory()
            obj_.build(child_)
            self.total_fuel_supplied = obj_
            obj_.original_tagname_ = 'total_fuel_supplied'
        elif nodeName_ == 'total_fuel_rob':
            total_fuel_rob_ = child_.text
            total_fuel_rob_ = self.gds_validate_string(total_fuel_rob_, node, 'total_fuel_rob')
            self.total_fuel_rob = total_fuel_rob_
# end class total_fuel_info


class cargo_item(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, cargo_id=None, cargo_weight=None, distance_travelled=None, distance_me_revoluation=None, me_average_rpm=None, average_slip=None, tfc_ifo=None, tfc_lsfo=None, tfc_mdo=None, tfc_lsmdo=None, perf_effciency=None):
        self.original_tagname_ = None
        self.cargo_id = cargo_id
        self.cargo_weight = cargo_weight
        self.distance_travelled = distance_travelled
        self.distance_me_revoluation = distance_me_revoluation
        self.me_average_rpm = me_average_rpm
        self.average_slip = average_slip
        self.tfc_ifo = tfc_ifo
        self.tfc_lsfo = tfc_lsfo
        self.tfc_mdo = tfc_mdo
        self.tfc_lsmdo = tfc_lsmdo
        self.perf_effciency = perf_effciency
    def factory(*args_, **kwargs_):
        if cargo_item.subclass:
            return cargo_item.subclass(*args_, **kwargs_)
        else:
            return cargo_item(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.cargo_id is not None or
            self.cargo_weight is not None or
            self.distance_travelled is not None or
            self.distance_me_revoluation is not None or
            self.me_average_rpm is not None or
            self.average_slip is not None or
            self.tfc_ifo is not None or
            self.tfc_lsfo is not None or
            self.tfc_mdo is not None or
            self.tfc_lsmdo is not None or
            self.perf_effciency is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='cargo_item', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='cargo_item')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='cargo_item', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='cargo_item'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='cargo_item', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.cargo_id is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%scargo_id>%s</%scargo_id>%s' % (namespace_, self.gds_format_string(quote_xml(self.cargo_id).encode(ExternalEncoding), input_name='cargo_id'), namespace_, eol_))
        if self.cargo_weight is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%scargo_weight>%s</%scargo_weight>%s' % (namespace_, self.gds_format_string(quote_xml(self.cargo_weight).encode(ExternalEncoding), input_name='cargo_weight'), namespace_, eol_))
        if self.distance_travelled is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdistance_travelled>%s</%sdistance_travelled>%s' % (namespace_, self.gds_format_string(quote_xml(self.distance_travelled).encode(ExternalEncoding), input_name='distance_travelled'), namespace_, eol_))
        if self.distance_me_revoluation is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdistance_me_revoluation>%s</%sdistance_me_revoluation>%s' % (namespace_, self.gds_format_string(quote_xml(self.distance_me_revoluation).encode(ExternalEncoding), input_name='distance_me_revoluation'), namespace_, eol_))
        if self.me_average_rpm is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sme_average_rpm>%s</%sme_average_rpm>%s' % (namespace_, self.gds_format_string(quote_xml(self.me_average_rpm).encode(ExternalEncoding), input_name='me_average_rpm'), namespace_, eol_))
        if self.average_slip is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%saverage_slip>%s</%saverage_slip>%s' % (namespace_, self.gds_format_string(quote_xml(self.average_slip).encode(ExternalEncoding), input_name='average_slip'), namespace_, eol_))
        if self.tfc_ifo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%stfc_ifo>%s</%stfc_ifo>%s' % (namespace_, self.gds_format_string(quote_xml(self.tfc_ifo).encode(ExternalEncoding), input_name='tfc_ifo'), namespace_, eol_))
        if self.tfc_lsfo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%stfc_lsfo>%s</%stfc_lsfo>%s' % (namespace_, self.gds_format_string(quote_xml(self.tfc_lsfo).encode(ExternalEncoding), input_name='tfc_lsfo'), namespace_, eol_))
        if self.tfc_mdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%stfc_mdo>%s</%stfc_mdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.tfc_mdo).encode(ExternalEncoding), input_name='tfc_mdo'), namespace_, eol_))
        if self.tfc_lsmdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%stfc_lsmdo>%s</%stfc_lsmdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.tfc_lsmdo).encode(ExternalEncoding), input_name='tfc_lsmdo'), namespace_, eol_))
        if self.perf_effciency is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sperf_effciency>%s</%sperf_effciency>%s' % (namespace_, self.gds_format_string(quote_xml(self.perf_effciency).encode(ExternalEncoding), input_name='perf_effciency'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'cargo_id':
            cargo_id_ = child_.text
            cargo_id_ = self.gds_validate_string(cargo_id_, node, 'cargo_id')
            self.cargo_id = cargo_id_
        elif nodeName_ == 'cargo_weight':
            cargo_weight_ = child_.text
            cargo_weight_ = self.gds_validate_string(cargo_weight_, node, 'cargo_weight')
            self.cargo_weight = cargo_weight_
        elif nodeName_ == 'distance_travelled':
            distance_travelled_ = child_.text
            distance_travelled_ = self.gds_validate_string(distance_travelled_, node, 'distance_travelled')
            self.distance_travelled = distance_travelled_
        elif nodeName_ == 'distance_me_revoluation':
            distance_me_revoluation_ = child_.text
            distance_me_revoluation_ = self.gds_validate_string(distance_me_revoluation_, node, 'distance_me_revoluation')
            self.distance_me_revoluation = distance_me_revoluation_
        elif nodeName_ == 'me_average_rpm':
            me_average_rpm_ = child_.text
            me_average_rpm_ = self.gds_validate_string(me_average_rpm_, node, 'me_average_rpm')
            self.me_average_rpm = me_average_rpm_
        elif nodeName_ == 'average_slip':
            average_slip_ = child_.text
            average_slip_ = self.gds_validate_string(average_slip_, node, 'average_slip')
            self.average_slip = average_slip_
        elif nodeName_ == 'tfc_ifo':
            tfc_ifo_ = child_.text
            tfc_ifo_ = self.gds_validate_string(tfc_ifo_, node, 'tfc_ifo')
            self.tfc_ifo = tfc_ifo_
        elif nodeName_ == 'tfc_lsfo':
            tfc_lsfo_ = child_.text
            tfc_lsfo_ = self.gds_validate_string(tfc_lsfo_, node, 'tfc_lsfo')
            self.tfc_lsfo = tfc_lsfo_
        elif nodeName_ == 'tfc_mdo':
            tfc_mdo_ = child_.text
            tfc_mdo_ = self.gds_validate_string(tfc_mdo_, node, 'tfc_mdo')
            self.tfc_mdo = tfc_mdo_
        elif nodeName_ == 'tfc_lsmdo':
            tfc_lsmdo_ = child_.text
            tfc_lsmdo_ = self.gds_validate_string(tfc_lsmdo_, node, 'tfc_lsmdo')
            self.tfc_lsmdo = tfc_lsmdo_
        elif nodeName_ == 'perf_effciency':
            perf_effciency_ = child_.text
            perf_effciency_ = self.gds_validate_string(perf_effciency_, node, 'perf_effciency')
            self.perf_effciency = perf_effciency_
# end class cargo_item


class total_fuel_consumption(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, ifo=None, lsfo=None, mdo=None, lsmdo=None):
        self.original_tagname_ = None
        self.ifo = ifo
        self.lsfo = lsfo
        self.mdo = mdo
        self.lsmdo = lsmdo
    def factory(*args_, **kwargs_):
        if total_fuel_consumption.subclass:
            return total_fuel_consumption.subclass(*args_, **kwargs_)
        else:
            return total_fuel_consumption(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.ifo is not None or
            self.lsfo is not None or
            self.mdo is not None or
            self.lsmdo is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='total_fuel_consumption', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='total_fuel_consumption')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='total_fuel_consumption', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='total_fuel_consumption'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='total_fuel_consumption', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.ifo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sifo>%s</%sifo>%s' % (namespace_, self.gds_format_string(quote_xml(self.ifo).encode(ExternalEncoding), input_name='ifo'), namespace_, eol_))
        if self.lsfo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slsfo>%s</%slsfo>%s' % (namespace_, self.gds_format_string(quote_xml(self.lsfo).encode(ExternalEncoding), input_name='lsfo'), namespace_, eol_))
        if self.mdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smdo>%s</%smdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.mdo).encode(ExternalEncoding), input_name='mdo'), namespace_, eol_))
        if self.lsmdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slsmdo>%s</%slsmdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.lsmdo).encode(ExternalEncoding), input_name='lsmdo'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'ifo':
            ifo_ = child_.text
            ifo_ = self.gds_validate_string(ifo_, node, 'ifo')
            self.ifo = ifo_
        elif nodeName_ == 'lsfo':
            lsfo_ = child_.text
            lsfo_ = self.gds_validate_string(lsfo_, node, 'lsfo')
            self.lsfo = lsfo_
        elif nodeName_ == 'mdo':
            mdo_ = child_.text
            mdo_ = self.gds_validate_string(mdo_, node, 'mdo')
            self.mdo = mdo_
        elif nodeName_ == 'lsmdo':
            lsmdo_ = child_.text
            lsmdo_ = self.gds_validate_string(lsmdo_, node, 'lsmdo')
            self.lsmdo = lsmdo_
# end class total_fuel_consumption


class total_fuel_supplied(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, ifo=None, lsfo=None, mdo=None, lsmdo=None):
        self.original_tagname_ = None
        self.ifo = ifo
        self.lsfo = lsfo
        self.mdo = mdo
        self.lsmdo = lsmdo
    def factory(*args_, **kwargs_):
        if total_fuel_supplied.subclass:
            return total_fuel_supplied.subclass(*args_, **kwargs_)
        else:
            return total_fuel_supplied(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.ifo is not None or
            self.lsfo is not None or
            self.mdo is not None or
            self.lsmdo is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='total_fuel_supplied', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='total_fuel_supplied')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='total_fuel_supplied', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='total_fuel_supplied'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='total_fuel_supplied', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.ifo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sifo>%s</%sifo>%s' % (namespace_, self.gds_format_string(quote_xml(self.ifo).encode(ExternalEncoding), input_name='ifo'), namespace_, eol_))
        if self.lsfo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slsfo>%s</%slsfo>%s' % (namespace_, self.gds_format_string(quote_xml(self.lsfo).encode(ExternalEncoding), input_name='lsfo'), namespace_, eol_))
        if self.mdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smdo>%s</%smdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.mdo).encode(ExternalEncoding), input_name='mdo'), namespace_, eol_))
        if self.lsmdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slsmdo>%s</%slsmdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.lsmdo).encode(ExternalEncoding), input_name='lsmdo'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'ifo':
            ifo_ = child_.text
            ifo_ = self.gds_validate_string(ifo_, node, 'ifo')
            self.ifo = ifo_
        elif nodeName_ == 'lsfo':
            lsfo_ = child_.text
            lsfo_ = self.gds_validate_string(lsfo_, node, 'lsfo')
            self.lsfo = lsfo_
        elif nodeName_ == 'mdo':
            mdo_ = child_.text
            mdo_ = self.gds_validate_string(mdo_, node, 'mdo')
            self.mdo = mdo_
        elif nodeName_ == 'lsmdo':
            lsmdo_ = child_.text
            lsmdo_ = self.gds_validate_string(lsmdo_, node, 'lsmdo')
            self.lsmdo = lsmdo_
# end class total_fuel_supplied


GDSClassesMapping = {
}


USAGE_TEXT = """
Usage: python <Parser>.py [ -s ] <in_xml_file>
"""


def usage():
    print(USAGE_TEXT)
    sys.exit(1)


def get_root_tag(node):
    tag = Tag_pattern_.match(node.tag).groups()[-1]
    rootClass = GDSClassesMapping.get(tag)
    if rootClass is None:
        rootClass = globals().get(tag)
    return tag, rootClass


def parse(inFileName, silence=False):
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'Property'
        rootClass = Property
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    if not silence:
        sys.stdout.write('<?xml version="1.0" ?>\n')
        rootObj.export(
            sys.stdout, 0, name_=rootTag,
            namespacedef_='',
            pretty_print=True)
    return rootObj


def parseEtree(inFileName, silence=False):
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'Property'
        rootClass = Property
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    mapping = {}
    rootElement = rootObj.to_etree(None, name_=rootTag, mapping_=mapping)
    reverse_mapping = rootObj.gds_reverse_node_mapping(mapping)
    if not silence:
        content = etree_.tostring(
            rootElement, pretty_print=True,
            xml_declaration=True, encoding="utf-8")
        sys.stdout.write(content)
        sys.stdout.write('\n')
    return rootObj, rootElement, mapping, reverse_mapping


def parseString(inString, silence=False):
    from StringIO import StringIO
    parser = None
    doc = parsexml_(StringIO(inString), parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'Property'
        rootClass = Property
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    if not silence:
        sys.stdout.write('<?xml version="1.0" ?>\n')
        rootObj.export(
            sys.stdout, 0, name_=rootTag,
            namespacedef_='')
    return rootObj


def parseLiteral(inFileName, silence=False):
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'Property'
        rootClass = Property
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    if not silence:
        sys.stdout.write('#from quarter import *\n\n')
        sys.stdout.write('import quarter as model_\n\n')
        sys.stdout.write('rootObj = model_.rootClass(\n')
        rootObj.exportLiteral(sys.stdout, 0, name_=rootTag)
        sys.stdout.write(')\n')
    return rootObj


def main():
    args = sys.argv[1:]
    if len(args) == 1:
        parse(args[0])
    else:
        usage()


if __name__ == '__main__':
    #import pdb; pdb.set_trace()
    main()


__all__ = [
    "Property",
    "cargo_info",
    "cargo_item",
    "quarterly_report",
    "total_fuel_consumption",
    "total_fuel_info",
    "total_fuel_supplied"
]
