#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Generated Thu Jan 21 17:10:26 2016 by generateDS.py version 2.17a.
#
# Command line options:
#   ('-f', '')
#   ('-q', '')
#   ('--use-getter-setter', 'none')
#   ('-o', 'D:\\GitRepo\\emgui\\src\\dao\\revert.py')
#
# Command line arguments:
#   D:\GitRepo\emgui\src\schema\revert.xsd
#
# Command line:
#   E:\Python27\Scripts\generateDS.py -f -q --use-getter-setter="none" -o "D:\GitRepo\emgui\src\dao\revert.py" D:\GitRepo\emgui\src\schema\revert.xsd
#
# Current working directory (os.getcwd()):
#   Scripts
#

import sys
import re as re_
import base64
import datetime as datetime_
import warnings as warnings_
from lxml import etree as etree_


Validate_simpletypes_ = True


def parsexml_(infile, parser=None, **kwargs):
    if parser is None:
        # Use the lxml ElementTree compatible parser so that, e.g.,
        #   we ignore comments.
        parser = etree_.ETCompatXMLParser()
    doc = etree_.parse(infile, parser=parser, **kwargs)
    return doc

#
# User methods
#
# Calls to the methods in these classes are generated by generateDS.py.
# You can replace these methods by re-implementing the following class
#   in a module named generatedssuper.py.

try:
    from generatedssuper import GeneratedsSuper
except ImportError as exp:

    class GeneratedsSuper(object):
        tzoff_pattern = re_.compile(r'(\+|-)((0\d|1[0-3]):[0-5]\d|14:00)$')
        class _FixedOffsetTZ(datetime_.tzinfo):
            def __init__(self, offset, name):
                self.__offset = datetime_.timedelta(minutes=offset)
                self.__name = name
            def utcoffset(self, dt):
                return self.__offset
            def tzname(self, dt):
                return self.__name
            def dst(self, dt):
                return None
        def gds_format_string(self, input_data, input_name=''):
            return input_data
        def gds_validate_string(self, input_data, node=None, input_name=''):
            if not input_data:
                return ''
            else:
                return input_data
        def gds_format_base64(self, input_data, input_name=''):
            return base64.b64encode(input_data)
        def gds_validate_base64(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_integer(self, input_data, input_name=''):
            return '%d' % input_data
        def gds_validate_integer(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_integer_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_integer_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    int(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of integers')
            return values
        def gds_format_float(self, input_data, input_name=''):
            return ('%.15f' % input_data).rstrip('0')
        def gds_validate_float(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_float_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_float_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of floats')
            return values
        def gds_format_double(self, input_data, input_name=''):
            return '%e' % input_data
        def gds_validate_double(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_double_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_double_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of doubles')
            return values
        def gds_format_boolean(self, input_data, input_name=''):
            return ('%s' % input_data).lower()
        def gds_validate_boolean(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_boolean_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_boolean_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                if value not in ('true', '1', 'false', '0', ):
                    raise_parse_error(
                        node,
                        'Requires sequence of booleans '
                        '("true", "1", "false", "0")')
            return values
        def gds_validate_datetime(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_datetime(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d.%s' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue
        @classmethod
        def gds_parse_datetime(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            time_parts = input_data.split('.')
            if len(time_parts) > 1:
                micro_seconds = int(float('0.' + time_parts[1]) * 1000000)
                input_data = '%s.%s' % (time_parts[0], micro_seconds, )
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt
        def gds_validate_date(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_date(self, input_data, input_name=''):
            _svalue = '%04d-%02d-%02d' % (
                input_data.year,
                input_data.month,
                input_data.day,
            )
            try:
                if input_data.tzinfo is not None:
                    tzoff = input_data.tzinfo.utcoffset(input_data)
                    if tzoff is not None:
                        total_seconds = tzoff.seconds + (86400 * tzoff.days)
                        if total_seconds == 0:
                            _svalue += 'Z'
                        else:
                            if total_seconds < 0:
                                _svalue += '-'
                                total_seconds *= -1
                            else:
                                _svalue += '+'
                            hours = total_seconds // 3600
                            minutes = (total_seconds - (hours * 3600)) // 60
                            _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            except AttributeError:
                pass
            return _svalue
        @classmethod
        def gds_parse_date(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            dt = datetime_.datetime.strptime(input_data, '%Y-%m-%d')
            dt = dt.replace(tzinfo=tz)
            return dt.date()
        def gds_validate_time(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_time(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%02d:%02d:%02d' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%02d:%02d:%02d.%s' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue
        def gds_validate_simple_patterns(self, patterns, target):
            # pat is a list of lists of strings/patterns.  We should:
            # - AND the outer elements
            # - OR the inner elements
            found1 = True
            for patterns1 in patterns:
                found2 = False
                for patterns2 in patterns1:
                    if re_.search(patterns2, target) is not None:
                        found2 = True
                        break
                if not found2:
                    found1 = False
                    break
            return found1
        @classmethod
        def gds_parse_time(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            if len(input_data.split('.')) > 1:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt.time()
        def gds_str_lower(self, instring):
            return instring.lower()
        def get_path_(self, node):
            path_list = []
            self.get_path_list_(node, path_list)
            path_list.reverse()
            path = '/'.join(path_list)
            return path
        Tag_strip_pattern_ = re_.compile(r'\{.*\}')
        def get_path_list_(self, node, path_list):
            if node is None:
                return
            tag = GeneratedsSuper.Tag_strip_pattern_.sub('', node.tag)
            if tag:
                path_list.append(tag)
            self.get_path_list_(node.getparent(), path_list)
        def get_class_obj_(self, node, default_class=None):
            class_obj1 = default_class
            if 'xsi' in node.nsmap:
                classname = node.get('{%s}type' % node.nsmap['xsi'])
                if classname is not None:
                    names = classname.split(':')
                    if len(names) == 2:
                        classname = names[1]
                    class_obj2 = globals().get(classname)
                    if class_obj2 is not None:
                        class_obj1 = class_obj2
            return class_obj1
        def gds_build_any(self, node, type_name=None):
            return None
        @classmethod
        def gds_reverse_node_mapping(cls, mapping):
            return dict(((v, k) for k, v in mapping.iteritems()))


#
# If you have installed IPython you can uncomment and use the following.
# IPython is available from http://ipython.scipy.org/.
#

## from IPython.Shell import IPShellEmbed
## args = ''
## ipshell = IPShellEmbed(args,
##     banner = 'Dropping into IPython',
##     exit_msg = 'Leaving Interpreter, back to program.')

# Then use the following line where and when you want to drop into the
# IPython shell:
#    ipshell('<some message> -- Entering ipshell.\nHit Ctrl-D to exit')

#
# Globals
#

ExternalEncoding = 'ascii'
Tag_pattern_ = re_.compile(r'({.*})?(.*)')
String_cleanup_pat_ = re_.compile(r"[\n\r\s]+")
Namespace_extract_pat_ = re_.compile(r'{(.*)}(.*)')
CDATA_pattern_ = re_.compile(r"<!\[CDATA\[.*?\]\]>", re_.DOTALL)

#
# Support/utility functions.
#


def showIndent(outfile, level, pretty_print=True):
    if pretty_print:
        for idx in range(level):
            outfile.write('    ')


def quote_xml(inStr):
    "Escape markup chars, but do not modify CDATA sections."
    if not inStr:
        return ''
    s1 = (isinstance(inStr, basestring) and inStr or
          '%s' % inStr)
    s2 = ''
    pos = 0
    matchobjects = CDATA_pattern_.finditer(s1)
    for mo in matchobjects:
        s3 = s1[pos:mo.start()]
        s2 += quote_xml_aux(s3)
        s2 += s1[mo.start():mo.end()]
        pos = mo.end()
    s3 = s1[pos:]
    s2 += quote_xml_aux(s3)
    return s2


def quote_xml_aux(inStr):
    s1 = inStr.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    return s1


def quote_attrib(inStr):
    s1 = (isinstance(inStr, basestring) and inStr or
          '%s' % inStr)
    s1 = s1.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    if '"' in s1:
        if "'" in s1:
            s1 = '"%s"' % s1.replace('"', "&quot;")
        else:
            s1 = "'%s'" % s1
    else:
        s1 = '"%s"' % s1
    return s1


def quote_python(inStr):
    s1 = inStr
    if s1.find("'") == -1:
        if s1.find('\n') == -1:
            return "'%s'" % s1
        else:
            return "'''%s'''" % s1
    else:
        if s1.find('"') != -1:
            s1 = s1.replace('"', '\\"')
        if s1.find('\n') == -1:
            return '"%s"' % s1
        else:
            return '"""%s"""' % s1


def get_all_text_(node):
    if node.text is not None:
        text = node.text
    else:
        text = ''
    for child in node:
        if child.tail is not None:
            text += child.tail
    return text


def find_attr_value_(attr_name, node):
    attrs = node.attrib
    attr_parts = attr_name.split(':')
    value = None
    if len(attr_parts) == 1:
        value = attrs.get(attr_name)
    elif len(attr_parts) == 2:
        prefix, name = attr_parts
        namespace = node.nsmap.get(prefix)
        if namespace is not None:
            value = attrs.get('{%s}%s' % (namespace, name, ))
    return value


class GDSParseError(Exception):
    pass


def raise_parse_error(node, msg):
    msg = '%s (element %s/line %d)' % (msg, node.tag, node.sourceline, )
    raise GDSParseError(msg)


class MixedContainer:
    # Constants for category:
    CategoryNone = 0
    CategoryText = 1
    CategorySimple = 2
    CategoryComplex = 3
    # Constants for content_type:
    TypeNone = 0
    TypeText = 1
    TypeString = 2
    TypeInteger = 3
    TypeFloat = 4
    TypeDecimal = 5
    TypeDouble = 6
    TypeBoolean = 7
    TypeBase64 = 8
    def __init__(self, category, content_type, name, value):
        self.category = category
        self.content_type = content_type
        self.name = name
        self.value = value
    def getCategory(self):
        return self.category
    def getContenttype(self, content_type):
        return self.content_type
    def getValue(self):
        return self.value
    def getName(self):
        return self.name
    def export(self, outfile, level, name, namespace, pretty_print=True):
        if self.category == MixedContainer.CategoryText:
            # Prevent exporting empty content as empty lines.
            if self.value.strip():
                outfile.write(self.value)
        elif self.category == MixedContainer.CategorySimple:
            self.exportSimple(outfile, level, name)
        else:    # category == MixedContainer.CategoryComplex
            self.value.export(outfile, level, namespace, name, pretty_print)
    def exportSimple(self, outfile, level, name):
        if self.content_type == MixedContainer.TypeString:
            outfile.write('<%s>%s</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeInteger or \
                self.content_type == MixedContainer.TypeBoolean:
            outfile.write('<%s>%d</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeFloat or \
                self.content_type == MixedContainer.TypeDecimal:
            outfile.write('<%s>%f</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeDouble:
            outfile.write('<%s>%g</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeBase64:
            outfile.write('<%s>%s</%s>' % (
                self.name, base64.b64encode(self.value), self.name))
    def to_etree(self, element):
        if self.category == MixedContainer.CategoryText:
            # Prevent exporting empty content as empty lines.
            if self.value.strip():
                if len(element) > 0:
                    if element[-1].tail is None:
                        element[-1].tail = self.value
                    else:
                        element[-1].tail += self.value
                else:
                    if element.text is None:
                        element.text = self.value
                    else:
                        element.text += self.value
        elif self.category == MixedContainer.CategorySimple:
            subelement = etree_.SubElement(element, '%s' % self.name)
            subelement.text = self.to_etree_simple()
        else:    # category == MixedContainer.CategoryComplex
            self.value.to_etree(element)
    def to_etree_simple(self):
        if self.content_type == MixedContainer.TypeString:
            text = self.value
        elif (self.content_type == MixedContainer.TypeInteger or
                self.content_type == MixedContainer.TypeBoolean):
            text = '%d' % self.value
        elif (self.content_type == MixedContainer.TypeFloat or
                self.content_type == MixedContainer.TypeDecimal):
            text = '%f' % self.value
        elif self.content_type == MixedContainer.TypeDouble:
            text = '%g' % self.value
        elif self.content_type == MixedContainer.TypeBase64:
            text = '%s' % base64.b64encode(self.value)
        return text
    def exportLiteral(self, outfile, level, name):
        if self.category == MixedContainer.CategoryText:
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s", "%s"),\n' % (
                    self.category, self.content_type, self.name, self.value))
        elif self.category == MixedContainer.CategorySimple:
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s", "%s"),\n' % (
                    self.category, self.content_type, self.name, self.value))
        else:    # category == MixedContainer.CategoryComplex
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s",\n' % (
                    self.category, self.content_type, self.name,))
            self.value.exportLiteral(outfile, level + 1)
            showIndent(outfile, level)
            outfile.write(')\n')


class MemberSpec_(object):
    def __init__(self, name='', data_type='', container=0):
        self.name = name
        self.data_type = data_type
        self.container = container
    def set_name(self, name): self.name = name
    def get_name(self): return self.name
    def set_data_type(self, data_type): self.data_type = data_type
    def get_data_type_chain(self): return self.data_type
    def get_data_type(self):
        if isinstance(self.data_type, list):
            if len(self.data_type) > 0:
                return self.data_type[-1]
            else:
                return 'xs:string'
        else:
            return self.data_type
    def set_container(self, container): self.container = container
    def get_container(self): return self.container


def _cast(typ, value):
    if typ is None or value is None:
        return value
    return typ(value)

#
# Data representation classes.
#


class Property(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, ship_name=None, call_sign=None, voyage_number=None, captain_name=None, date=None, voyage_detail=None, via=None, use_dw_route=None, use_critial_point=None, critial_point=None, route_number=None, modify_route=None, modify_reason=None, paper_chart=None, voyage_data=None, total_bunker_consumption=None, average_bunker_consumption_per_nm=None, remark=None):
        self.original_tagname_ = None
        self.ship_name = ship_name
        self.call_sign = call_sign
        self.voyage_number = voyage_number
        self.captain_name = captain_name
        if isinstance(date, basestring):
            initvalue_ = datetime_.datetime.strptime(date, '%Y-%m-%d').date()
        else:
            initvalue_ = date
        self.date = initvalue_
        self.voyage_detail = voyage_detail
        self.via = via
        self.use_dw_route = use_dw_route
        self.use_critial_point = use_critial_point
        self.critial_point = critial_point
        self.route_number = route_number
        self.modify_route = modify_route
        self.modify_reason = modify_reason
        self.paper_chart = paper_chart
        self.voyage_data = voyage_data
        self.total_bunker_consumption = total_bunker_consumption
        self.average_bunker_consumption_per_nm = average_bunker_consumption_per_nm
        self.remark = remark
    def factory(*args_, **kwargs_):
        if Property.subclass:
            return Property.subclass(*args_, **kwargs_)
        else:
            return Property(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.ship_name is not None or
            self.call_sign is not None or
            self.voyage_number is not None or
            self.captain_name is not None or
            self.date is not None or
            self.voyage_detail is not None or
            self.via is not None or
            self.use_dw_route is not None or
            self.use_critial_point is not None or
            self.critial_point is not None or
            self.route_number is not None or
            self.modify_route is not None or
            self.modify_reason is not None or
            self.paper_chart is not None or
            self.voyage_data is not None or
            self.total_bunker_consumption is not None or
            self.average_bunker_consumption_per_nm is not None or
            self.remark is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='Property', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='Property')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='Property', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='Property'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='Property', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.ship_name is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sship_name>%s</%sship_name>%s' % (namespace_, self.gds_format_string(quote_xml(self.ship_name).encode(ExternalEncoding), input_name='ship_name'), namespace_, eol_))
        if self.call_sign is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%scall_sign>%s</%scall_sign>%s' % (namespace_, self.gds_format_string(quote_xml(self.call_sign).encode(ExternalEncoding), input_name='call_sign'), namespace_, eol_))
        if self.voyage_number is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%svoyage_number>%s</%svoyage_number>%s' % (namespace_, self.gds_format_string(quote_xml(self.voyage_number).encode(ExternalEncoding), input_name='voyage_number'), namespace_, eol_))
        if self.captain_name is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%scaptain_name>%s</%scaptain_name>%s' % (namespace_, self.gds_format_string(quote_xml(self.captain_name).encode(ExternalEncoding), input_name='captain_name'), namespace_, eol_))
        if self.date is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdate>%s</%sdate>%s' % (namespace_, self.gds_format_date(self.date, input_name='date'), namespace_, eol_))
        if self.voyage_detail is not None:
            self.voyage_detail.export(outfile, level, namespace_, name_='voyage_detail', pretty_print=pretty_print)
        if self.via is not None:
            self.via.export(outfile, level, namespace_, name_='via', pretty_print=pretty_print)
        if self.use_dw_route is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%suse_dw_route>%s</%suse_dw_route>%s' % (namespace_, self.gds_format_boolean(self.use_dw_route, input_name='use_dw_route'), namespace_, eol_))
        if self.use_critial_point is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%suse_critial_point>%s</%suse_critial_point>%s' % (namespace_, self.gds_format_boolean(self.use_critial_point, input_name='use_critial_point'), namespace_, eol_))
        if self.critial_point is not None:
            self.critial_point.export(outfile, level, namespace_, name_='critial_point', pretty_print=pretty_print)
        if self.route_number is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sroute_number>%s</%sroute_number>%s' % (namespace_, self.gds_format_integer(self.route_number, input_name='route_number'), namespace_, eol_))
        if self.modify_route is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smodify_route>%s</%smodify_route>%s' % (namespace_, self.gds_format_boolean(self.modify_route, input_name='modify_route'), namespace_, eol_))
        if self.modify_reason is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smodify_reason>%s</%smodify_reason>%s' % (namespace_, self.gds_format_string(quote_xml(self.modify_reason).encode(ExternalEncoding), input_name='modify_reason'), namespace_, eol_))
        if self.paper_chart is not None:
            self.paper_chart.export(outfile, level, namespace_, name_='paper_chart', pretty_print=pretty_print)
        if self.voyage_data is not None:
            self.voyage_data.export(outfile, level, namespace_, name_='voyage_data', pretty_print=pretty_print)
        if self.total_bunker_consumption is not None:
            self.total_bunker_consumption.export(outfile, level, namespace_, name_='total_bunker_consumption', pretty_print=pretty_print)
        if self.average_bunker_consumption_per_nm is not None:
            self.average_bunker_consumption_per_nm.export(outfile, level, namespace_, name_='average_bunker_consumption_per_nm', pretty_print=pretty_print)
        if self.remark is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sremark>%s</%sremark>%s' % (namespace_, self.gds_format_string(quote_xml(self.remark).encode(ExternalEncoding), input_name='remark'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'ship_name':
            ship_name_ = child_.text
            ship_name_ = self.gds_validate_string(ship_name_, node, 'ship_name')
            self.ship_name = ship_name_
        elif nodeName_ == 'call_sign':
            call_sign_ = child_.text
            call_sign_ = self.gds_validate_string(call_sign_, node, 'call_sign')
            self.call_sign = call_sign_
        elif nodeName_ == 'voyage_number':
            voyage_number_ = child_.text
            voyage_number_ = self.gds_validate_string(voyage_number_, node, 'voyage_number')
            self.voyage_number = voyage_number_
        elif nodeName_ == 'captain_name':
            captain_name_ = child_.text
            captain_name_ = self.gds_validate_string(captain_name_, node, 'captain_name')
            self.captain_name = captain_name_
        elif nodeName_ == 'date':
            sval_ = child_.text
            dval_ = self.gds_parse_date(sval_)
            self.date = dval_
        elif nodeName_ == 'voyage_detail':
            obj_ = voyage_detail.factory()
            obj_.build(child_)
            self.voyage_detail = obj_
            obj_.original_tagname_ = 'voyage_detail'
        elif nodeName_ == 'via':
            obj_ = via.factory()
            obj_.build(child_)
            self.via = obj_
            obj_.original_tagname_ = 'via'
        elif nodeName_ == 'use_dw_route':
            sval_ = child_.text
            if sval_ in ('true', '1'):
                ival_ = True
            elif sval_ in ('false', '0'):
                ival_ = False
            else:
                raise_parse_error(child_, 'requires boolean')
            ival_ = self.gds_validate_boolean(ival_, node, 'use_dw_route')
            self.use_dw_route = ival_
        elif nodeName_ == 'use_critial_point':
            sval_ = child_.text
            if sval_ in ('true', '1'):
                ival_ = True
            elif sval_ in ('false', '0'):
                ival_ = False
            else:
                raise_parse_error(child_, 'requires boolean')
            ival_ = self.gds_validate_boolean(ival_, node, 'use_critial_point')
            self.use_critial_point = ival_
        elif nodeName_ == 'critial_point':
            obj_ = critial_point.factory()
            obj_.build(child_)
            self.critial_point = obj_
            obj_.original_tagname_ = 'critial_point'
        elif nodeName_ == 'route_number':
            sval_ = child_.text
            try:
                ival_ = int(sval_)
            except (TypeError, ValueError) as exp:
                raise_parse_error(child_, 'requires integer: %s' % exp)
            ival_ = self.gds_validate_integer(ival_, node, 'route_number')
            self.route_number = ival_
        elif nodeName_ == 'modify_route':
            sval_ = child_.text
            if sval_ in ('true', '1'):
                ival_ = True
            elif sval_ in ('false', '0'):
                ival_ = False
            else:
                raise_parse_error(child_, 'requires boolean')
            ival_ = self.gds_validate_boolean(ival_, node, 'modify_route')
            self.modify_route = ival_
        elif nodeName_ == 'modify_reason':
            modify_reason_ = child_.text
            modify_reason_ = self.gds_validate_string(modify_reason_, node, 'modify_reason')
            self.modify_reason = modify_reason_
        elif nodeName_ == 'paper_chart':
            obj_ = paper_chart.factory()
            obj_.build(child_)
            self.paper_chart = obj_
            obj_.original_tagname_ = 'paper_chart'
        elif nodeName_ == 'voyage_data':
            obj_ = voyage_data.factory()
            obj_.build(child_)
            self.voyage_data = obj_
            obj_.original_tagname_ = 'voyage_data'
        elif nodeName_ == 'total_bunker_consumption':
            obj_ = total_bunker_consumption.factory()
            obj_.build(child_)
            self.total_bunker_consumption = obj_
            obj_.original_tagname_ = 'total_bunker_consumption'
        elif nodeName_ == 'average_bunker_consumption_per_nm':
            obj_ = average_bunker_consumption_per_nm.factory()
            obj_.build(child_)
            self.average_bunker_consumption_per_nm = obj_
            obj_.original_tagname_ = 'average_bunker_consumption_per_nm'
        elif nodeName_ == 'remark':
            remark_ = child_.text
            remark_ = self.gds_validate_string(remark_, node, 'remark')
            self.remark = remark_
# end class Property


class arrival(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, arrival_date=None, arrival_time=None, country=None, port=None, unlo_code=None, terminal=None):
        self.original_tagname_ = None
        if isinstance(arrival_date, basestring):
            initvalue_ = datetime_.datetime.strptime(arrival_date, '%Y-%m-%d').date()
        else:
            initvalue_ = arrival_date
        self.arrival_date = initvalue_
        if isinstance(arrival_time, basestring):
            initvalue_ = datetime_.datetime.strptime(arrival_time, '%H:%M:%S').time()
        else:
            initvalue_ = arrival_time
        self.arrival_time = initvalue_
        self.country = country
        self.port = port
        self.unlo_code = unlo_code
        self.terminal = terminal
    def factory(*args_, **kwargs_):
        if arrival.subclass:
            return arrival.subclass(*args_, **kwargs_)
        else:
            return arrival(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.arrival_date is not None or
            self.arrival_time is not None or
            self.country is not None or
            self.port is not None or
            self.unlo_code is not None or
            self.terminal is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='arrival', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='arrival')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='arrival', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='arrival'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='arrival', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.arrival_date is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sarrival_date>%s</%sarrival_date>%s' % (namespace_, self.gds_format_date(self.arrival_date, input_name='arrival_date'), namespace_, eol_))
        if self.arrival_time is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sarrival_time>%s</%sarrival_time>%s' % (namespace_, self.gds_format_time(self.arrival_time, input_name='arrival_time'), namespace_, eol_))
        if self.country is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%scountry>%s</%scountry>%s' % (namespace_, self.gds_format_string(quote_xml(self.country).encode(ExternalEncoding), input_name='country'), namespace_, eol_))
        if self.port is not None:
            self.port.export(outfile, level, namespace_, name_='port', pretty_print=pretty_print)
        if self.unlo_code is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sunlo_code>%s</%sunlo_code>%s' % (namespace_, self.gds_format_string(quote_xml(self.unlo_code).encode(ExternalEncoding), input_name='unlo_code'), namespace_, eol_))
        if self.terminal is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sterminal>%s</%sterminal>%s' % (namespace_, self.gds_format_string(quote_xml(self.terminal).encode(ExternalEncoding), input_name='terminal'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'arrival_date':
            sval_ = child_.text
            dval_ = self.gds_parse_date(sval_)
            self.arrival_date = dval_
        elif nodeName_ == 'arrival_time':
            sval_ = child_.text
            dval_ = self.gds_parse_time(sval_)
            self.arrival_time = dval_
        elif nodeName_ == 'country':
            country_ = child_.text
            country_ = self.gds_validate_string(country_, node, 'country')
            self.country = country_
        elif nodeName_ == 'port':
            obj_ = port.factory()
            obj_.build(child_)
            self.port = obj_
            obj_.original_tagname_ = 'port'
        elif nodeName_ == 'unlo_code':
            unlo_code_ = child_.text
            unlo_code_ = self.gds_validate_string(unlo_code_, node, 'unlo_code')
            self.unlo_code = unlo_code_
        elif nodeName_ == 'terminal':
            terminal_ = child_.text
            terminal_ = self.gds_validate_string(terminal_, node, 'terminal')
            self.terminal = terminal_
# end class arrival


class average_bunker_consumption_per_nm(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, ifo=None, mdo=None, lsfo=None, lsmdo=None):
        self.original_tagname_ = None
        self.ifo = ifo
        self.mdo = mdo
        self.lsfo = lsfo
        self.lsmdo = lsmdo
    def factory(*args_, **kwargs_):
        if average_bunker_consumption_per_nm.subclass:
            return average_bunker_consumption_per_nm.subclass(*args_, **kwargs_)
        else:
            return average_bunker_consumption_per_nm(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.ifo is not None or
            self.mdo is not None or
            self.lsfo is not None or
            self.lsmdo is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='average_bunker_consumption_per_nm', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='average_bunker_consumption_per_nm')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='average_bunker_consumption_per_nm', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='average_bunker_consumption_per_nm'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='average_bunker_consumption_per_nm', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.ifo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sifo>%s</%sifo>%s' % (namespace_, self.gds_format_string(quote_xml(self.ifo).encode(ExternalEncoding), input_name='ifo'), namespace_, eol_))
        if self.mdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smdo>%s</%smdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.mdo).encode(ExternalEncoding), input_name='mdo'), namespace_, eol_))
        if self.lsfo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slsfo>%s</%slsfo>%s' % (namespace_, self.gds_format_string(quote_xml(self.lsfo).encode(ExternalEncoding), input_name='lsfo'), namespace_, eol_))
        if self.lsmdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slsmdo>%s</%slsmdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.lsmdo).encode(ExternalEncoding), input_name='lsmdo'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'ifo':
            ifo_ = child_.text
            ifo_ = self.gds_validate_string(ifo_, node, 'ifo')
            self.ifo = ifo_
        elif nodeName_ == 'mdo':
            mdo_ = child_.text
            mdo_ = self.gds_validate_string(mdo_, node, 'mdo')
            self.mdo = mdo_
        elif nodeName_ == 'lsfo':
            lsfo_ = child_.text
            lsfo_ = self.gds_validate_string(lsfo_, node, 'lsfo')
            self.lsfo = lsfo_
        elif nodeName_ == 'lsmdo':
            lsmdo_ = child_.text
            lsmdo_ = self.gds_validate_string(lsmdo_, node, 'lsmdo')
            self.lsmdo = lsmdo_
# end class average_bunker_consumption_per_nm


class critial_point(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, point=None):
        self.original_tagname_ = None
        self.point = point
    def factory(*args_, **kwargs_):
        if critial_point.subclass:
            return critial_point.subclass(*args_, **kwargs_)
        else:
            return critial_point(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.point is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='critial_point', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='critial_point')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='critial_point', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='critial_point'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='critial_point', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.point is not None:
            self.point.export(outfile, level, namespace_, name_='point', pretty_print=pretty_print)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'point':
            obj_ = point.factory()
            obj_.build(child_)
            self.point = obj_
            obj_.original_tagname_ = 'point'
# end class critial_point


class departure(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, departure_date=None, departure_time=None, country=None, port=None, unlo_code=None, terminal=None):
        self.original_tagname_ = None
        if isinstance(departure_date, basestring):
            initvalue_ = datetime_.datetime.strptime(departure_date, '%Y-%m-%d').date()
        else:
            initvalue_ = departure_date
        self.departure_date = initvalue_
        if isinstance(departure_time, basestring):
            initvalue_ = datetime_.datetime.strptime(departure_time, '%H:%M:%S').time()
        else:
            initvalue_ = departure_time
        self.departure_time = initvalue_
        self.country = country
        self.port = port
        self.unlo_code = unlo_code
        self.terminal = terminal
    def factory(*args_, **kwargs_):
        if departure.subclass:
            return departure.subclass(*args_, **kwargs_)
        else:
            return departure(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.departure_date is not None or
            self.departure_time is not None or
            self.country is not None or
            self.port is not None or
            self.unlo_code is not None or
            self.terminal is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='departure', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='departure')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='departure', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='departure'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='departure', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.departure_date is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdeparture_date>%s</%sdeparture_date>%s' % (namespace_, self.gds_format_date(self.departure_date, input_name='departure_date'), namespace_, eol_))
        if self.departure_time is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdeparture_time>%s</%sdeparture_time>%s' % (namespace_, self.gds_format_time(self.departure_time, input_name='departure_time'), namespace_, eol_))
        if self.country is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%scountry>%s</%scountry>%s' % (namespace_, self.gds_format_string(quote_xml(self.country).encode(ExternalEncoding), input_name='country'), namespace_, eol_))
        if self.port is not None:
            self.port.export(outfile, level, namespace_, name_='port', pretty_print=pretty_print)
        if self.unlo_code is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sunlo_code>%s</%sunlo_code>%s' % (namespace_, self.gds_format_string(quote_xml(self.unlo_code).encode(ExternalEncoding), input_name='unlo_code'), namespace_, eol_))
        if self.terminal is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sterminal>%s</%sterminal>%s' % (namespace_, self.gds_format_string(quote_xml(self.terminal).encode(ExternalEncoding), input_name='terminal'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'departure_date':
            sval_ = child_.text
            dval_ = self.gds_parse_date(sval_)
            self.departure_date = dval_
        elif nodeName_ == 'departure_time':
            sval_ = child_.text
            dval_ = self.gds_parse_time(sval_)
            self.departure_time = dval_
        elif nodeName_ == 'country':
            country_ = child_.text
            country_ = self.gds_validate_string(country_, node, 'country')
            self.country = country_
        elif nodeName_ == 'port':
            obj_ = port.factory()
            obj_.build(child_)
            self.port = obj_
            obj_.original_tagname_ = 'port'
        elif nodeName_ == 'unlo_code':
            unlo_code_ = child_.text
            unlo_code_ = self.gds_validate_string(unlo_code_, node, 'unlo_code')
            self.unlo_code = unlo_code_
        elif nodeName_ == 'terminal':
            terminal_ = child_.text
            terminal_ = self.gds_validate_string(terminal_, node, 'terminal')
            self.terminal = terminal_
# end class departure


class paper(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self):
        self.original_tagname_ = None
    def factory(*args_, **kwargs_):
        if paper.subclass:
            return paper.subclass(*args_, **kwargs_)
        else:
            return paper(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (

        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='paper', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='paper')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='paper', pretty_print=pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='paper'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='paper', fromsubclass_=False, pretty_print=True):
        pass
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        pass
# end class paper


class paper_chart(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, paper=None):
        self.original_tagname_ = None
        self.paper = paper
    def factory(*args_, **kwargs_):
        if paper_chart.subclass:
            return paper_chart.subclass(*args_, **kwargs_)
        else:
            return paper_chart(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.paper is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='paper_chart', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='paper_chart')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='paper_chart', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='paper_chart'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='paper_chart', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.paper is not None:
            self.paper.export(outfile, level, namespace_, name_='paper', pretty_print=pretty_print)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'paper':
            obj_ = paper.factory()
            obj_.build(child_)
            self.paper = obj_
            obj_.original_tagname_ = 'paper'
# end class paper_chart


class point(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, latitude=None, longtitude=None):
        self.original_tagname_ = None
        self.latitude = latitude
        self.longtitude = longtitude
    def factory(*args_, **kwargs_):
        if point.subclass:
            return point.subclass(*args_, **kwargs_)
        else:
            return point(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.latitude is not None or
            self.longtitude is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='point', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='point')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='point', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='point'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='point', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.latitude is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slatitude>%s</%slatitude>%s' % (namespace_, self.gds_format_float(self.latitude, input_name='latitude'), namespace_, eol_))
        if self.longtitude is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slongtitude>%s</%slongtitude>%s' % (namespace_, self.gds_format_float(self.longtitude, input_name='longtitude'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'latitude':
            sval_ = child_.text
            try:
                fval_ = float(sval_)
            except (TypeError, ValueError) as exp:
                raise_parse_error(child_, 'requires float or double: %s' % exp)
            fval_ = self.gds_validate_float(fval_, node, 'latitude')
            self.latitude = fval_
        elif nodeName_ == 'longtitude':
            sval_ = child_.text
            try:
                fval_ = float(sval_)
            except (TypeError, ValueError) as exp:
                raise_parse_error(child_, 'requires float or double: %s' % exp)
            fval_ = self.gds_validate_float(fval_, node, 'longtitude')
            self.longtitude = fval_
# end class point


class port(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self):
        self.original_tagname_ = None
    def factory(*args_, **kwargs_):
        if port.subclass:
            return port.subclass(*args_, **kwargs_)
        else:
            return port(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (

        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='port', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='port')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='port', pretty_print=pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='port'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='port', fromsubclass_=False, pretty_print=True):
        pass
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        pass
# end class port


class revert_report(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, Property=None):
        self.original_tagname_ = None
        self.Property = Property
    def factory(*args_, **kwargs_):
        if revert_report.subclass:
            return revert_report.subclass(*args_, **kwargs_)
        else:
            return revert_report(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.Property is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='revert_report', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='revert_report')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='revert_report', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='revert_report'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='revert_report', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.Property is not None:
            self.Property.export(outfile, level, namespace_, name_='Property', pretty_print=pretty_print)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'Property':
            obj_ = Property.factory()
            obj_.build(child_)
            self.Property = obj_
            obj_.original_tagname_ = 'Property'
# end class revert_report


class total_bunker_consumption(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, ifo=None, mdo=None, lsfo=None, lsmdo=None):
        self.original_tagname_ = None
        self.ifo = ifo
        self.mdo = mdo
        self.lsfo = lsfo
        self.lsmdo = lsmdo
    def factory(*args_, **kwargs_):
        if total_bunker_consumption.subclass:
            return total_bunker_consumption.subclass(*args_, **kwargs_)
        else:
            return total_bunker_consumption(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.ifo is not None or
            self.mdo is not None or
            self.lsfo is not None or
            self.lsmdo is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='total_bunker_consumption', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='total_bunker_consumption')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='total_bunker_consumption', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='total_bunker_consumption'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='total_bunker_consumption', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.ifo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sifo>%s</%sifo>%s' % (namespace_, self.gds_format_string(quote_xml(self.ifo).encode(ExternalEncoding), input_name='ifo'), namespace_, eol_))
        if self.mdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smdo>%s</%smdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.mdo).encode(ExternalEncoding), input_name='mdo'), namespace_, eol_))
        if self.lsfo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slsfo>%s</%slsfo>%s' % (namespace_, self.gds_format_string(quote_xml(self.lsfo).encode(ExternalEncoding), input_name='lsfo'), namespace_, eol_))
        if self.lsmdo is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%slsmdo>%s</%slsmdo>%s' % (namespace_, self.gds_format_string(quote_xml(self.lsmdo).encode(ExternalEncoding), input_name='lsmdo'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'ifo':
            ifo_ = child_.text
            ifo_ = self.gds_validate_string(ifo_, node, 'ifo')
            self.ifo = ifo_
        elif nodeName_ == 'mdo':
            mdo_ = child_.text
            mdo_ = self.gds_validate_string(mdo_, node, 'mdo')
            self.mdo = mdo_
        elif nodeName_ == 'lsfo':
            lsfo_ = child_.text
            lsfo_ = self.gds_validate_string(lsfo_, node, 'lsfo')
            self.lsfo = lsfo_
        elif nodeName_ == 'lsmdo':
            lsmdo_ = child_.text
            lsmdo_ = self.gds_validate_string(lsmdo_, node, 'lsmdo')
            self.lsmdo = lsmdo_
# end class total_bunker_consumption


class via(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, port=None):
        self.original_tagname_ = None
        self.port = port
    def factory(*args_, **kwargs_):
        if via.subclass:
            return via.subclass(*args_, **kwargs_)
        else:
            return via(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.port is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='via', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='via')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='via', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='via'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='via', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.port is not None:
            self.port.export(outfile, level, namespace_, name_='port', pretty_print=pretty_print)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'port':
            obj_ = port.factory()
            obj_.build(child_)
            self.port = obj_
            obj_.original_tagname_ = 'port'
# end class via


class voyage_data(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, maximum_draft=None, minimum_ukc=None, load_condition=None, displacement=None, cargo_shipped=None, total_distance=None, total_streaming_time=None, average_speed=None, average_slip=None, me_revolution_distance=None, average_me_rmp=None):
        self.original_tagname_ = None
        self.maximum_draft = maximum_draft
        self.minimum_ukc = minimum_ukc
        self.load_condition = load_condition
        self.displacement = displacement
        self.cargo_shipped = cargo_shipped
        self.total_distance = total_distance
        self.total_streaming_time = total_streaming_time
        self.average_speed = average_speed
        self.average_slip = average_slip
        self.me_revolution_distance = me_revolution_distance
        self.average_me_rmp = average_me_rmp
    def factory(*args_, **kwargs_):
        if voyage_data.subclass:
            return voyage_data.subclass(*args_, **kwargs_)
        else:
            return voyage_data(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.maximum_draft is not None or
            self.minimum_ukc is not None or
            self.load_condition is not None or
            self.displacement is not None or
            self.cargo_shipped is not None or
            self.total_distance is not None or
            self.total_streaming_time is not None or
            self.average_speed is not None or
            self.average_slip is not None or
            self.me_revolution_distance is not None or
            self.average_me_rmp is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='voyage_data', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='voyage_data')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='voyage_data', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='voyage_data'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='voyage_data', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.maximum_draft is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smaximum_draft>%s</%smaximum_draft>%s' % (namespace_, self.gds_format_string(quote_xml(self.maximum_draft).encode(ExternalEncoding), input_name='maximum_draft'), namespace_, eol_))
        if self.minimum_ukc is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sminimum_ukc>%s</%sminimum_ukc>%s' % (namespace_, self.gds_format_string(quote_xml(self.minimum_ukc).encode(ExternalEncoding), input_name='minimum_ukc'), namespace_, eol_))
        if self.load_condition is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sload_condition>%s</%sload_condition>%s' % (namespace_, self.gds_format_string(quote_xml(self.load_condition).encode(ExternalEncoding), input_name='load_condition'), namespace_, eol_))
        if self.displacement is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdisplacement>%s</%sdisplacement>%s' % (namespace_, self.gds_format_string(quote_xml(self.displacement).encode(ExternalEncoding), input_name='displacement'), namespace_, eol_))
        if self.cargo_shipped is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%scargo_shipped>%s</%scargo_shipped>%s' % (namespace_, self.gds_format_string(quote_xml(self.cargo_shipped).encode(ExternalEncoding), input_name='cargo_shipped'), namespace_, eol_))
        if self.total_distance is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%stotal_distance>%s</%stotal_distance>%s' % (namespace_, self.gds_format_string(quote_xml(self.total_distance).encode(ExternalEncoding), input_name='total_distance'), namespace_, eol_))
        if self.total_streaming_time is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%stotal_streaming_time>%s</%stotal_streaming_time>%s' % (namespace_, self.gds_format_string(quote_xml(self.total_streaming_time).encode(ExternalEncoding), input_name='total_streaming_time'), namespace_, eol_))
        if self.average_speed is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%saverage_speed>%s</%saverage_speed>%s' % (namespace_, self.gds_format_string(quote_xml(self.average_speed).encode(ExternalEncoding), input_name='average_speed'), namespace_, eol_))
        if self.average_slip is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%saverage_slip>%s</%saverage_slip>%s' % (namespace_, self.gds_format_string(quote_xml(self.average_slip).encode(ExternalEncoding), input_name='average_slip'), namespace_, eol_))
        if self.me_revolution_distance is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sme_revolution_distance>%s</%sme_revolution_distance>%s' % (namespace_, self.gds_format_string(quote_xml(self.me_revolution_distance).encode(ExternalEncoding), input_name='me_revolution_distance'), namespace_, eol_))
        if self.average_me_rmp is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%saverage_me_rmp>%s</%saverage_me_rmp>%s' % (namespace_, self.gds_format_string(quote_xml(self.average_me_rmp).encode(ExternalEncoding), input_name='average_me_rmp'), namespace_, eol_))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'maximum_draft':
            maximum_draft_ = child_.text
            maximum_draft_ = self.gds_validate_string(maximum_draft_, node, 'maximum_draft')
            self.maximum_draft = maximum_draft_
        elif nodeName_ == 'minimum_ukc':
            minimum_ukc_ = child_.text
            minimum_ukc_ = self.gds_validate_string(minimum_ukc_, node, 'minimum_ukc')
            self.minimum_ukc = minimum_ukc_
        elif nodeName_ == 'load_condition':
            load_condition_ = child_.text
            load_condition_ = self.gds_validate_string(load_condition_, node, 'load_condition')
            self.load_condition = load_condition_
        elif nodeName_ == 'displacement':
            displacement_ = child_.text
            displacement_ = self.gds_validate_string(displacement_, node, 'displacement')
            self.displacement = displacement_
        elif nodeName_ == 'cargo_shipped':
            cargo_shipped_ = child_.text
            cargo_shipped_ = self.gds_validate_string(cargo_shipped_, node, 'cargo_shipped')
            self.cargo_shipped = cargo_shipped_
        elif nodeName_ == 'total_distance':
            total_distance_ = child_.text
            total_distance_ = self.gds_validate_string(total_distance_, node, 'total_distance')
            self.total_distance = total_distance_
        elif nodeName_ == 'total_streaming_time':
            total_streaming_time_ = child_.text
            total_streaming_time_ = self.gds_validate_string(total_streaming_time_, node, 'total_streaming_time')
            self.total_streaming_time = total_streaming_time_
        elif nodeName_ == 'average_speed':
            average_speed_ = child_.text
            average_speed_ = self.gds_validate_string(average_speed_, node, 'average_speed')
            self.average_speed = average_speed_
        elif nodeName_ == 'average_slip':
            average_slip_ = child_.text
            average_slip_ = self.gds_validate_string(average_slip_, node, 'average_slip')
            self.average_slip = average_slip_
        elif nodeName_ == 'me_revolution_distance':
            me_revolution_distance_ = child_.text
            me_revolution_distance_ = self.gds_validate_string(me_revolution_distance_, node, 'me_revolution_distance')
            self.me_revolution_distance = me_revolution_distance_
        elif nodeName_ == 'average_me_rmp':
            average_me_rmp_ = child_.text
            average_me_rmp_ = self.gds_validate_string(average_me_rmp_, node, 'average_me_rmp')
            self.average_me_rmp = average_me_rmp_
# end class voyage_data


class voyage_detail(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, departure=None, arrival=None):
        self.original_tagname_ = None
        self.departure = departure
        self.arrival = arrival
    def factory(*args_, **kwargs_):
        if voyage_detail.subclass:
            return voyage_detail.subclass(*args_, **kwargs_)
        else:
            return voyage_detail(*args_, **kwargs_)
    factory = staticmethod(factory)
    def hasContent_(self):
        if (
            self.departure is not None or
            self.arrival is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='voyage_detail', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='voyage_detail')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='voyage_detail', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='voyage_detail'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='voyage_detail', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.departure is not None:
            self.departure.export(outfile, level, namespace_, name_='departure', pretty_print=pretty_print)
        if self.arrival is not None:
            self.arrival.export(outfile, level, namespace_, name_='arrival', pretty_print=pretty_print)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'departure':
            obj_ = departure.factory()
            obj_.build(child_)
            self.departure = obj_
            obj_.original_tagname_ = 'departure'
        elif nodeName_ == 'arrival':
            obj_ = arrival.factory()
            obj_.build(child_)
            self.arrival = obj_
            obj_.original_tagname_ = 'arrival'
# end class voyage_detail


GDSClassesMapping = {
}


USAGE_TEXT = """
Usage: python <Parser>.py [ -s ] <in_xml_file>
"""


def usage():
    print(USAGE_TEXT)
    sys.exit(1)


def get_root_tag(node):
    tag = Tag_pattern_.match(node.tag).groups()[-1]
    rootClass = GDSClassesMapping.get(tag)
    if rootClass is None:
        rootClass = globals().get(tag)
    return tag, rootClass


def parse(inFileName, silence=False):
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'Property'
        rootClass = Property
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    if not silence:
        sys.stdout.write('<?xml version="1.0" ?>\n')
        rootObj.export(
            sys.stdout, 0, name_=rootTag,
            namespacedef_='',
            pretty_print=True)
    return rootObj


def parseEtree(inFileName, silence=False):
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'Property'
        rootClass = Property
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    mapping = {}
    rootElement = rootObj.to_etree(None, name_=rootTag, mapping_=mapping)
    reverse_mapping = rootObj.gds_reverse_node_mapping(mapping)
    if not silence:
        content = etree_.tostring(
            rootElement, pretty_print=True,
            xml_declaration=True, encoding="utf-8")
        sys.stdout.write(content)
        sys.stdout.write('\n')
    return rootObj, rootElement, mapping, reverse_mapping


def parseString(inString, silence=False):
    from StringIO import StringIO
    parser = None
    doc = parsexml_(StringIO(inString), parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'Property'
        rootClass = Property
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    if not silence:
        sys.stdout.write('<?xml version="1.0" ?>\n')
        rootObj.export(
            sys.stdout, 0, name_=rootTag,
            namespacedef_='')
    return rootObj


def parseLiteral(inFileName, silence=False):
    parser = None
    doc = parsexml_(inFileName, parser)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'Property'
        rootClass = Property
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    if not silence:
        sys.stdout.write('#from revert import *\n\n')
        sys.stdout.write('import revert as model_\n\n')
        sys.stdout.write('rootObj = model_.rootClass(\n')
        rootObj.exportLiteral(sys.stdout, 0, name_=rootTag)
        sys.stdout.write(')\n')
    return rootObj


def main():
    args = sys.argv[1:]
    if len(args) == 1:
        parse(args[0])
    else:
        usage()


if __name__ == '__main__':
    #import pdb; pdb.set_trace()
    main()


__all__ = [
    "Property",
    "arrival",
    "average_bunker_consumption_per_nm",
    "critial_point",
    "departure",
    "paper",
    "paper_chart",
    "point",
    "port",
    "revert_report",
    "total_bunker_consumption",
    "via",
    "voyage_data",
    "voyage_detail"
]
