# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadRoute.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(916, 658)
        Form.setAutoFillBackground(True)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout_11 = QtGui.QGridLayout(Form)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.load_btn = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_btn.sizePolicy().hasHeightForWidth())
        self.load_btn.setSizePolicy(sizePolicy)
        self.load_btn.setObjectName(_fromUtf8("load_btn"))
        self.horizontalLayout_2.addWidget(self.load_btn)
        self.submit_btn = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_btn.sizePolicy().hasHeightForWidth())
        self.submit_btn.setSizePolicy(sizePolicy)
        self.submit_btn.setObjectName(_fromUtf8("submit_btn"))
        self.horizontalLayout_2.addWidget(self.submit_btn)
        self.cancel_btn = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_btn.sizePolicy().hasHeightForWidth())
        self.cancel_btn.setSizePolicy(sizePolicy)
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.gridLayout_11.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.general_tab = QtGui.QWidget()
        self.general_tab.setObjectName(_fromUtf8("general_tab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.general_tab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_5 = QtGui.QLabel(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_10.addWidget(self.label_5, 0, 0, 1, 1)
        self.ship_name_edit = QtGui.QLineEdit(self.general_tab)
        self.ship_name_edit.setEnabled(False)
        self.ship_name_edit.setObjectName(_fromUtf8("ship_name_edit"))
        self.gridLayout_10.addWidget(self.ship_name_edit, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_10.addWidget(self.label_18, 0, 2, 1, 1)
        self.call_sign_edit = QtGui.QLineEdit(self.general_tab)
        self.call_sign_edit.setEnabled(False)
        self.call_sign_edit.setObjectName(_fromUtf8("call_sign_edit"))
        self.gridLayout_10.addWidget(self.call_sign_edit, 0, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_10.addWidget(self.label_23, 0, 4, 1, 1)
        self.voyage_number_edit = QtGui.QLineEdit(self.general_tab)
        self.voyage_number_edit.setEnabled(False)
        self.voyage_number_edit.setObjectName(_fromUtf8("voyage_number_edit"))
        self.gridLayout_10.addWidget(self.voyage_number_edit, 0, 5, 1, 1)
        self.label_37 = QtGui.QLabel(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_10.addWidget(self.label_37, 0, 6, 1, 1)
        self.captain_name_edit = QtGui.QLineEdit(self.general_tab)
        self.captain_name_edit.setEnabled(False)
        self.captain_name_edit.setObjectName(_fromUtf8("captain_name_edit"))
        self.gridLayout_10.addWidget(self.captain_name_edit, 0, 7, 1, 1)
        self.label_38 = QtGui.QLabel(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_10.addWidget(self.label_38, 0, 8, 1, 1)
        self.date_edit = QtGui.QLineEdit(self.general_tab)
        self.date_edit.setEnabled(False)
        self.date_edit.setObjectName(_fromUtf8("date_edit"))
        self.gridLayout_10.addWidget(self.date_edit, 0, 9, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.depart_date_edit = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depart_date_edit.sizePolicy().hasHeightForWidth())
        self.depart_date_edit.setSizePolicy(sizePolicy)
        self.depart_date_edit.setCalendarPopup(True)
        self.depart_date_edit.setObjectName(_fromUtf8("depart_date_edit"))
        self.gridLayout.addWidget(self.depart_date_edit, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.departure_port_combo = QtGui.QComboBox(self.groupBox)
        self.departure_port_combo.setObjectName(_fromUtf8("departure_port_combo"))
        self.gridLayout.addWidget(self.departure_port_combo, 1, 3, 1, 1)
        self.departure_country_combo = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_country_combo.sizePolicy().hasHeightForWidth())
        self.departure_country_combo.setSizePolicy(sizePolicy)
        self.departure_country_combo.setObjectName(_fromUtf8("departure_country_combo"))
        self.gridLayout.addWidget(self.departure_country_combo, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.departure_time_edit = QtGui.QTimeEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_time_edit.sizePolicy().hasHeightForWidth())
        self.departure_time_edit.setSizePolicy(sizePolicy)
        self.departure_time_edit.setCalendarPopup(True)
        self.departure_time_edit.setObjectName(_fromUtf8("departure_time_edit"))
        self.gridLayout.addWidget(self.departure_time_edit, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 2, 2, 1, 1)
        self.departure_terminal = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_terminal.sizePolicy().hasHeightForWidth())
        self.departure_terminal.setSizePolicy(sizePolicy)
        self.departure_terminal.setObjectName(_fromUtf8("departure_terminal"))
        self.gridLayout.addWidget(self.departure_terminal, 2, 3, 1, 1)
        self.depature_unlo_code = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depature_unlo_code.sizePolicy().hasHeightForWidth())
        self.depature_unlo_code.setSizePolicy(sizePolicy)
        self.depature_unlo_code.setObjectName(_fromUtf8("depature_unlo_code"))
        self.gridLayout.addWidget(self.depature_unlo_code, 2, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox, 1, 0, 1, 10)
        self.groupBox_2 = QtGui.QGroupBox(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 1, 2, 1, 1)
        self.arrival_country_combo = QtGui.QComboBox(self.groupBox_2)
        self.arrival_country_combo.setObjectName(_fromUtf8("arrival_country_combo"))
        self.gridLayout_2.addWidget(self.arrival_country_combo, 1, 1, 1, 1)
        self.arrival_port_combo = QtGui.QComboBox(self.groupBox_2)
        self.arrival_port_combo.setObjectName(_fromUtf8("arrival_port_combo"))
        self.gridLayout_2.addWidget(self.arrival_port_combo, 1, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.arrival_date_edit = QtGui.QDateEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_date_edit.sizePolicy().hasHeightForWidth())
        self.arrival_date_edit.setSizePolicy(sizePolicy)
        self.arrival_date_edit.setCalendarPopup(True)
        self.arrival_date_edit.setObjectName(_fromUtf8("arrival_date_edit"))
        self.gridLayout_2.addWidget(self.arrival_date_edit, 0, 1, 1, 1)
        self.arrival_time_edit = QtGui.QTimeEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_time_edit.sizePolicy().hasHeightForWidth())
        self.arrival_time_edit.setSizePolicy(sizePolicy)
        self.arrival_time_edit.setCalendarPopup(True)
        self.arrival_time_edit.setObjectName(_fromUtf8("arrival_time_edit"))
        self.gridLayout_2.addWidget(self.arrival_time_edit, 0, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 2, 0, 1, 1)
        self.arrival_unlo_code = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_unlo_code.sizePolicy().hasHeightForWidth())
        self.arrival_unlo_code.setSizePolicy(sizePolicy)
        self.arrival_unlo_code.setObjectName(_fromUtf8("arrival_unlo_code"))
        self.gridLayout_2.addWidget(self.arrival_unlo_code, 2, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 2, 2, 1, 1)
        self.arrival_terminal = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_terminal.sizePolicy().hasHeightForWidth())
        self.arrival_terminal.setSizePolicy(sizePolicy)
        self.arrival_terminal.setObjectName(_fromUtf8("arrival_terminal"))
        self.gridLayout_2.addWidget(self.arrival_terminal, 2, 3, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 2, 0, 1, 10)
        self.tabWidget.addTab(self.general_tab, _fromUtf8(""))
        self.paper_chart_tab = QtGui.QWidget()
        self.paper_chart_tab.setObjectName(_fromUtf8("paper_chart_tab"))
        self.groupBox_3 = QtGui.QGroupBox(self.paper_chart_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 885, 588))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.via_name_edit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_name_edit.sizePolicy().hasHeightForWidth())
        self.via_name_edit.setSizePolicy(sizePolicy)
        self.via_name_edit.setObjectName(_fromUtf8("via_name_edit"))
        self.verticalLayout_3.addWidget(self.via_name_edit)
        self.via_listWidget = QtGui.QListWidget(self.groupBox_5)
        self.via_listWidget.setObjectName(_fromUtf8("via_listWidget"))
        self.verticalLayout_3.addWidget(self.via_listWidget)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.via_add_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_add_btn.sizePolicy().hasHeightForWidth())
        self.via_add_btn.setSizePolicy(sizePolicy)
        self.via_add_btn.setObjectName(_fromUtf8("via_add_btn"))
        self.verticalLayout.addWidget(self.via_add_btn)
        self.via_remove_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_remove_btn.sizePolicy().hasHeightForWidth())
        self.via_remove_btn.setSizePolicy(sizePolicy)
        self.via_remove_btn.setObjectName(_fromUtf8("via_remove_btn"))
        self.verticalLayout.addWidget(self.via_remove_btn)
        self.via_up_btn = QtGui.QPushButton(self.groupBox_5)
        self.via_up_btn.setObjectName(_fromUtf8("via_up_btn"))
        self.verticalLayout.addWidget(self.via_up_btn)
        self.via_down_btn = QtGui.QPushButton(self.groupBox_5)
        self.via_down_btn.setObjectName(_fromUtf8("via_down_btn"))
        self.verticalLayout.addWidget(self.via_down_btn)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_8.addWidget(self.label_19)
        self.use_dw_route_yes_radio = QtGui.QRadioButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_dw_route_yes_radio.sizePolicy().hasHeightForWidth())
        self.use_dw_route_yes_radio.setSizePolicy(sizePolicy)
        self.use_dw_route_yes_radio.setObjectName(_fromUtf8("use_dw_route_yes_radio"))
        self.horizontalLayout_8.addWidget(self.use_dw_route_yes_radio)
        self.use_dw_route_no_radio = QtGui.QRadioButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_dw_route_no_radio.sizePolicy().hasHeightForWidth())
        self.use_dw_route_no_radio.setSizePolicy(sizePolicy)
        self.use_dw_route_no_radio.setObjectName(_fromUtf8("use_dw_route_no_radio"))
        self.horizontalLayout_8.addWidget(self.use_dw_route_no_radio)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_9.addWidget(self.label_20)
        self.critial_yes_radio = QtGui.QRadioButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.critial_yes_radio.sizePolicy().hasHeightForWidth())
        self.critial_yes_radio.setSizePolicy(sizePolicy)
        self.critial_yes_radio.setObjectName(_fromUtf8("critial_yes_radio"))
        self.horizontalLayout_9.addWidget(self.critial_yes_radio)
        self.critial_no_radio = QtGui.QRadioButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.critial_no_radio.sizePolicy().hasHeightForWidth())
        self.critial_no_radio.setSizePolicy(sizePolicy)
        self.critial_no_radio.setObjectName(_fromUtf8("critial_no_radio"))
        self.horizontalLayout_9.addWidget(self.critial_no_radio)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.scrollArea_4 = QtGui.QScrollArea(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 863, 210))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.point_table_widget = QtGui.QTableWidget(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.point_table_widget.sizePolicy().hasHeightForWidth())
        self.point_table_widget.setSizePolicy(sizePolicy)
        self.point_table_widget.setObjectName(_fromUtf8("point_table_widget"))
        self.point_table_widget.setColumnCount(0)
        self.point_table_widget.setRowCount(0)
        self.gridLayout_7.addWidget(self.point_table_widget, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.addWidget(self.scrollArea_4, 5, 0, 1, 2)
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout.addWidget(self.label_21)
        self.gridLayout_3.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea_3 = QtGui.QScrollArea(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(0, 91))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 393, 218))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.critial_point_table_widget = QtGui.QTableWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.critial_point_table_widget.sizePolicy().hasHeightForWidth())
        self.critial_point_table_widget.setSizePolicy(sizePolicy)
        self.critial_point_table_widget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.critial_point_table_widget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.critial_point_table_widget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.critial_point_table_widget.setShowGrid(True)
        self.critial_point_table_widget.setObjectName(_fromUtf8("critial_point_table_widget"))
        self.critial_point_table_widget.setColumnCount(3)
        self.critial_point_table_widget.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.critial_point_table_widget.setHorizontalHeaderItem(2, item)
        self.critial_point_table_widget.horizontalHeader().setCascadingSectionResizes(True)
        self.critial_point_table_widget.horizontalHeader().setStretchLastSection(True)
        self.critial_point_table_widget.verticalHeader().setVisible(False)
        self.critial_point_table_widget.verticalHeader().setCascadingSectionResizes(True)
        self.critial_point_table_widget.verticalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.critial_point_table_widget, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.critial_point_add_btn = QtGui.QPushButton(self.groupBox_4)
        self.critial_point_add_btn.setObjectName(_fromUtf8("critial_point_add_btn"))
        self.verticalLayout_2.addWidget(self.critial_point_add_btn)
        self.critial_point_delete_btn = QtGui.QPushButton(self.groupBox_4)
        self.critial_point_delete_btn.setObjectName(_fromUtf8("critial_point_delete_btn"))
        self.verticalLayout_2.addWidget(self.critial_point_delete_btn)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.label_22.raise_()
        self.scrollArea_4.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        self.tabWidget.addTab(self.paper_chart_tab, _fromUtf8(""))
        self.voyage_data_tab = QtGui.QWidget()
        self.voyage_data_tab.setObjectName(_fromUtf8("voyage_data_tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.voyage_data_tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.voyageDataGroupBox = QtGui.QGroupBox(self.voyage_data_tab)
        self.voyageDataGroupBox.setObjectName(_fromUtf8("voyageDataGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.voyageDataGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_28 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_13.addWidget(self.label_28)
        self.maximum_draft_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximum_draft_edit.sizePolicy().hasHeightForWidth())
        self.maximum_draft_edit.setSizePolicy(sizePolicy)
        self.maximum_draft_edit.setObjectName(_fromUtf8("maximum_draft_edit"))
        self.horizontalLayout_13.addWidget(self.maximum_draft_edit)
        self.label_29 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_13.addWidget(self.label_29)
        self.minimum_ukc_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimum_ukc_edit.sizePolicy().hasHeightForWidth())
        self.minimum_ukc_edit.setSizePolicy(sizePolicy)
        self.minimum_ukc_edit.setObjectName(_fromUtf8("minimum_ukc_edit"))
        self.horizontalLayout_13.addWidget(self.minimum_ukc_edit)
        self.label_30 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_13.addWidget(self.label_30)
        self.comboBox_4 = QtGui.QComboBox(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.comboBox_4)
        self.label_31 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_13.addWidget(self.label_31)
        self.displacement_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displacement_edit.sizePolicy().hasHeightForWidth())
        self.displacement_edit.setSizePolicy(sizePolicy)
        self.displacement_edit.setObjectName(_fromUtf8("displacement_edit"))
        self.horizontalLayout_13.addWidget(self.displacement_edit)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_27 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_12.addWidget(self.label_27)
        self.cargo_shipped = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cargo_shipped.sizePolicy().hasHeightForWidth())
        self.cargo_shipped.setSizePolicy(sizePolicy)
        self.cargo_shipped.setObjectName(_fromUtf8("cargo_shipped"))
        self.horizontalLayout_12.addWidget(self.cargo_shipped)
        self.label_24 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_12.addWidget(self.label_24)
        self.total_distance_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_distance_edit.sizePolicy().hasHeightForWidth())
        self.total_distance_edit.setSizePolicy(sizePolicy)
        self.total_distance_edit.setObjectName(_fromUtf8("total_distance_edit"))
        self.horizontalLayout_12.addWidget(self.total_distance_edit)
        self.label_25 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(120, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_12.addWidget(self.label_25)
        self.total_streaming_time_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_streaming_time_edit.sizePolicy().hasHeightForWidth())
        self.total_streaming_time_edit.setSizePolicy(sizePolicy)
        self.total_streaming_time_edit.setObjectName(_fromUtf8("total_streaming_time_edit"))
        self.horizontalLayout_12.addWidget(self.total_streaming_time_edit)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_33 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_4.addWidget(self.label_33)
        self.distance_me_revolution_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distance_me_revolution_edit.sizePolicy().hasHeightForWidth())
        self.distance_me_revolution_edit.setSizePolicy(sizePolicy)
        self.distance_me_revolution_edit.setObjectName(_fromUtf8("distance_me_revolution_edit"))
        self.horizontalLayout_4.addWidget(self.distance_me_revolution_edit)
        self.label_34 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_4.addWidget(self.label_34)
        self.average_me_rmp_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_me_rmp_edit.sizePolicy().hasHeightForWidth())
        self.average_me_rmp_edit.setSizePolicy(sizePolicy)
        self.average_me_rmp_edit.setObjectName(_fromUtf8("average_me_rmp_edit"))
        self.horizontalLayout_4.addWidget(self.average_me_rmp_edit)
        self.label_26 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_4.addWidget(self.label_26)
        self.average_speed_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_speed_edit.sizePolicy().hasHeightForWidth())
        self.average_speed_edit.setSizePolicy(sizePolicy)
        self.average_speed_edit.setObjectName(_fromUtf8("average_speed_edit"))
        self.horizontalLayout_4.addWidget(self.average_speed_edit)
        self.pushButton_3 = QtGui.QPushButton(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_32 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_3.addWidget(self.label_32)
        self.average_slip_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_slip_edit.sizePolicy().hasHeightForWidth())
        self.average_slip_edit.setSizePolicy(sizePolicy)
        self.average_slip_edit.setObjectName(_fromUtf8("average_slip_edit"))
        self.horizontalLayout_3.addWidget(self.average_slip_edit)
        self.calculate_btn = QtGui.QPushButton(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate_btn.sizePolicy().hasHeightForWidth())
        self.calculate_btn.setSizePolicy(sizePolicy)
        self.calculate_btn.setObjectName(_fromUtf8("calculate_btn"))
        self.horizontalLayout_3.addWidget(self.calculate_btn)
        self.label_39 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setMinimumSize(QtCore.QSize(120, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_3.addWidget(self.label_39)
        self.total_streaming_time_edit_2 = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_streaming_time_edit_2.sizePolicy().hasHeightForWidth())
        self.total_streaming_time_edit_2.setSizePolicy(sizePolicy)
        self.total_streaming_time_edit_2.setObjectName(_fromUtf8("total_streaming_time_edit_2"))
        self.horizontalLayout_3.addWidget(self.total_streaming_time_edit_2)
        self.label_40 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_3.addWidget(self.label_40)
        self.average_speed_edit_2 = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_speed_edit_2.sizePolicy().hasHeightForWidth())
        self.average_speed_edit_2.setSizePolicy(sizePolicy)
        self.average_speed_edit_2.setObjectName(_fromUtf8("average_speed_edit_2"))
        self.horizontalLayout_3.addWidget(self.average_speed_edit_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 192))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.tableWidget, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_35 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_5.addWidget(self.label_35)
        self.attach_ecdis_route_file_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.attach_ecdis_route_file_edit.setObjectName(_fromUtf8("attach_ecdis_route_file_edit"))
        self.horizontalLayout_5.addWidget(self.attach_ecdis_route_file_edit)
        self.attach_ecdis_browse_btn = QtGui.QPushButton(self.voyageDataGroupBox)
        self.attach_ecdis_browse_btn.setObjectName(_fromUtf8("attach_ecdis_browse_btn"))
        self.horizontalLayout_5.addWidget(self.attach_ecdis_browse_btn)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_36 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_6.addWidget(self.label_36)
        self.attach_wp_plan_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.attach_wp_plan_edit.setObjectName(_fromUtf8("attach_wp_plan_edit"))
        self.horizontalLayout_6.addWidget(self.attach_wp_plan_edit)
        self.attach_wp_plan_browse_btn = QtGui.QPushButton(self.voyageDataGroupBox)
        self.attach_wp_plan_browse_btn.setObjectName(_fromUtf8("attach_wp_plan_browse_btn"))
        self.horizontalLayout_6.addWidget(self.attach_wp_plan_browse_btn)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.gridLayout_9.addWidget(self.voyageDataGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.voyage_data_tab, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Load Route", None))
        self.load_btn.setText(_translate("Form", "Load", None))
        self.submit_btn.setText(_translate("Form", "Submit", None))
        self.cancel_btn.setText(_translate("Form", "Cancel", None))
        self.label_5.setText(_translate("Form", "Ship Name", None))
        self.label_18.setText(_translate("Form", "Call Sign", None))
        self.label_23.setText(_translate("Form", "Voyage Number", None))
        self.label_37.setText(_translate("Form", "Captain Name", None))
        self.label_38.setText(_translate("Form", "Date", None))
        self.groupBox.setTitle(_translate("Form", "Departure", None))
        self.label_11.setText(_translate("Form", "Departure Port", None))
        self.label_6.setText(_translate("Form", "Departure Date", None))
        self.label_10.setText(_translate("Form", "Departure Country", None))
        self.label_7.setText(_translate("Form", "Departure Time", None))
        self.label_12.setText(_translate("Form", "UNLO Code", None))
        self.label_13.setText(_translate("Form", "Terminal", None))
        self.groupBox_2.setTitle(_translate("Form", "Arrival", None))
        self.label_15.setText(_translate("Form", "Arrival Port", None))
        self.label_14.setText(_translate("Form", "Arrival Country", None))
        self.label_8.setText(_translate("Form", "Arrival Time     ", None))
        self.label_9.setText(_translate("Form", "Arrival Time  ", None))
        self.label_16.setText(_translate("Form", "UNLO Code", None))
        self.label_17.setText(_translate("Form", "Terminal", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general_tab), _translate("Form", "General", None))
        self.groupBox_3.setTitle(_translate("Form", "Paper Chart", None))
        self.groupBox_5.setTitle(_translate("Form", "Via", None))
        self.via_add_btn.setText(_translate("Form", "Add", None))
        self.via_remove_btn.setText(_translate("Form", "Remove", None))
        self.via_up_btn.setText(_translate("Form", "Up", None))
        self.via_down_btn.setText(_translate("Form", "Down", None))
        self.label_19.setText(_translate("Form", "Use DW route when passing channel or TSS if appilicable?", None))
        self.use_dw_route_yes_radio.setText(_translate("Form", "Yes", None))
        self.use_dw_route_no_radio.setText(_translate("Form", "No", None))
        self.label_20.setText(_translate("Form", "Is there any critial point that request to pay special attention to?", None))
        self.critial_yes_radio.setText(_translate("Form", "Yes", None))
        self.critial_no_radio.setText(_translate("Form", "No", None))
        self.label_22.setText(_translate("Form", "If it is necessery to waitting for high tide or reduce speed to passing critial point,  please click the button on the right of the point.", None))
        self.label.setText(_translate("Form", "This route\'s ID number in the world e-route cloud system is ", None))
        self.label_2.setText(_translate("Form", "TextLabel", None))
        self.label_3.setText(_translate("Form", "It has been used for", None))
        self.label_4.setText(_translate("Form", "TextLabel", None))
        self.label_21.setText(_translate("Form", "times by other ships successfully", None))
        self.groupBox_4.setTitle(_translate("Form", "Critial Point", None))
        item = self.critial_point_table_widget.verticalHeaderItem(0)
        item.setText(_translate("Form", "新建行", None))
        item = self.critial_point_table_widget.verticalHeaderItem(1)
        item.setText(_translate("Form", "新建行", None))
        item = self.critial_point_table_widget.verticalHeaderItem(2)
        item.setText(_translate("Form", "新建行", None))
        item = self.critial_point_table_widget.verticalHeaderItem(3)
        item.setText(_translate("Form", "新建行", None))
        item = self.critial_point_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Latitude", None))
        item = self.critial_point_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Longtitude", None))
        item = self.critial_point_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Selected", None))
        self.critial_point_add_btn.setText(_translate("Form", "Add", None))
        self.critial_point_delete_btn.setText(_translate("Form", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.paper_chart_tab), _translate("Form", "Paper Chart", None))
        self.voyageDataGroupBox.setTitle(_translate("Form", "Voyage Data", None))
        self.label_28.setText(_translate("Form", "Maximum Draft", None))
        self.label_29.setText(_translate("Form", "Minimum UKC", None))
        self.label_30.setText(_translate("Form", "Load Condition", None))
        self.comboBox_4.setItemText(0, _translate("Form", "Ballast", None))
        self.comboBox_4.setItemText(1, _translate("Form", "Loaded", None))
        self.label_31.setText(_translate("Form", "Displacement", None))
        self.label_27.setText(_translate("Form", "Cargo Shipped", None))
        self.label_24.setText(_translate("Form", "Total Distance", None))
        self.label_25.setText(_translate("Form", "Total Streaming Time", None))
        self.label_33.setText(_translate("Form", "Distance By M/E Revolution", None))
        self.label_34.setText(_translate("Form", "Average M/E RMP", None))
        self.label_26.setText(_translate("Form", "Average Speed", None))
        self.pushButton_3.setText(_translate("Form", "Calculate", None))
        self.label_32.setText(_translate("Form", "Average Slip", None))
        self.calculate_btn.setText(_translate("Form", "Calculate", None))
        self.label_39.setText(_translate("Form", "Total Streaming Time", None))
        self.label_40.setText(_translate("Form", "Average Speed", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Total Bunker Consumption", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Average Bunker Consumption per NM", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "IFO", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "MDO", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "LSFO", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "LSMDO", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_35.setText(_translate("Form", "Save ECDIS Route File", None))
        self.attach_ecdis_browse_btn.setText(_translate("Form", "Browse", None))
        self.label_36.setText(_translate("Form", "Save E-marine WP Plan", None))
        self.attach_wp_plan_browse_btn.setText(_translate("Form", "Browse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voyage_data_tab), _translate("Form", "Voyage Data", None))

