# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadRoute.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(871, 674)
        Form.setAutoFillBackground(True)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_11 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.general_tab = QtGui.QWidget()
        self.general_tab.setObjectName(_fromUtf8("general_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.general_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_2 = QtGui.QLabel(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_9.addWidget(self.label_2)
        self.load_route_path_edit = QtGui.QLineEdit(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_route_path_edit.sizePolicy().hasHeightForWidth())
        self.load_route_path_edit.setSizePolicy(sizePolicy)
        self.load_route_path_edit.setObjectName(_fromUtf8("load_route_path_edit"))
        self.horizontalLayout_9.addWidget(self.load_route_path_edit)
        self.load_route_file_btn = QtGui.QPushButton(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_route_file_btn.sizePolicy().hasHeightForWidth())
        self.load_route_file_btn.setSizePolicy(sizePolicy)
        self.load_route_file_btn.setObjectName(_fromUtf8("load_route_file_btn"))
        self.horizontalLayout_9.addWidget(self.load_route_file_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.groupBox_2 = QtGui.QGroupBox(self.general_tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.depart_date_edit = QtGui.QDateEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depart_date_edit.sizePolicy().hasHeightForWidth())
        self.depart_date_edit.setSizePolicy(sizePolicy)
        self.depart_date_edit.setCalendarPopup(True)
        self.depart_date_edit.setObjectName(_fromUtf8("depart_date_edit"))
        self.gridLayout.addWidget(self.depart_date_edit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.departure_time_edit = QtGui.QTimeEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_time_edit.sizePolicy().hasHeightForWidth())
        self.departure_time_edit.setSizePolicy(sizePolicy)
        self.departure_time_edit.setCalendarPopup(True)
        self.departure_time_edit.setObjectName(_fromUtf8("departure_time_edit"))
        self.gridLayout.addWidget(self.departure_time_edit, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 4, 1, 1)
        self.departure_unlo_edit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_unlo_edit.sizePolicy().hasHeightForWidth())
        self.departure_unlo_edit.setSizePolicy(sizePolicy)
        self.departure_unlo_edit.setObjectName(_fromUtf8("departure_unlo_edit"))
        self.gridLayout.addWidget(self.departure_unlo_edit, 0, 5, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 6, 1, 1)
        self.depature_terminal = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depature_terminal.sizePolicy().hasHeightForWidth())
        self.depature_terminal.setSizePolicy(sizePolicy)
        self.depature_terminal.setObjectName(_fromUtf8("depature_terminal"))
        self.gridLayout.addWidget(self.depature_terminal, 0, 7, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.departure_country_combo = QtGui.QComboBox(self.groupBox_2)
        self.departure_country_combo.setEditable(True)
        self.departure_country_combo.setMaxVisibleItems(15)
        self.departure_country_combo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.departure_country_combo.setObjectName(_fromUtf8("departure_country_combo"))
        self.gridLayout.addWidget(self.departure_country_combo, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.departure_port_combo = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departure_port_combo.sizePolicy().hasHeightForWidth())
        self.departure_port_combo.setSizePolicy(sizePolicy)
        self.departure_port_combo.setEditable(True)
        self.departure_port_combo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.departure_port_combo.setObjectName(_fromUtf8("departure_port_combo"))
        self.gridLayout.addWidget(self.departure_port_combo, 1, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_7 = QtGui.QGroupBox(self.general_tab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 1, 2, 1, 1)
        self.arrival_country_combo = QtGui.QComboBox(self.groupBox_7)
        self.arrival_country_combo.setEditable(True)
        self.arrival_country_combo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.arrival_country_combo.setObjectName(_fromUtf8("arrival_country_combo"))
        self.gridLayout_2.addWidget(self.arrival_country_combo, 1, 1, 1, 1)
        self.arrival_port_combo = QtGui.QComboBox(self.groupBox_7)
        self.arrival_port_combo.setEditable(True)
        self.arrival_port_combo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.arrival_port_combo.setObjectName(_fromUtf8("arrival_port_combo"))
        self.gridLayout_2.addWidget(self.arrival_port_combo, 1, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.arrival_date_edit = QtGui.QDateEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_date_edit.sizePolicy().hasHeightForWidth())
        self.arrival_date_edit.setSizePolicy(sizePolicy)
        self.arrival_date_edit.setCalendarPopup(True)
        self.arrival_date_edit.setObjectName(_fromUtf8("arrival_date_edit"))
        self.gridLayout_2.addWidget(self.arrival_date_edit, 0, 1, 1, 1)
        self.arrival_time_edit = QtGui.QTimeEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_time_edit.sizePolicy().hasHeightForWidth())
        self.arrival_time_edit.setSizePolicy(sizePolicy)
        self.arrival_time_edit.setCalendarPopup(True)
        self.arrival_time_edit.setObjectName(_fromUtf8("arrival_time_edit"))
        self.gridLayout_2.addWidget(self.arrival_time_edit, 0, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 4, 1, 1)
        self.arrival_unlo_edit = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_unlo_edit.sizePolicy().hasHeightForWidth())
        self.arrival_unlo_edit.setSizePolicy(sizePolicy)
        self.arrival_unlo_edit.setObjectName(_fromUtf8("arrival_unlo_edit"))
        self.gridLayout_2.addWidget(self.arrival_unlo_edit, 0, 5, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 6, 1, 1)
        self.arrival_terminal = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrival_terminal.sizePolicy().hasHeightForWidth())
        self.arrival_terminal.setSizePolicy(sizePolicy)
        self.arrival_terminal.setObjectName(_fromUtf8("arrival_terminal"))
        self.gridLayout_2.addWidget(self.arrival_terminal, 0, 7, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_19 = QtGui.QLabel(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_17.addWidget(self.label_19)
        self.use_dw_route_yes_radio = QtGui.QRadioButton(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_dw_route_yes_radio.sizePolicy().hasHeightForWidth())
        self.use_dw_route_yes_radio.setSizePolicy(sizePolicy)
        self.use_dw_route_yes_radio.setObjectName(_fromUtf8("use_dw_route_yes_radio"))
        self.horizontalLayout_17.addWidget(self.use_dw_route_yes_radio)
        self.use_dw_route_no_radio = QtGui.QRadioButton(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_dw_route_no_radio.sizePolicy().hasHeightForWidth())
        self.use_dw_route_no_radio.setSizePolicy(sizePolicy)
        self.use_dw_route_no_radio.setObjectName(_fromUtf8("use_dw_route_no_radio"))
        self.horizontalLayout_17.addWidget(self.use_dw_route_no_radio)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_20 = QtGui.QLabel(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_18.addWidget(self.label_20)
        self.critial_yes_radio = QtGui.QRadioButton(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.critial_yes_radio.sizePolicy().hasHeightForWidth())
        self.critial_yes_radio.setSizePolicy(sizePolicy)
        self.critial_yes_radio.setObjectName(_fromUtf8("critial_yes_radio"))
        self.horizontalLayout_18.addWidget(self.critial_yes_radio)
        self.critial_no_radio = QtGui.QRadioButton(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.critial_no_radio.sizePolicy().hasHeightForWidth())
        self.critial_no_radio.setSizePolicy(sizePolicy)
        self.critial_no_radio.setObjectName(_fromUtf8("critial_no_radio"))
        self.horizontalLayout_18.addWidget(self.critial_no_radio)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.groupBox_4 = QtGui.QGroupBox(self.general_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea_3 = QtGui.QScrollArea(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(0, 91))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 724, 301))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tableWidget_2 = QtGui.QTableWidget(self.scrollAreaWidgetContents_3)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(7)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.critial_point_add_btn = QtGui.QPushButton(self.groupBox_4)
        self.critial_point_add_btn.setObjectName(_fromUtf8("critial_point_add_btn"))
        self.verticalLayout_2.addWidget(self.critial_point_add_btn)
        self.critial_point_delete_btn = QtGui.QPushButton(self.groupBox_4)
        self.critial_point_delete_btn.setObjectName(_fromUtf8("critial_point_delete_btn"))
        self.verticalLayout_2.addWidget(self.critial_point_delete_btn)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.general_tab, _fromUtf8(""))
        self.paper_chart_tab = QtGui.QWidget()
        self.paper_chart_tab.setObjectName(_fromUtf8("paper_chart_tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.paper_chart_tab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_3 = QtGui.QGroupBox(self.paper_chart_tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.via_name_edit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_name_edit.sizePolicy().hasHeightForWidth())
        self.via_name_edit.setSizePolicy(sizePolicy)
        self.via_name_edit.setObjectName(_fromUtf8("via_name_edit"))
        self.verticalLayout_3.addWidget(self.via_name_edit)
        self.via_listWidget = QtGui.QListWidget(self.groupBox_5)
        self.via_listWidget.setObjectName(_fromUtf8("via_listWidget"))
        self.verticalLayout_3.addWidget(self.via_listWidget)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.via_add_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_add_btn.sizePolicy().hasHeightForWidth())
        self.via_add_btn.setSizePolicy(sizePolicy)
        self.via_add_btn.setObjectName(_fromUtf8("via_add_btn"))
        self.verticalLayout.addWidget(self.via_add_btn)
        self.via_remove_btn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.via_remove_btn.sizePolicy().hasHeightForWidth())
        self.via_remove_btn.setSizePolicy(sizePolicy)
        self.via_remove_btn.setObjectName(_fromUtf8("via_remove_btn"))
        self.verticalLayout.addWidget(self.via_remove_btn)
        self.via_up_btn = QtGui.QPushButton(self.groupBox_5)
        self.via_up_btn.setObjectName(_fromUtf8("via_up_btn"))
        self.verticalLayout.addWidget(self.via_up_btn)
        self.via_down_btn = QtGui.QPushButton(self.groupBox_5)
        self.via_down_btn.setObjectName(_fromUtf8("via_down_btn"))
        self.verticalLayout.addWidget(self.via_down_btn)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.route_id_number_label = QtGui.QLabel(self.groupBox_3)
        self.route_id_number_label.setObjectName(_fromUtf8("route_id_number_label"))
        self.horizontalLayout.addWidget(self.route_id_number_label)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.used_times_label = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.used_times_label.sizePolicy().hasHeightForWidth())
        self.used_times_label.setSizePolicy(sizePolicy)
        self.used_times_label.setObjectName(_fromUtf8("used_times_label"))
        self.horizontalLayout_8.addWidget(self.used_times_label)
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_8.addWidget(self.label_21)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.scrollArea_4 = QtGui.QScrollArea(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 807, 210))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.point_table_widget = QtGui.QTableWidget(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.point_table_widget.sizePolicy().hasHeightForWidth())
        self.point_table_widget.setSizePolicy(sizePolicy)
        self.point_table_widget.setObjectName(_fromUtf8("point_table_widget"))
        self.point_table_widget.setColumnCount(0)
        self.point_table_widget.setRowCount(0)
        self.gridLayout_7.addWidget(self.point_table_widget, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_7.addWidget(self.scrollArea_4)
        self.scrollArea_4.raise_()
        self.groupBox_5.raise_()
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.paper_chart_tab, _fromUtf8(""))
        self.voyage_data_tab = QtGui.QWidget()
        self.voyage_data_tab.setObjectName(_fromUtf8("voyage_data_tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.voyage_data_tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.voyageDataGroupBox = QtGui.QGroupBox(self.voyage_data_tab)
        self.voyageDataGroupBox.setObjectName(_fromUtf8("voyageDataGroupBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.voyageDataGroupBox)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_6 = QtGui.QGroupBox(self.voyageDataGroupBox)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_28 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_3.addWidget(self.label_28)
        self.minimum_ukc_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimum_ukc_edit.sizePolicy().hasHeightForWidth())
        self.minimum_ukc_edit.setSizePolicy(sizePolicy)
        self.minimum_ukc_edit.setObjectName(_fromUtf8("minimum_ukc_edit"))
        self.horizontalLayout_3.addWidget(self.minimum_ukc_edit)
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_3.addWidget(self.label_29)
        self.maximum_draft_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximum_draft_edit.sizePolicy().hasHeightForWidth())
        self.maximum_draft_edit.setSizePolicy(sizePolicy)
        self.maximum_draft_edit.setObjectName(_fromUtf8("maximum_draft_edit"))
        self.horizontalLayout_3.addWidget(self.maximum_draft_edit)
        self.label_30 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_3.addWidget(self.label_30)
        self.load_condition_combo = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_condition_combo.sizePolicy().hasHeightForWidth())
        self.load_condition_combo.setSizePolicy(sizePolicy)
        self.load_condition_combo.setObjectName(_fromUtf8("load_condition_combo"))
        self.load_condition_combo.addItem(_fromUtf8(""))
        self.load_condition_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.load_condition_combo)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_31 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_4.addWidget(self.label_31)
        self.displacement_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displacement_edit.sizePolicy().hasHeightForWidth())
        self.displacement_edit.setSizePolicy(sizePolicy)
        self.displacement_edit.setObjectName(_fromUtf8("displacement_edit"))
        self.horizontalLayout_4.addWidget(self.displacement_edit)
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_4.addWidget(self.label_27)
        self.cargo_shipped = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cargo_shipped.sizePolicy().hasHeightForWidth())
        self.cargo_shipped.setSizePolicy(sizePolicy)
        self.cargo_shipped.setObjectName(_fromUtf8("cargo_shipped"))
        self.horizontalLayout_4.addWidget(self.cargo_shipped)
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_4.addWidget(self.label_24)
        self.total_distance_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_distance_edit.sizePolicy().hasHeightForWidth())
        self.total_distance_edit.setSizePolicy(sizePolicy)
        self.total_distance_edit.setObjectName(_fromUtf8("total_distance_edit"))
        self.horizontalLayout_4.addWidget(self.total_distance_edit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_25 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(120, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_7.addWidget(self.label_25)
        self.total_streaming_time_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_streaming_time_edit.sizePolicy().hasHeightForWidth())
        self.total_streaming_time_edit.setSizePolicy(sizePolicy)
        self.total_streaming_time_edit.setObjectName(_fromUtf8("total_streaming_time_edit"))
        self.horizontalLayout_7.addWidget(self.total_streaming_time_edit)
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_7.addWidget(self.label_26)
        self.log_distance_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_distance_edit.sizePolicy().hasHeightForWidth())
        self.log_distance_edit.setSizePolicy(sizePolicy)
        self.log_distance_edit.setObjectName(_fromUtf8("log_distance_edit"))
        self.horizontalLayout_7.addWidget(self.log_distance_edit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_33 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_10.addWidget(self.label_33)
        self.distance_me_revolution_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distance_me_revolution_edit.sizePolicy().hasHeightForWidth())
        self.distance_me_revolution_edit.setSizePolicy(sizePolicy)
        self.distance_me_revolution_edit.setObjectName(_fromUtf8("distance_me_revolution_edit"))
        self.horizontalLayout_10.addWidget(self.distance_me_revolution_edit)
        self.label_34 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_10.addWidget(self.label_34)
        self.average_me_rmp_edit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_me_rmp_edit.sizePolicy().hasHeightForWidth())
        self.average_me_rmp_edit.setSizePolicy(sizePolicy)
        self.average_me_rmp_edit.setObjectName(_fromUtf8("average_me_rmp_edit"))
        self.horizontalLayout_10.addWidget(self.average_me_rmp_edit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_32 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_11.addWidget(self.label_32)
        self.average_slip_edit = QtGui.QLineEdit(self.groupBox_6)
        self.average_slip_edit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_slip_edit.sizePolicy().hasHeightForWidth())
        self.average_slip_edit.setSizePolicy(sizePolicy)
        self.average_slip_edit.setObjectName(_fromUtf8("average_slip_edit"))
        self.horizontalLayout_11.addWidget(self.average_slip_edit)
        self.label_40 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_11.addWidget(self.label_40)
        self.average_speed_edit_2 = QtGui.QLineEdit(self.groupBox_6)
        self.average_speed_edit_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_speed_edit_2.sizePolicy().hasHeightForWidth())
        self.average_speed_edit_2.setSizePolicy(sizePolicy)
        self.average_speed_edit_2.setObjectName(_fromUtf8("average_speed_edit_2"))
        self.horizontalLayout_11.addWidget(self.average_speed_edit_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        self.tableWidget = QtGui.QTableWidget(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 192))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.tableWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_35 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_5.addWidget(self.label_35)
        self.attach_ecdis_route_file_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attach_ecdis_route_file_edit.sizePolicy().hasHeightForWidth())
        self.attach_ecdis_route_file_edit.setSizePolicy(sizePolicy)
        self.attach_ecdis_route_file_edit.setObjectName(_fromUtf8("attach_ecdis_route_file_edit"))
        self.horizontalLayout_5.addWidget(self.attach_ecdis_route_file_edit)
        self.attach_ecdis_browse_btn = QtGui.QPushButton(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attach_ecdis_browse_btn.sizePolicy().hasHeightForWidth())
        self.attach_ecdis_browse_btn.setSizePolicy(sizePolicy)
        self.attach_ecdis_browse_btn.setObjectName(_fromUtf8("attach_ecdis_browse_btn"))
        self.horizontalLayout_5.addWidget(self.attach_ecdis_browse_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_36 = QtGui.QLabel(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_6.addWidget(self.label_36)
        self.attach_wp_plan_edit = QtGui.QLineEdit(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attach_wp_plan_edit.sizePolicy().hasHeightForWidth())
        self.attach_wp_plan_edit.setSizePolicy(sizePolicy)
        self.attach_wp_plan_edit.setObjectName(_fromUtf8("attach_wp_plan_edit"))
        self.horizontalLayout_6.addWidget(self.attach_wp_plan_edit)
        self.attach_wp_plan_browse_btn = QtGui.QPushButton(self.voyageDataGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attach_wp_plan_browse_btn.sizePolicy().hasHeightForWidth())
        self.attach_wp_plan_browse_btn.setSizePolicy(sizePolicy)
        self.attach_wp_plan_browse_btn.setObjectName(_fromUtf8("attach_wp_plan_browse_btn"))
        self.horizontalLayout_6.addWidget(self.attach_wp_plan_browse_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.gridLayout_9.addWidget(self.voyageDataGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.voyage_data_tab, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.submit_btn = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_btn.sizePolicy().hasHeightForWidth())
        self.submit_btn.setSizePolicy(sizePolicy)
        self.submit_btn.setObjectName(_fromUtf8("submit_btn"))
        self.horizontalLayout_2.addWidget(self.submit_btn)
        self.cancel_btn = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_btn.sizePolicy().hasHeightForWidth())
        self.cancel_btn.setSizePolicy(sizePolicy)
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Load Route", None))
        self.label_2.setText(_translate("Form", "Route File Path", None))
        self.load_route_file_btn.setText(_translate("Form", "Load Route File", None))
        self.groupBox_2.setTitle(_translate("Form", "Departure", None))
        self.label_6.setText(_translate("Form", "Departure Date", None))
        self.label_7.setText(_translate("Form", "Departure Time", None))
        self.label_12.setText(_translate("Form", "UNLO Code", None))
        self.label_13.setText(_translate("Form", "Terminal", None))
        self.label_10.setText(_translate("Form", "Departure Country", None))
        self.label_11.setText(_translate("Form", "Departure Port", None))
        self.groupBox_7.setTitle(_translate("Form", "Arrival", None))
        self.label_15.setText(_translate("Form", "Arrival Port", None))
        self.label_14.setText(_translate("Form", "Arrival Country", None))
        self.label_8.setText(_translate("Form", "Arrival Time     ", None))
        self.label_9.setText(_translate("Form", "Arrival Time  ", None))
        self.label_16.setText(_translate("Form", "UNLO Code", None))
        self.label_17.setText(_translate("Form", "Terminal", None))
        self.label_19.setText(_translate("Form", "Use DW route when passing channel or TSS if appilicable?", None))
        self.use_dw_route_yes_radio.setText(_translate("Form", "Yes", None))
        self.use_dw_route_no_radio.setText(_translate("Form", "No", None))
        self.label_20.setText(_translate("Form", "Is there any critial point that request to pay special attention to?", None))
        self.critial_yes_radio.setText(_translate("Form", "Yes", None))
        self.critial_no_radio.setText(_translate("Form", "No", None))
        self.groupBox_4.setTitle(_translate("Form", "Critial Point", None))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "新建行", None))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "新建行", None))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "新建行", None))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "新建行", None))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "新建行", None))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "新建行", None))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "新建行", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Latitude", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Longtitude", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Included?", None))
        self.critial_point_add_btn.setText(_translate("Form", "Add", None))
        self.critial_point_delete_btn.setText(_translate("Form", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general_tab), _translate("Form", "General", None))
        self.groupBox_3.setTitle(_translate("Form", "Paper Chart", None))
        self.groupBox_5.setTitle(_translate("Form", "Via", None))
        self.via_add_btn.setText(_translate("Form", "Add", None))
        self.via_remove_btn.setText(_translate("Form", "Remove", None))
        self.via_up_btn.setText(_translate("Form", "Up", None))
        self.via_down_btn.setText(_translate("Form", "Down", None))
        self.label.setText(_translate("Form", "This route\'s ID number in the world e-route cloud system is ", None))
        self.route_id_number_label.setText(_translate("Form", "TextLabel", None))
        self.label_3.setText(_translate("Form", "It has been used for", None))
        self.used_times_label.setText(_translate("Form", "TextLabel", None))
        self.label_21.setText(_translate("Form", "times by other ships successfully", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.paper_chart_tab), _translate("Form", "Paper Chart", None))
        self.voyageDataGroupBox.setTitle(_translate("Form", "Voyage Data", None))
        self.groupBox_6.setTitle(_translate("Form", "Calculate", None))
        self.label_28.setText(_translate("Form", "Maximum Draft", None))
        self.label_29.setText(_translate("Form", "Minimum UKC", None))
        self.label_30.setText(_translate("Form", "Load Condition", None))
        self.load_condition_combo.setItemText(0, _translate("Form", "Ballast", None))
        self.load_condition_combo.setItemText(1, _translate("Form", "Loaded", None))
        self.label_31.setText(_translate("Form", "Displacement", None))
        self.label_27.setText(_translate("Form", "Cargo Carried (Tone)", None))
        self.label_24.setText(_translate("Form", "Total Distance Over Ground", None))
        self.label_25.setText(_translate("Form", "Total Streaming Time", None))
        self.label_26.setText(_translate("Form", "Log Distance", None))
        self.label_33.setText(_translate("Form", "Distance By M/E Revolution", None))
        self.label_34.setText(_translate("Form", "Average M/E RMP", None))
        self.label_32.setText(_translate("Form", "Average Slip", None))
        self.label_40.setText(_translate("Form", "Average Speed", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Total Bunker Consumption", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Average Bunker Consumption per NM", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Voyage Performance Efficiency", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "IFO", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "MDO", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "LSFO", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "LSMDO", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_35.setText(_translate("Form", "Save ECDIS Route File", None))
        self.attach_ecdis_browse_btn.setText(_translate("Form", "Browse", None))
        self.label_36.setText(_translate("Form", "Save E-marine WP Plan", None))
        self.attach_wp_plan_browse_btn.setText(_translate("Form", "Browse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voyage_data_tab), _translate("Form", "Voyage Data", None))
        self.submit_btn.setText(_translate("Form", "Submit", None))
        self.cancel_btn.setText(_translate("Form", "Cancel", None))

