# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'objectionReport.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(818, 711)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.ship_name_edit = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ship_name_edit.sizePolicy().hasHeightForWidth())
        self.ship_name_edit.setSizePolicy(sizePolicy)
        self.ship_name_edit.setObjectName(_fromUtf8("ship_name_edit"))
        self.horizontalLayout.addWidget(self.ship_name_edit)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.call_sign_edit = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.call_sign_edit.sizePolicy().hasHeightForWidth())
        self.call_sign_edit.setSizePolicy(sizePolicy)
        self.call_sign_edit.setObjectName(_fromUtf8("call_sign_edit"))
        self.horizontalLayout.addWidget(self.call_sign_edit)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.voyage_number_edit = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voyage_number_edit.sizePolicy().hasHeightForWidth())
        self.voyage_number_edit.setSizePolicy(sizePolicy)
        self.voyage_number_edit.setObjectName(_fromUtf8("voyage_number_edit"))
        self.horizontalLayout.addWidget(self.voyage_number_edit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.captain_name_edit = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.captain_name_edit.sizePolicy().hasHeightForWidth())
        self.captain_name_edit.setSizePolicy(sizePolicy)
        self.captain_name_edit.setObjectName(_fromUtf8("captain_name_edit"))
        self.horizontalLayout_2.addWidget(self.captain_name_edit)
        self.label_6 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.dateEdit = QtGui.QDateEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.label_4 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4, QtCore.Qt.AlignRight)
        self.route_id_number = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.route_id_number.sizePolicy().hasHeightForWidth())
        self.route_id_number.setSizePolicy(sizePolicy)
        self.route_id_number.setObjectName(_fromUtf8("route_id_number"))
        self.horizontalLayout_2.addWidget(self.route_id_number)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.route_table_widget = QtGui.QTableWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.route_table_widget.sizePolicy().hasHeightForWidth())
        self.route_table_widget.setSizePolicy(sizePolicy)
        self.route_table_widget.setObjectName(_fromUtf8("route_table_widget"))
        self.route_table_widget.setColumnCount(3)
        self.route_table_widget.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.route_table_widget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.route_table_widget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.route_table_widget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.route_table_widget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.route_table_widget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.route_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.route_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.route_table_widget.setHorizontalHeaderItem(2, item)
        self.route_table_widget.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.route_table_widget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_water_depth = QtGui.QCheckBox(self.groupBox)
        self.checkBox_water_depth.setObjectName(_fromUtf8("checkBox_water_depth"))
        self.gridLayout.addWidget(self.checkBox_water_depth, 0, 0, 1, 1)
        self.checkBox_safety_margin = QtGui.QCheckBox(self.groupBox)
        self.checkBox_safety_margin.setObjectName(_fromUtf8("checkBox_safety_margin"))
        self.gridLayout.addWidget(self.checkBox_safety_margin, 1, 0, 1, 1)
        self.checkBox_heavy_traffic = QtGui.QCheckBox(self.groupBox)
        self.checkBox_heavy_traffic.setObjectName(_fromUtf8("checkBox_heavy_traffic"))
        self.gridLayout.addWidget(self.checkBox_heavy_traffic, 2, 1, 1, 1)
        self.textEdit_remark = QtGui.QTextEdit(self.groupBox)
        self.textEdit_remark.setObjectName(_fromUtf8("textEdit_remark"))
        self.gridLayout.addWidget(self.textEdit_remark, 4, 0, 1, 2)
        self.checkBox_ntm_navtex_egc = QtGui.QCheckBox(self.groupBox)
        self.checkBox_ntm_navtex_egc.setObjectName(_fromUtf8("checkBox_ntm_navtex_egc"))
        self.gridLayout.addWidget(self.checkBox_ntm_navtex_egc, 2, 0, 1, 1)
        self.checkBox_others = QtGui.QCheckBox(self.groupBox)
        self.checkBox_others.setObjectName(_fromUtf8("checkBox_others"))
        self.gridLayout.addWidget(self.checkBox_others, 3, 0, 1, 1)
        self.checkBox_violate_local = QtGui.QCheckBox(self.groupBox)
        self.checkBox_violate_local.setObjectName(_fromUtf8("checkBox_violate_local"))
        self.gridLayout.addWidget(self.checkBox_violate_local, 1, 1, 1, 1)
        self.checkBox_ukc = QtGui.QCheckBox(self.groupBox)
        self.checkBox_ukc.setObjectName(_fromUtf8("checkBox_ukc"))
        self.gridLayout.addWidget(self.checkBox_ukc, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.submit_btn = QtGui.QPushButton(Form)
        self.submit_btn.setObjectName(_fromUtf8("submit_btn"))
        self.horizontalLayout_5.addWidget(self.submit_btn)
        self.cancel_btn = QtGui.QPushButton(Form)
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout_5.addWidget(self.cancel_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "Ship Name", None))
        self.label_2.setText(_translate("Form", "Call Sign", None))
        self.label_3.setText(_translate("Form", "Voyage Number", None))
        self.label_5.setText(_translate("Form", "Captain Name", None))
        self.label_6.setText(_translate("Form", "Date", None))
        self.label_4.setText(_translate("Form", "Route\'s ID number", None))
        self.label_7.setText(_translate("Form", "Navigation hazard exist along the route at position:", None))
        self.groupBox_2.setTitle(_translate("Form", "Route", None))
        item = self.route_table_widget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.route_table_widget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.route_table_widget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.route_table_widget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4", None))
        item = self.route_table_widget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5", None))
        item = self.route_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id", None))
        item = self.route_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Latitude", None))
        item = self.route_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Longtitue", None))
        self.pushButton.setText(_translate("Form", " Add New Line", None))
        self.pushButton_2.setText(_translate("Form", "Remove Current", None))
        self.groupBox.setTitle(_translate("Form", "Reason of objection", None))
        self.checkBox_water_depth.setText(_translate("Form", "Insufficient water depth", None))
        self.checkBox_safety_margin.setText(_translate("Form", "Insufficient safety margin from navigation hazard", None))
        self.checkBox_heavy_traffic.setText(_translate("Form", "Heavy traffic that cause concer", None))
        self.checkBox_ntm_navtex_egc.setText(_translate("Form", "New navigation hazard affected by NTM/Navtex/EGC", None))
        self.checkBox_others.setText(_translate("Form", "Others", None))
        self.checkBox_violate_local.setText(_translate("Form", "Violate international or local regulation/low", None))
        self.checkBox_ukc.setText(_translate("Form", "Insufficient UKC", None))
        self.submit_btn.setText(_translate("Form", "Submit", None))
        self.cancel_btn.setText(_translate("Form", "Cancel", None))

