# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'requestRoute.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1046, 468)
        self.gridLayout_5 = QtGui.QGridLayout(Form)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.submitBtn = QtGui.QPushButton(self.frame)
        self.submitBtn.setObjectName(_fromUtf8("submitBtn"))
        self.horizontalLayout_2.addWidget(self.submitBtn)
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_shipName = QtGui.QLabel(self.frame)
        self.label_shipName.setObjectName(_fromUtf8("label_shipName"))
        self.horizontalLayout_6.addWidget(self.label_shipName)
        self.shipNameEdit = QtGui.QLineEdit(self.frame)
        self.shipNameEdit.setObjectName(_fromUtf8("shipNameEdit"))
        self.horizontalLayout_6.addWidget(self.shipNameEdit)
        self.label_callSign = QtGui.QLabel(self.frame)
        self.label_callSign.setObjectName(_fromUtf8("label_callSign"))
        self.horizontalLayout_6.addWidget(self.label_callSign)
        self.callSignEdit = QtGui.QLineEdit(self.frame)
        self.callSignEdit.setObjectName(_fromUtf8("callSignEdit"))
        self.horizontalLayout_6.addWidget(self.callSignEdit)
        self.label_voyageNumber = QtGui.QLabel(self.frame)
        self.label_voyageNumber.setObjectName(_fromUtf8("label_voyageNumber"))
        self.horizontalLayout_6.addWidget(self.label_voyageNumber)
        self.voyageNumberEdit = QtGui.QLineEdit(self.frame)
        self.voyageNumberEdit.setObjectName(_fromUtf8("voyageNumberEdit"))
        self.horizontalLayout_6.addWidget(self.voyageNumberEdit)
        self.label_date = QtGui.QLabel(self.frame)
        self.label_date.setObjectName(_fromUtf8("label_date"))
        self.horizontalLayout_6.addWidget(self.label_date)
        self.dateEdit = QtGui.QLineEdit(self.frame)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter = QtGui.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_DeparturePort = QtGui.QLabel(self.groupBox_2)
        self.label_DeparturePort.setObjectName(_fromUtf8("label_DeparturePort"))
        self.gridLayout.addWidget(self.label_DeparturePort, 1, 0, 1, 1)
        self.comboBoxDeparturePort = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxDeparturePort.setObjectName(_fromUtf8("comboBoxDeparturePort"))
        self.gridLayout.addWidget(self.comboBoxDeparturePort, 1, 1, 1, 1)
        self.label_DepartureCountry = QtGui.QLabel(self.groupBox_2)
        self.label_DepartureCountry.setObjectName(_fromUtf8("label_DepartureCountry"))
        self.gridLayout.addWidget(self.label_DepartureCountry, 0, 0, 1, 1)
        self.comboBoxDepartureCountry = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxDepartureCountry.setObjectName(_fromUtf8("comboBoxDepartureCountry"))
        self.gridLayout.addWidget(self.comboBoxDepartureCountry, 0, 1, 1, 1)
        self.label_DepartureUnloCode = QtGui.QLabel(self.groupBox_2)
        self.label_DepartureUnloCode.setObjectName(_fromUtf8("label_DepartureUnloCode"))
        self.gridLayout.addWidget(self.label_DepartureUnloCode, 2, 0, 1, 1)
        self.unloCodeDepartureEdit = QtGui.QLineEdit(self.groupBox_2)
        self.unloCodeDepartureEdit.setObjectName(_fromUtf8("unloCodeDepartureEdit"))
        self.gridLayout.addWidget(self.unloCodeDepartureEdit, 2, 1, 1, 1)
        self.label_DepartureTerminal = QtGui.QLabel(self.groupBox_2)
        self.label_DepartureTerminal.setObjectName(_fromUtf8("label_DepartureTerminal"))
        self.gridLayout.addWidget(self.label_DepartureTerminal, 3, 0, 1, 1)
        self.terminalDepartureEdit = QtGui.QLineEdit(self.groupBox_2)
        self.terminalDepartureEdit.setObjectName(_fromUtf8("terminalDepartureEdit"))
        self.gridLayout.addWidget(self.terminalDepartureEdit, 3, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_DestinationCountry = QtGui.QLabel(self.groupBox_3)
        self.label_DestinationCountry.setObjectName(_fromUtf8("label_DestinationCountry"))
        self.gridLayout_2.addWidget(self.label_DestinationCountry, 0, 0, 1, 1)
        self.label_DestinationUnloCode = QtGui.QLabel(self.groupBox_3)
        self.label_DestinationUnloCode.setObjectName(_fromUtf8("label_DestinationUnloCode"))
        self.gridLayout_2.addWidget(self.label_DestinationUnloCode, 2, 0, 1, 1)
        self.label_DestinationPort = QtGui.QLabel(self.groupBox_3)
        self.label_DestinationPort.setObjectName(_fromUtf8("label_DestinationPort"))
        self.gridLayout_2.addWidget(self.label_DestinationPort, 1, 0, 1, 1)
        self.comboBox_DestinationCountry = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_DestinationCountry.setObjectName(_fromUtf8("comboBox_DestinationCountry"))
        self.gridLayout_2.addWidget(self.comboBox_DestinationCountry, 0, 1, 1, 1)
        self.comboBox_DestinationPort = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_DestinationPort.setObjectName(_fromUtf8("comboBox_DestinationPort"))
        self.gridLayout_2.addWidget(self.comboBox_DestinationPort, 1, 1, 1, 1)
        self.DestinationUnloCodeEdit = QtGui.QLineEdit(self.groupBox_3)
        self.DestinationUnloCodeEdit.setObjectName(_fromUtf8("DestinationUnloCodeEdit"))
        self.gridLayout_2.addWidget(self.DestinationUnloCodeEdit, 2, 1, 1, 1)
        self.label_DestinationTerminal = QtGui.QLabel(self.groupBox_3)
        self.label_DestinationTerminal.setObjectName(_fromUtf8("label_DestinationTerminal"))
        self.gridLayout_2.addWidget(self.label_DestinationTerminal, 3, 0, 1, 1)
        self.DestinationTerminalEdit = QtGui.QLineEdit(self.groupBox_3)
        self.DestinationTerminalEdit.setObjectName(_fromUtf8("DestinationTerminalEdit"))
        self.gridLayout_2.addWidget(self.DestinationTerminalEdit, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_via = QtGui.QLabel(self.groupBox)
        self.label_via.setObjectName(_fromUtf8("label_via"))
        self.horizontalLayout.addWidget(self.label_via)
        self.via1Edit = QtGui.QLineEdit(self.groupBox)
        self.via1Edit.setObjectName(_fromUtf8("via1Edit"))
        self.horizontalLayout.addWidget(self.via1Edit)
        self.via2Edit = QtGui.QLineEdit(self.groupBox)
        self.via2Edit.setObjectName(_fromUtf8("via2Edit"))
        self.horizontalLayout.addWidget(self.via2Edit)
        self.via3Edit = QtGui.QLineEdit(self.groupBox)
        self.via3Edit.setObjectName(_fromUtf8("via3Edit"))
        self.horizontalLayout.addWidget(self.via3Edit)
        self.via4Edit = QtGui.QLineEdit(self.groupBox)
        self.via4Edit.setObjectName(_fromUtf8("via4Edit"))
        self.horizontalLayout.addWidget(self.via4Edit)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_question = QtGui.QLabel(self.groupBox)
        self.label_question.setObjectName(_fromUtf8("label_question"))
        self.horizontalLayout_3.addWidget(self.label_question)
        self.radioButtonYes = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonYes.sizePolicy().hasHeightForWidth())
        self.radioButtonYes.setSizePolicy(sizePolicy)
        self.radioButtonYes.setObjectName(_fromUtf8("radioButtonYes"))
        self.horizontalLayout_3.addWidget(self.radioButtonYes)
        self.radioButtonNo = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonNo.sizePolicy().hasHeightForWidth())
        self.radioButtonNo.setSizePolicy(sizePolicy)
        self.radioButtonNo.setObjectName(_fromUtf8("radioButtonNo"))
        self.horizontalLayout_3.addWidget(self.radioButtonNo)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_maxDraft = QtGui.QLabel(self.groupBox)
        self.label_maxDraft.setObjectName(_fromUtf8("label_maxDraft"))
        self.horizontalLayout_4.addWidget(self.label_maxDraft)
        self.maxiDraftEdit = QtGui.QLineEdit(self.groupBox)
        self.maxiDraftEdit.setObjectName(_fromUtf8("maxiDraftEdit"))
        self.horizontalLayout_4.addWidget(self.maxiDraftEdit)
        self.label_loadCondition = QtGui.QLabel(self.groupBox)
        self.label_loadCondition.setObjectName(_fromUtf8("label_loadCondition"))
        self.horizontalLayout_4.addWidget(self.label_loadCondition)
        self.loadConditionEdit = QtGui.QLineEdit(self.groupBox)
        self.loadConditionEdit.setObjectName(_fromUtf8("loadConditionEdit"))
        self.horizontalLayout_4.addWidget(self.loadConditionEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_speedSetting = QtGui.QLabel(self.groupBox)
        self.label_speedSetting.setObjectName(_fromUtf8("label_speedSetting"))
        self.horizontalLayout_5.addWidget(self.label_speedSetting)
        self.speedSettingEdit = QtGui.QLineEdit(self.groupBox)
        self.speedSettingEdit.setObjectName(_fromUtf8("speedSettingEdit"))
        self.horizontalLayout_5.addWidget(self.speedSettingEdit)
        self.label_etd = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_etd.sizePolicy().hasHeightForWidth())
        self.label_etd.setSizePolicy(sizePolicy)
        self.label_etd.setObjectName(_fromUtf8("label_etd"))
        self.horizontalLayout_5.addWidget(self.label_etd)
        self.etdEdit = QtGui.QLineEdit(self.groupBox)
        self.etdEdit.setObjectName(_fromUtf8("etdEdit"))
        self.horizontalLayout_5.addWidget(self.etdEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.label_shipName.setBuddy(self.shipNameEdit)
        self.label_callSign.setBuddy(self.callSignEdit)
        self.label_voyageNumber.setBuddy(self.voyageNumberEdit)
        self.label_date.setBuddy(self.dateEdit)
        self.label_DeparturePort.setBuddy(self.comboBoxDeparturePort)
        self.label_DepartureCountry.setBuddy(self.comboBoxDepartureCountry)
        self.label_DepartureUnloCode.setBuddy(self.unloCodeDepartureEdit)
        self.label_DepartureTerminal.setBuddy(self.terminalDepartureEdit)
        self.label_DestinationCountry.setBuddy(self.comboBox_DestinationCountry)
        self.label_DestinationUnloCode.setBuddy(self.DestinationUnloCodeEdit)
        self.label_DestinationPort.setBuddy(self.comboBox_DestinationPort)
        self.label_DestinationTerminal.setBuddy(self.DestinationTerminalEdit)
        self.label_via.setBuddy(self.via1Edit)
        self.label_maxDraft.setBuddy(self.maxiDraftEdit)
        self.label_loadCondition.setBuddy(self.loadConditionEdit)
        self.label_speedSetting.setBuddy(self.speedSettingEdit)
        self.label_etd.setBuddy(self.etdEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.shipNameEdit, self.callSignEdit)
        Form.setTabOrder(self.callSignEdit, self.voyageNumberEdit)
        Form.setTabOrder(self.voyageNumberEdit, self.dateEdit)
        Form.setTabOrder(self.dateEdit, self.comboBoxDepartureCountry)
        Form.setTabOrder(self.comboBoxDepartureCountry, self.comboBox_DestinationCountry)
        Form.setTabOrder(self.comboBox_DestinationCountry, self.comboBoxDeparturePort)
        Form.setTabOrder(self.comboBoxDeparturePort, self.comboBox_DestinationPort)
        Form.setTabOrder(self.comboBox_DestinationPort, self.unloCodeDepartureEdit)
        Form.setTabOrder(self.unloCodeDepartureEdit, self.DestinationUnloCodeEdit)
        Form.setTabOrder(self.DestinationUnloCodeEdit, self.terminalDepartureEdit)
        Form.setTabOrder(self.terminalDepartureEdit, self.DestinationTerminalEdit)
        Form.setTabOrder(self.DestinationTerminalEdit, self.via1Edit)
        Form.setTabOrder(self.via1Edit, self.via2Edit)
        Form.setTabOrder(self.via2Edit, self.via3Edit)
        Form.setTabOrder(self.via3Edit, self.via4Edit)
        Form.setTabOrder(self.via4Edit, self.radioButtonYes)
        Form.setTabOrder(self.radioButtonYes, self.radioButtonNo)
        Form.setTabOrder(self.radioButtonNo, self.maxiDraftEdit)
        Form.setTabOrder(self.maxiDraftEdit, self.loadConditionEdit)
        Form.setTabOrder(self.loadConditionEdit, self.speedSettingEdit)
        Form.setTabOrder(self.speedSettingEdit, self.etdEdit)
        Form.setTabOrder(self.etdEdit, self.submitBtn)
        Form.setTabOrder(self.submitBtn, self.pushButton_2)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.submitBtn.setText(_translate("Form", "Submit", None))
        self.pushButton_2.setText(_translate("Form", "Cancel", None))
        self.label_shipName.setText(_translate("Form", "Ship Name", None))
        self.label_callSign.setText(_translate("Form", "Call Sign", None))
        self.label_voyageNumber.setText(_translate("Form", "Voyage Number", None))
        self.label_date.setText(_translate("Form", "Date", None))
        self.groupBox.setTitle(_translate("Form", "Voyage Detail", None))
        self.groupBox_2.setTitle(_translate("Form", "Departure", None))
        self.label_DeparturePort.setText(_translate("Form", "Port", None))
        self.label_DepartureCountry.setText(_translate("Form", "Country", None))
        self.label_DepartureUnloCode.setText(_translate("Form", "UNLO Code", None))
        self.label_DepartureTerminal.setText(_translate("Form", "Terminal", None))
        self.groupBox_3.setTitle(_translate("Form", "Destination", None))
        self.label_DestinationCountry.setText(_translate("Form", "Country", None))
        self.label_DestinationUnloCode.setText(_translate("Form", "UNLO Code", None))
        self.label_DestinationPort.setText(_translate("Form", "Port", None))
        self.label_DestinationTerminal.setText(_translate("Form", "Terminal", None))
        self.label_via.setText(_translate("Form", "Via", None))
        self.label_question.setText(_translate("Form", "Use DW route when passing channel or TSS if applicable?", None))
        self.radioButtonYes.setText(_translate("Form", "Yes", None))
        self.radioButtonNo.setText(_translate("Form", "No", None))
        self.label_maxDraft.setText(_translate("Form", "Maximum Draft", None))
        self.label_loadCondition.setText(_translate("Form", "Load Condition", None))
        self.label_speedSetting.setText(_translate("Form", "Speed Setting", None))
        self.label_etd.setText(_translate("Form", "ETD           ", None))

