# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'requestRoute.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1030, 562)
        self.gridLayout_5 = QtGui.QGridLayout(Form)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_shipName = QtGui.QLabel(self.frame)
        self.label_shipName.setObjectName(_fromUtf8("label_shipName"))
        self.horizontalLayout_6.addWidget(self.label_shipName)
        self.shipNameEdit = QtGui.QLineEdit(self.frame)
        self.shipNameEdit.setObjectName(_fromUtf8("shipNameEdit"))
        self.horizontalLayout_6.addWidget(self.shipNameEdit)
        self.label_callSign = QtGui.QLabel(self.frame)
        self.label_callSign.setObjectName(_fromUtf8("label_callSign"))
        self.horizontalLayout_6.addWidget(self.label_callSign)
        self.callSignEdit = QtGui.QLineEdit(self.frame)
        self.callSignEdit.setObjectName(_fromUtf8("callSignEdit"))
        self.horizontalLayout_6.addWidget(self.callSignEdit)
        self.label_voyageNumber = QtGui.QLabel(self.frame)
        self.label_voyageNumber.setObjectName(_fromUtf8("label_voyageNumber"))
        self.horizontalLayout_6.addWidget(self.label_voyageNumber)
        self.voyageNumberEdit = QtGui.QLineEdit(self.frame)
        self.voyageNumberEdit.setObjectName(_fromUtf8("voyageNumberEdit"))
        self.horizontalLayout_6.addWidget(self.voyageNumberEdit)
        self.label_date = QtGui.QLabel(self.frame)
        self.label_date.setObjectName(_fromUtf8("label_date"))
        self.horizontalLayout_6.addWidget(self.label_date)
        self.dateEdit = QtGui.QLineEdit(self.frame)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.depart_date_edit = QtGui.QDateEdit(self.groupBox_2)
        self.depart_date_edit.setCalendarPopup(True)
        self.depart_date_edit.setObjectName(_fromUtf8("depart_date_edit"))
        self.gridLayout.addWidget(self.depart_date_edit, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.unlo_departure_edit = QtGui.QLineEdit(self.groupBox_2)
        self.unlo_departure_edit.setObjectName(_fromUtf8("unlo_departure_edit"))
        self.gridLayout.addWidget(self.unlo_departure_edit, 1, 5, 1, 1)
        self.terminal_depature = QtGui.QLineEdit(self.groupBox_2)
        self.terminal_depature.setObjectName(_fromUtf8("terminal_depature"))
        self.gridLayout.addWidget(self.terminal_depature, 1, 7, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.departure_port_combo = QtGui.QComboBox(self.groupBox_2)
        self.departure_port_combo.setObjectName(_fromUtf8("departure_port_combo"))
        self.gridLayout.addWidget(self.departure_port_combo, 1, 3, 1, 1)
        self.departure_country_combo = QtGui.QComboBox(self.groupBox_2)
        self.departure_country_combo.setObjectName(_fromUtf8("departure_country_combo"))
        self.gridLayout.addWidget(self.departure_country_combo, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 4, 1, 1)
        self.departure_time_edit = QtGui.QTimeEdit(self.groupBox_2)
        self.departure_time_edit.setCalendarPopup(True)
        self.departure_time_edit.setObjectName(_fromUtf8("departure_time_edit"))
        self.gridLayout.addWidget(self.departure_time_edit, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 1, 2, 1, 1)
        self.arrival_unlo_code = QtGui.QLineEdit(self.groupBox_3)
        self.arrival_unlo_code.setObjectName(_fromUtf8("arrival_unlo_code"))
        self.gridLayout_2.addWidget(self.arrival_unlo_code, 1, 5, 1, 1)
        self.arrival_terminal = QtGui.QLineEdit(self.groupBox_3)
        self.arrival_terminal.setObjectName(_fromUtf8("arrival_terminal"))
        self.gridLayout_2.addWidget(self.arrival_terminal, 1, 7, 1, 1)
        self.arrival_country_edit = QtGui.QComboBox(self.groupBox_3)
        self.arrival_country_edit.setObjectName(_fromUtf8("arrival_country_edit"))
        self.gridLayout_2.addWidget(self.arrival_country_edit, 1, 1, 1, 1)
        self.arrival_port_combo = QtGui.QComboBox(self.groupBox_3)
        self.arrival_port_combo.setObjectName(_fromUtf8("arrival_port_combo"))
        self.gridLayout_2.addWidget(self.arrival_port_combo, 1, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 1, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 1, 6, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.arrival_date_edit = QtGui.QDateEdit(self.groupBox_3)
        self.arrival_date_edit.setCalendarPopup(True)
        self.arrival_date_edit.setObjectName(_fromUtf8("arrival_date_edit"))
        self.gridLayout_2.addWidget(self.arrival_date_edit, 0, 1, 1, 1)
        self.arrival_time_edit = QtGui.QTimeEdit(self.groupBox_3)
        self.arrival_time_edit.setCalendarPopup(True)
        self.arrival_time_edit.setObjectName(_fromUtf8("arrival_time_edit"))
        self.gridLayout_2.addWidget(self.arrival_time_edit, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.frame_2 = QtGui.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_question = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_question.sizePolicy().hasHeightForWidth())
        self.label_question.setSizePolicy(sizePolicy)
        self.label_question.setObjectName(_fromUtf8("label_question"))
        self.horizontalLayout_4.addWidget(self.label_question)
        self.use_dw_route_yes_radio = QtGui.QRadioButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_dw_route_yes_radio.sizePolicy().hasHeightForWidth())
        self.use_dw_route_yes_radio.setSizePolicy(sizePolicy)
        self.use_dw_route_yes_radio.setObjectName(_fromUtf8("use_dw_route_yes_radio"))
        self.horizontalLayout_4.addWidget(self.use_dw_route_yes_radio)
        self.use_dw_route_no_radio = QtGui.QRadioButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_dw_route_no_radio.sizePolicy().hasHeightForWidth())
        self.use_dw_route_no_radio.setSizePolicy(sizePolicy)
        self.use_dw_route_no_radio.setObjectName(_fromUtf8("use_dw_route_no_radio"))
        self.horizontalLayout_4.addWidget(self.use_dw_route_no_radio)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_maxDraft = QtGui.QLabel(self.frame_2)
        self.label_maxDraft.setObjectName(_fromUtf8("label_maxDraft"))
        self.horizontalLayout_5.addWidget(self.label_maxDraft)
        self.maxiDraftEdit = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxiDraftEdit.sizePolicy().hasHeightForWidth())
        self.maxiDraftEdit.setSizePolicy(sizePolicy)
        self.maxiDraftEdit.setObjectName(_fromUtf8("maxiDraftEdit"))
        self.horizontalLayout_5.addWidget(self.maxiDraftEdit)
        self.label_loadCondition = QtGui.QLabel(self.frame_2)
        self.label_loadCondition.setObjectName(_fromUtf8("label_loadCondition"))
        self.horizontalLayout_5.addWidget(self.label_loadCondition)
        self.loadConditionEdit = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadConditionEdit.sizePolicy().hasHeightForWidth())
        self.loadConditionEdit.setSizePolicy(sizePolicy)
        self.loadConditionEdit.setObjectName(_fromUtf8("loadConditionEdit"))
        self.horizontalLayout_5.addWidget(self.loadConditionEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_speedSetting = QtGui.QLabel(self.frame_2)
        self.label_speedSetting.setObjectName(_fromUtf8("label_speedSetting"))
        self.horizontalLayout_11.addWidget(self.label_speedSetting)
        self.speedSettingEdit = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedSettingEdit.sizePolicy().hasHeightForWidth())
        self.speedSettingEdit.setSizePolicy(sizePolicy)
        self.speedSettingEdit.setObjectName(_fromUtf8("speedSettingEdit"))
        self.horizontalLayout_11.addWidget(self.speedSettingEdit)
        self.label_etd = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_etd.sizePolicy().hasHeightForWidth())
        self.label_etd.setSizePolicy(sizePolicy)
        self.label_etd.setObjectName(_fromUtf8("label_etd"))
        self.horizontalLayout_11.addWidget(self.label_etd)
        self.etdEdit = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etdEdit.sizePolicy().hasHeightForWidth())
        self.etdEdit.setSizePolicy(sizePolicy)
        self.etdEdit.setObjectName(_fromUtf8("etdEdit"))
        self.horizontalLayout_11.addWidget(self.etdEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 3, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_3.addWidget(self.frame_4, 3, 1, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 806, 128))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_via = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_via.setObjectName(_fromUtf8("label_via"))
        self.gridLayout_7.addWidget(self.label_via, 0, 0, 1, 1)
        self.via1Edit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via1Edit.setObjectName(_fromUtf8("via1Edit"))
        self.gridLayout_7.addWidget(self.via1Edit, 0, 1, 1, 1)
        self.via2Edit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via2Edit.setObjectName(_fromUtf8("via2Edit"))
        self.gridLayout_7.addWidget(self.via2Edit, 0, 2, 1, 1)
        self.via3Edit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via3Edit.setObjectName(_fromUtf8("via3Edit"))
        self.gridLayout_7.addWidget(self.via3Edit, 0, 3, 1, 1)
        self.via4Edit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via4Edit.setObjectName(_fromUtf8("via4Edit"))
        self.gridLayout_7.addWidget(self.via4Edit, 0, 4, 1, 1)
        self.via4Edit_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via4Edit_3.setObjectName(_fromUtf8("via4Edit_3"))
        self.gridLayout_7.addWidget(self.via4Edit_3, 0, 5, 1, 1)
        self.add_btn = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.add_btn.setObjectName(_fromUtf8("add_btn"))
        self.gridLayout_7.addWidget(self.add_btn, 0, 6, 1, 1)
        self.via4Edit_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via4Edit_5.setObjectName(_fromUtf8("via4Edit_5"))
        self.gridLayout_7.addWidget(self.via4Edit_5, 1, 1, 1, 1)
        self.via4Edit_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via4Edit_6.setObjectName(_fromUtf8("via4Edit_6"))
        self.gridLayout_7.addWidget(self.via4Edit_6, 1, 2, 1, 1)
        self.via4Edit_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via4Edit_7.setObjectName(_fromUtf8("via4Edit_7"))
        self.gridLayout_7.addWidget(self.via4Edit_7, 1, 3, 1, 1)
        self.via4Edit_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via4Edit_4.setObjectName(_fromUtf8("via4Edit_4"))
        self.gridLayout_7.addWidget(self.via4Edit_4, 1, 4, 1, 1)
        self.via4Edit_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.via4Edit_8.setObjectName(_fromUtf8("via4Edit_8"))
        self.gridLayout_7.addWidget(self.via4Edit_8, 1, 5, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.submitBtn = QtGui.QPushButton(self.frame)
        self.submitBtn.setObjectName(_fromUtf8("submitBtn"))
        self.horizontalLayout_2.addWidget(self.submitBtn)
        self.cancel_btn = QtGui.QPushButton(self.frame)
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.label_shipName.setBuddy(self.shipNameEdit)
        self.label_callSign.setBuddy(self.callSignEdit)
        self.label_voyageNumber.setBuddy(self.voyageNumberEdit)
        self.label_date.setBuddy(self.dateEdit)
        self.label_maxDraft.setBuddy(self.maxiDraftEdit)
        self.label_loadCondition.setBuddy(self.loadConditionEdit)
        self.label_speedSetting.setBuddy(self.speedSettingEdit)
        self.label_etd.setBuddy(self.etdEdit)
        self.label_via.setBuddy(self.via1Edit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.shipNameEdit, self.callSignEdit)
        Form.setTabOrder(self.callSignEdit, self.voyageNumberEdit)
        Form.setTabOrder(self.voyageNumberEdit, self.dateEdit)
        Form.setTabOrder(self.dateEdit, self.via1Edit)
        Form.setTabOrder(self.via1Edit, self.via2Edit)
        Form.setTabOrder(self.via2Edit, self.via3Edit)
        Form.setTabOrder(self.via3Edit, self.via4Edit)
        Form.setTabOrder(self.via4Edit, self.use_dw_route_yes_radio)
        Form.setTabOrder(self.use_dw_route_yes_radio, self.use_dw_route_no_radio)
        Form.setTabOrder(self.use_dw_route_no_radio, self.maxiDraftEdit)
        Form.setTabOrder(self.maxiDraftEdit, self.loadConditionEdit)
        Form.setTabOrder(self.loadConditionEdit, self.speedSettingEdit)
        Form.setTabOrder(self.speedSettingEdit, self.etdEdit)
        Form.setTabOrder(self.etdEdit, self.submitBtn)
        Form.setTabOrder(self.submitBtn, self.cancel_btn)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_shipName.setText(_translate("Form", "Ship Name", None))
        self.label_callSign.setText(_translate("Form", "Call Sign", None))
        self.label_voyageNumber.setText(_translate("Form", "Voyage Number", None))
        self.label_date.setText(_translate("Form", "Date", None))
        self.groupBox.setTitle(_translate("Form", "Voyage Detail", None))
        self.groupBox_2.setTitle(_translate("Form", "Departure", None))
        self.label_11.setText(_translate("Form", "Departure Port", None))
        self.label_6.setText(_translate("Form", "Departure Date", None))
        self.label_10.setText(_translate("Form", "Departure Country", None))
        self.label_13.setText(_translate("Form", "Terminal", None))
        self.label_7.setText(_translate("Form", "Departure Time", None))
        self.label_12.setText(_translate("Form", "UNLO Code", None))
        self.groupBox_3.setTitle(_translate("Form", "Arrival", None))
        self.label_15.setText(_translate("Form", "Arrival Port", None))
        self.label_14.setText(_translate("Form", "Arrival Country", None))
        self.label_16.setText(_translate("Form", "UNLO Code", None))
        self.label_17.setText(_translate("Form", "Terminal", None))
        self.label_8.setText(_translate("Form", "Arrival Time     ", None))
        self.label_9.setText(_translate("Form", "Arrival Time  ", None))
        self.label_question.setText(_translate("Form", "Use DW route when passing channel or TSS if applicable?", None))
        self.use_dw_route_yes_radio.setText(_translate("Form", "Yes", None))
        self.use_dw_route_no_radio.setText(_translate("Form", "No", None))
        self.label_maxDraft.setText(_translate("Form", "Maximum Draft", None))
        self.label_loadCondition.setText(_translate("Form", "Load Condition", None))
        self.label_speedSetting.setText(_translate("Form", "Speed Setting", None))
        self.label_etd.setText(_translate("Form", "ETD           ", None))
        self.label_via.setText(_translate("Form", "Via", None))
        self.add_btn.setText(_translate("Form", "Add", None))
        self.submitBtn.setText(_translate("Form", "Submit", None))
        self.cancel_btn.setText(_translate("Form", "Cancel", None))

