# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shareRoute.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1324, 1244)
        self.gridLayout_4 = QtGui.QGridLayout(Form)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea = QtGui.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1304, 1224))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout.addWidget(self.lineEdit_5)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.voyageDetailGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.voyageDetailGroupBox.setObjectName(_fromUtf8("voyageDetailGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.voyageDetailGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 5, 1, 1)
        self.label_12 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 9, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.voyageDetailGroupBox)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout.addWidget(self.comboBox_2, 1, 6, 1, 3)
        self.lineEdit_6 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 0, 1, 1, 3)
        self.label_11 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 5, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout.addWidget(self.lineEdit_10, 1, 10, 1, 1)
        self.label_13 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 11, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout.addWidget(self.lineEdit_13, 3, 12, 1, 1)
        self.label_10 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.voyageDetailGroupBox)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 3)
        self.lineEdit_7 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 0, 6, 1, 3)
        self.lineEdit_11 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout.addWidget(self.lineEdit_11, 1, 12, 1, 1)
        self.label_6 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 6, 0, 1, 2)
        self.lineEdit_8 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout.addWidget(self.lineEdit_8, 2, 1, 1, 3)
        self.radioButton_2 = QtGui.QRadioButton(self.voyageDetailGroupBox)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout.addWidget(self.radioButton_2, 6, 5, 1, 2)
        self.lineEdit_25 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.gridLayout.addWidget(self.lineEdit_25, 9, 5, 1, 3)
        self.lineEdit_19 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout.addWidget(self.lineEdit_19, 5, 4, 1, 3)
        self.label_20 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 7, 0, 1, 2)
        self.lineEdit_15 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout.addWidget(self.lineEdit_15, 4, 4, 1, 3)
        self.lineEdit_9 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout.addWidget(self.lineEdit_9, 2, 6, 1, 3)
        self.label_16 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 3, 9, 1, 1)
        self.label_17 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 3, 11, 1, 1)
        self.label_8 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 5, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout.addWidget(self.lineEdit_12, 3, 10, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.voyageDetailGroupBox)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.gridLayout.addWidget(self.comboBox_3, 3, 1, 1, 3)
        self.lineEdit_16 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout.addWidget(self.lineEdit_16, 4, 7, 1, 2)
        self.radioButton_4 = QtGui.QRadioButton(self.voyageDetailGroupBox)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout.addWidget(self.radioButton_4, 7, 5, 1, 2)
        self.radioButton = QtGui.QRadioButton(self.voyageDetailGroupBox)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout.addWidget(self.radioButton, 6, 3, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.voyageDetailGroupBox)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 8, 8, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.voyageDetailGroupBox)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.gridLayout.addWidget(self.comboBox_4, 3, 6, 1, 3)
        self.label_14 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 8, 0, 1, 2)
        self.lineEdit_22 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout.addWidget(self.lineEdit_22, 8, 3, 1, 2)
        self.lineEdit_20 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout.addWidget(self.lineEdit_20, 5, 7, 1, 2)
        self.label_15 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 3, 5, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.voyageDetailGroupBox)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout.addWidget(self.radioButton_3, 7, 3, 1, 1)
        self.lineEdit_23 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.gridLayout.addWidget(self.lineEdit_23, 8, 5, 1, 3)
        self.lineEdit_24 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.gridLayout.addWidget(self.lineEdit_24, 9, 3, 1, 2)
        self.checkBox_3 = QtGui.QCheckBox(self.voyageDetailGroupBox)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 10, 8, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.voyageDetailGroupBox)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 9, 8, 1, 1)
        self.label_23 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 12, 0, 1, 3)
        self.label_22 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 11, 0, 1, 3)
        self.lineEdit_27 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.gridLayout.addWidget(self.lineEdit_27, 10, 5, 1, 3)
        self.lineEdit_26 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.gridLayout.addWidget(self.lineEdit_26, 10, 3, 1, 2)
        self.tableWidget = QtGui.QTableWidget(self.voyageDetailGroupBox)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 13, 0, 1, 13)
        self.label_18 = QtGui.QLabel(self.voyageDetailGroupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout.addWidget(self.lineEdit_14, 4, 1, 1, 3)
        self.lineEdit_18 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout.addWidget(self.lineEdit_18, 5, 1, 1, 3)
        self.lineEdit_21 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout.addWidget(self.lineEdit_21, 5, 9, 1, 2)
        self.lineEdit_17 = QtGui.QLineEdit(self.voyageDetailGroupBox)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout.addWidget(self.lineEdit_17, 4, 9, 1, 2)
        self.gridLayout_3.addWidget(self.voyageDetailGroupBox, 1, 0, 1, 2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 3, 1, 1, 1)
        self.voyageDataGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.voyageDataGroupBox.setObjectName(_fromUtf8("voyageDataGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.voyageDataGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_24 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_2.addWidget(self.label_24)
        self.lineEdit_28 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.horizontalLayout_2.addWidget(self.lineEdit_28)
        self.label_25 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_2.addWidget(self.label_25)
        self.lineEdit_29 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.horizontalLayout_2.addWidget(self.lineEdit_29)
        self.label_26 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_2.addWidget(self.label_26)
        self.lineEdit_30 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.horizontalLayout_2.addWidget(self.lineEdit_30)
        self.label_27 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_2.addWidget(self.label_27)
        self.lineEdit_31 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.horizontalLayout_2.addWidget(self.lineEdit_31)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_28 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_3.addWidget(self.label_28)
        self.lineEdit_32 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.horizontalLayout_3.addWidget(self.lineEdit_32)
        self.label_29 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_3.addWidget(self.label_29)
        self.lineEdit_33 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.horizontalLayout_3.addWidget(self.lineEdit_33)
        self.label_30 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_3.addWidget(self.label_30)
        self.lineEdit_34 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.horizontalLayout_3.addWidget(self.lineEdit_34)
        self.label_31 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_3.addWidget(self.label_31)
        self.lineEdit_35 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.horizontalLayout_3.addWidget(self.lineEdit_35)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton = QtGui.QPushButton(self.voyageDataGroupBox)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.label_32 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_4.addWidget(self.label_32)
        self.lineEdit_36 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.horizontalLayout_4.addWidget(self.lineEdit_36)
        self.label_33 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_4.addWidget(self.label_33)
        self.lineEdit_37 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_37.setObjectName(_fromUtf8("lineEdit_37"))
        self.horizontalLayout_4.addWidget(self.lineEdit_37)
        self.label_34 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_4.addWidget(self.label_34)
        self.lineEdit_38 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_38.setObjectName(_fromUtf8("lineEdit_38"))
        self.horizontalLayout_4.addWidget(self.lineEdit_38)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.tableWidget_2 = QtGui.QTableWidget(self.voyageDataGroupBox)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_2, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_35 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_5.addWidget(self.label_35)
        self.lineEdit_39 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_39.setObjectName(_fromUtf8("lineEdit_39"))
        self.horizontalLayout_5.addWidget(self.lineEdit_39)
        self.pushButton_2 = QtGui.QPushButton(self.voyageDataGroupBox)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_36 = QtGui.QLabel(self.voyageDataGroupBox)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_6.addWidget(self.label_36)
        self.lineEdit_40 = QtGui.QLineEdit(self.voyageDataGroupBox)
        self.lineEdit_40.setObjectName(_fromUtf8("lineEdit_40"))
        self.horizontalLayout_6.addWidget(self.lineEdit_40)
        self.pushButton_3 = QtGui.QPushButton(self.voyageDataGroupBox)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.gridLayout_3.addWidget(self.voyageDataGroupBox, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "TextLabel", None))
        self.label_2.setText(_translate("Form", "TextLabel", None))
        self.label_3.setText(_translate("Form", "TextLabel", None))
        self.label_4.setText(_translate("Form", "TextLabel", None))
        self.label_5.setText(_translate("Form", "TextLabel", None))
        self.voyageDetailGroupBox.setTitle(_translate("Form", "Voyage Detail", None))
        self.label_7.setText(_translate("Form", "TextLabel", None))
        self.label_12.setText(_translate("Form", "TextLabel", None))
        self.label_11.setText(_translate("Form", "TextLabel", None))
        self.label_13.setText(_translate("Form", "TextLabel", None))
        self.label_10.setText(_translate("Form", "TextLabel", None))
        self.label_6.setText(_translate("Form", "TextLabel", None))
        self.label_19.setText(_translate("Form", "TextLabel", None))
        self.radioButton_2.setText(_translate("Form", "RadioButton", None))
        self.label_20.setText(_translate("Form", "TextLabel", None))
        self.label_16.setText(_translate("Form", "TextLabel", None))
        self.label_17.setText(_translate("Form", "TextLabel", None))
        self.label_8.setText(_translate("Form", "TextLabel", None))
        self.label_9.setText(_translate("Form", "TextLabel", None))
        self.radioButton_4.setText(_translate("Form", "RadioButton", None))
        self.radioButton.setText(_translate("Form", "RadioButton", None))
        self.checkBox.setText(_translate("Form", "CheckBox", None))
        self.label_14.setText(_translate("Form", "TextLabel", None))
        self.label_21.setText(_translate("Form", "TextLabel", None))
        self.label_15.setText(_translate("Form", "TextLabel", None))
        self.radioButton_3.setText(_translate("Form", "RadioButton", None))
        self.checkBox_3.setText(_translate("Form", "CheckBox", None))
        self.checkBox_2.setText(_translate("Form", "CheckBox", None))
        self.label_23.setText(_translate("Form", "TextLabel", None))
        self.label_22.setText(_translate("Form", "TextLabel", None))
        self.label_18.setText(_translate("Form", "TextLabel", None))
        self.pushButton_4.setText(_translate("Form", "Submit", None))
        self.pushButton_5.setText(_translate("Form", "Cancel", None))
        self.voyageDataGroupBox.setTitle(_translate("Form", "Voyage Data", None))
        self.label_24.setText(_translate("Form", "TextLabel", None))
        self.label_25.setText(_translate("Form", "TextLabel", None))
        self.label_26.setText(_translate("Form", "TextLabel", None))
        self.label_27.setText(_translate("Form", "TextLabel", None))
        self.label_28.setText(_translate("Form", "TextLabel", None))
        self.label_29.setText(_translate("Form", "TextLabel", None))
        self.label_30.setText(_translate("Form", "TextLabel", None))
        self.label_31.setText(_translate("Form", "TextLabel", None))
        self.pushButton.setText(_translate("Form", "Calculate", None))
        self.label_32.setText(_translate("Form", "TextLabel", None))
        self.label_33.setText(_translate("Form", "TextLabel", None))
        self.label_34.setText(_translate("Form", "TextLabel", None))
        self.label_35.setText(_translate("Form", "TextLabel", None))
        self.pushButton_2.setText(_translate("Form", "PushButton", None))
        self.label_36.setText(_translate("Form", "TextLabel", None))
        self.pushButton_3.setText(_translate("Form", "PushButton", None))

